# From limited data to populations

In the last exercise we analyzed data from the Demographic and Health Survey^[To learn more about this survey, please visit the DHS website at https://dhsprogram.com/] to look at data supporting the 
monitoring of the nutritional state of children by using anthropometric data.¶

The data allow for producing tables like - for example - the following from the DHS model
data set we also used for an exercise in the previous section.
```{r}
library(JWL)
data  <- children_nutrition_data

stunting_by_region <- by(data, data$region, with, weighted.mean(nt_ch_stunt, wt)) |> as.numeric() |> round(2)
wasting_by_region <-  by(data, data$region, with, weighted.mean(nt_ch_wast, wt)) |> as.numeric() |> round(2) 

tab <- data.frame(Region = c("Region 1", "Region 2", "Region 3", "Region 4"),
                             Stunted = stunting_by_region, Wasted = wasting_by_region)
knitr::kable(tab, caption = "Percentage of stunted and wasted children by Region")
```
These percentages are calculated from measurements of 2494 observations. 
Now even a small region in a thinly populated area will have more children than
that. For instance the tiny European state of Liechtenstein, a small 62 square miles sliver of land
between Austria and Switzerland has currently about 38.000 inhabitants. To a rough approximation even there
the number of children under 59 month - the group for which the anthropometric measurments of the DHS were taken -
is about this size or larger.

The data of the demographic and health survey are collected by selecting some households in a country and
asking them questions to their members or by taking measurements from them.
Surveys are huge and expensive projects which require complex logistics to work properly.
The researchers in such a project are not interested
in what particular respondents say or what are their particular anthropometric data are. In fact the
individual respondents are anonymous in the collected data set. The questions are asked to find
overall patterns in - for example - the nutritional status of children and infants in a country
or in an administrative region.

But how can we say something about such a pattern in a country or a
region by just asking a group of people or by taking some measurements from them? How can we be
confident about the results beyond just claiming that we can generalize from the data of people
we asked to the population pattern we are ultimately interested in? How can we ask or
measure people in a way that the analysis of data from this subset allows to learn something
about these measures in the entire population? 

In this chapter we discuss how such a seemingly
magical generalization can work at all and what needs to be considered before making such 
sweeping generalizations with some level of confidence.

The process of going from responses or measurements in a survey to patterns in a country of region
proceeds in four stages as explained in @Spi2019. 

Let us take the DHS as an example. 

Stage 1:

In the first stage of the data collection process the DHS a group of
households is selected from the larger population about which we want to learn 
something. In technical
terms the selected group is called a **sample** and the larger population about we
ultimately hope to learn something is called the **target population**. The sample
and all the successful and failed measurements in the sample will give us the
**raw data**. From this we can get information about ...

Stage 2:

The **true** numbers of height and weight in our sample, which contains
information about ...

Stage 3:

The height and weight in the **study population**, the people that could have potentially
been included in the survey, which contains information about ...

Stage 4: 

The height and weight of children in our **target population**.

It is important to understand that at all these stages errors can occur. 

For example
on the way from the raw data to our sample - the step from stage 1 to stage 2 -
we have to make assumptions on how accurately
the field workers have taken their height and weight measurements. Or if we ask questions, 
we need to make assumptions on how accurately people respond. 

When we go from the sample to the study population - from stage 2 to stage 3 - we need to
be confident that the people asked or measured are a **random sample** from those who could be
asked in principle. We have not yet introduced probability and what we mean exactly with 
a random sample. But at this stage it is sufficient to rely on our intuitive understanding
of what random means and why it is important. Assume the sample had not been selected at random. Say
the DHS survey team would drive through a region and stop here and there to interview households. This
method risks that some households are much more likely to be in the sample than others - for example the 
ones who are easy to reach on the road. Then in going from 2 to 3 we will make mistakes because we will
measure using a sample that is not comparable to the study population. Even worse we can not even quantify the
error we are making.

Now if a survey is done properly and professionally, as we can be confident with the DHS, this is
something we can usually assume. But even then we need to assume that the people who agree to take
part in the survey, those in our sample that cooperate with the survey team, i.e. answer questions, 
agree to have anthropocentric measurements taken of their children, are representative. Otherwise
comparisons with the larger group about which we ultimately want to say something, will be problematic.
Assuring that the people in the sample who cooperate are representative is more difficult to assure.
There are methods and procedures to address this difficulty systematically. For the moment it is 
important for you to recognize this as a potential source of error.

When we assume that the people who could potentially have been asked to participate in the survey
represent the population of a country or a region, then the last step - going from stage 3 to stage 4 - 
is more straightforward. If the sample has been chosen with sufficient care this will be
possible. It is, however, not easy in practice.

Considering all these potential sources of error you might become sceptical whether it is
possible to say something reliable at all. The good news is that statistics as a science and the
methods you are going to learn during this course can smooth and control the process of
going through these four steps where you indeed can say something very reliable and you
can even precisely quantify the uncertainty that remains in what you are saying. 


## Learning from data and the process of inductive inference.

In this section we can discuss the importance of random sampling by demonstrations using R
a good example for this is in data08.

Maybe explain the DHS sampling process.

<!-- ## How does the DHS sample its data -->

<!-- DHS is a nationally representative, population based cross sectional household survey. The survey is representative at the -->
<!-- national level, for urban and rural areas and for the first administrative subunit. -->

<!-- population based: data are collected through interviews of a representative sample of  -->
<!-- households. Interviewers visit selcetd households, collecting data from the household. -->

<!-- cross-sectional: A snapshot of an area at a particular point in time. -->

<!-- first government level below the national unit, such as region, state or zone -->

<!-- target population: women and men of reproductive age (15-49) of all backgrounds -->

<!-- 4 stages in the DHS survey process: -->

<!-- Stage 1 survey design and questionnaire six months -->
<!-- Stage 2 training interviewers and collecting data 6 month -->
<!-- Stage 3 data editing, tabulation and report writing 1 year -->
<!-- Stage 4 Dissemination and analysis 6-7 months -->


<!-- ## Contents -->

<!-- Inductive inference requires working from data to study sample and study population to target population. -->

<!-- At each stage bias can crop up. -->
<!-- The best way to proceed from sample to study population is if you have drawn a random sample. -->
<!-- Introduce the idea that a population can be thought of as a group of individuals but also as a probability distribution for a random observation drawn from that population -->
<!-- Populations can be summarized using parameters that mirror the summary statistics of sample data. -->
<!-- It often occurs that data do not arise as a sample from a literal population. We can always imagine data as drawn from a metaphorical population of events that could have occurred but didn’t. -->

<!-- ## Outcome -->

<!-- Make the concept of a random sample and a probability distribution tangible by using the computer. -->