# **Introduction**

What is the biggest source of electricity production in Kenya? Answering 
this question needs data listing and recording various forms of 
electricity production in specific countries. An internationally 
acknowledged organisation, which collects and reports these data 
is the International Energy Agency (IEA). 

:::{.callout-tip}
## Accessing IEA data on the internet

If you have access to the internet,
you can look up data and reports by the IEA on it's website
https://www.iea.org/ 
:::



Now let's take a quiz and guess. What do you think is
actually the biggest source of electricity production in Kenya?

1. Coal
2. Renewable energy
3. Natural gas

Consulting the IEA data, you will find that the correct answer 
is *renewable energy*. A very interesting website 
called *gapminder*, which analyzes the answers of
many people to this question, finds that 61 % give a wrong answer to this
question. Maybe they find it hard to imagine that 80 % of energy production in 
Kenya is already fossil free thanks to huge 
sources of geothermal- and hydropower.^[Geothermal electricity generation uses the earth's natural heating energy - geothermal energy. A country needs to be located on a geothermal hot spot to make effective use of this enegry source for electricity generation. At such a hotspot there are high temperatures beneath the earth's surface which naturally produces steam. This steam can be used to spin turbines connected to a generator. This mechanism then produces electricity. Hydropower uses  the water cycle to generate electricity by using dams to alter the flow of a river. The kinetic energy of the water spins tubrines connected to a generator which produces electricity.]  Even if you break the answers down by
country you see that 38 % of people from Kenya get the answer wrong. Among
the people from the UK, who answer this question even 72 % answer wrongly.

If you are not familiar with the details of electricity production using 
geothermal- and hydropower or if you are not completely sure how 
to interpret a number like 38 %, don't worry for now. The point here is 
that you see that one useful consequence of being able to access, read and 
interpret data is that it can help to establish facts about the world. In this
way data can´
help us to perhaps correct misconceptions we might have had about these
facts. 

:::{.callout-tip}
## The gapminder webpage
If you have internet access you can reach the gapminder webpage at https://www.gapminder.org/). I encourage you to visit this page at an occasion 
when you have access to the internet. You will be surprised how often you
might have a wrong guess about basic facts in the world.
:::

In this course you will learn how to work with data and how to learn from these
data in a systematic way. 

Learning from data entails more than just establishing
facts. This might not always be possible, either because you cannot access the
relevant data or you cannot completely access them, since doing so would be
way too expensive. When working with data you also need rigorous definitions
of concepts, so that you can transform your experience about the world into
data

Think for a moment about the following interesting 
example, which I learned from a wonderful book by the British 
statistician David Spiegelhalter [@Spi2019]. The example shows that even
just categorizing and labeling things in the world to measure them and turn
them into data can be challenging. A very basic question raised in 
the introduction of this book is:

::: {.callout-note icon=false}

## Question:

How many trees are there on the planet?

:::

It is clear that answering this question is more challenging than the task 
the IEA had to solve when listing energy sources by country around the world 
in a given time period. 
But before you go about to think how you might count all the trees on
the planet, you have to answer
an even more basic question, namely: What is a tree? Some of you might think
this is a silly and obvious question, which every child can answer. But 
what some might consider a tree others will consider just a shrub. 
Turning experience into data requires rigorous definitions. It turns out 
that such definitions can be given for trees. ^[For example the 
forestry expert Michael Kuhns writes: "...*Though no scientific definition exists to separate trees and shrubs, a useful definition for a tree is a woody plant having one erect perennial stem (trunk) at least three inches in diameter at a point 4-1/2 feet above the ground, a definitely formed crown of foliage, and a mature height of at least 13 feet. This definition works fine, though some trees may have more than one stem and young trees obviously don't meet the size criteria. A shrub can then be defined as a woody plant with several perennial stems that may be erect or may lay close to the ground. It will usually have a height less than 13 feet and stems no more than about three inches in diameter.*" [@Kuh]] 

But even with the definition at
hand you cannot just go around the planet and count every plant that meets the
criteria. So this is what the researchers investigating that question 
did according to [@Spi2019]: 

"...*They first took a series of of areas with a common type of landscape, known as a biome and counted the average number of trees per square kilometer. They then used satellite imaging to estimate the total area of the planet covered by each type of biome, carried out some complex statistical modelling, and eventually came up with an estimate of 3.04 trillion (3,040,000,000,000) trees on the planet. This sounds a lot, except that they reckoned there used to be twice this number*."

Now imagine that if long expert discussions are needed to precisely 
define something
so seemingly obvious as a tree, clearly more complex concepts
such as unemployment or the definition of the total value of goods ans services
produced in a country in a given year, known as Gross Domestic Product 
or GDP, is
even more challenging. 

There is no automatism or mechanical receipt how we can 
turn experience into data
and the statistics that we use and produce are constructed on the basis of
judgement. It is a starting point for a deeper understanding of the world 
around us. This is one of the reasons why in this course statistics is
not only referred to as science, which it arguably is to some degree, but also
as an art.

One of the limitations of data as a source of knowledge about the world is
that anything we choose to measure will differ across places, across persons
or across time. When analyzing and trying to understand data we will always
face the problem how we can extract meaningful insights from this
apparent random variation. One challenge faced by statistics and one
core topic in this course will thus be how we can distinguish in data the
important relationships from the unimportant background variability. 

Exploring and finding such meaningful relationships or patterns 
in data using the
science of statistics and computational tools is one of the skills you will
learn in this course. When we speak of patterns, we mean that sometimes
we can see data increasing or decreasing. In this case we speak of an upward
or a downward trend.

Consider the following data from the world bank reporting the 
share of people in the world who are living in extreme poverty. 
Extreme poverty is defined by the World Bank, an international organisation located in the US^[Footnote World Bank] as the percentage 
of people in the world who
have to live on less that $ 1.90 per day. If you look at these data in a table
you can see the following numbers:

Visualizing trends in world extreme poverty as an example of data
exploration.

But finding relationships and patterns in data naturally 
leads to another set of skills that you acquire by learning 
statistics: Making predictions, which means using available data and information to make informed guesses about data and information we do not have.

Example, take falling trend in poverty, make prediction
on the trend, show that corona for the first time in many years reversed the
trend look for the gapminder example.

this can then lead to the third point, quantifying uncertainty.


Introduce the concept of statistics and give an overview what students will learn during the course. In the introductory unit I would like to include an activity on variation or an interesting visualization where students see the code (which they do not yet understand in detail) but can change certain details and experiment on the computer how the visualization changes. This will also provide a first check of whether the software and hardware work for each student. I would also like to discuss why statistics is important and get students involved by collecting data on them for use later in the course. I would like to have lots of involvement in the first unit to set expectations for plenty of participation.

The overall goals of this course might be described as follows: After successfully completing this course students will have learned new skills in three core pillars of statistics

1.  Data exploration or finding patterns in data and information through visualisation and computation.

2.  Making predictions, which means using available data and information to make informed guesses about data and information we do not have.

3.  To quantify the uncertainty we have to attach to our predictions.

Simultaneously with these three core skills the students will learn to use the computer and modern computing tools to apply this knowledge to real world data. The combination of these skills will empower students to achieve a level of data literacy allowing them to independently work with new data and new situations they encounter in their professional life after completing the course or in their further studies.

As sources for my notes I rely very much on [@FrePisPur2009] on [@Kap2009] and in particular on Spiegelhalter's wonderful exposition [@Spi2019] in terms of concepts and the logic how the concepts are developed. Important sources for examples are \[@BekKes2021\], \[@GelNol2017\] as well as [@PeCa2005] as well as [@AdhDen], who wrote the textbook for Berkeley's introductory data science course Data08.

My vision would be to achieve a suitably adapted combination of Spiegelhalter and Adhikari, DeNero and Wagner. While the former is the didactically best exposition of statistics I have ever encountered, the latter is unmatched in explaining modern computational tools at a basic level. For this course, however both sources need to be substantially reworked. Spiegelhalter is written for a general audience of readers. Here we need to teach the concepts and actively involve students through exercises and projects they do themselves. I will thus follow the conceptual development logic of Spiegelhalter -- and in this lecture note outline I have literally done so -- but I would like to find a different and more interactive exposition with perhaps also different examples, nearer to the live context of students. Adhikari, DeNero and Wagner is for this course a bit too much tilted towards computation and perhaps not enough towards statistics. On the other hand this is a lightening rod for how I would like to see this course roughly turn out in terms of exposition and the use of the computational tools, in particular notebooks and coding style.
