<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics - 4&nbsp; From limited data to populations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./what_causes_what.html" rel="next">
<link href="./summarizing_and_communicating_lots_of_data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><strong>Introduction</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical_data_and_proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Data and Proportions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summarizing_and_communicating_lots_of_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and communicating lots of data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from_limited_data_to_populations.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_causes_what.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">What causes what?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling relationships using regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./algorithmic_prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Algorithmic prediction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_sure_can_we_be.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variablility</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_and_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answering_questions_and_claiming_discoveries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Answering questions and claiming discoveries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-from-data-and-the-process-of-inductive-inference." id="toc-learning-from-data-and-the-process-of-inductive-inference." class="nav-link active" data-scroll-target="#learning-from-data-and-the-process-of-inductive-inference."><span class="toc-section-number">4.1</span>  Learning from data and the process of inductive inference.</a></li>
  <li><a href="#why-does-random-sampling-help-avoiding-bias" id="toc-why-does-random-sampling-help-avoiding-bias" class="nav-link" data-scroll-target="#why-does-random-sampling-help-avoiding-bias"><span class="toc-section-number">4.2</span>  Why does random sampling help avoiding bias?</a>
  <ul class="collapse">
  <li><a href="#a-virtual-game-of-chance-rolling-a-die" id="toc-a-virtual-game-of-chance-rolling-a-die" class="nav-link" data-scroll-target="#a-virtual-game-of-chance-rolling-a-die"><span class="toc-section-number">4.2.1</span>  A virtual game of chance: Rolling a die</a></li>
  <li><a href="#a-brief-digression-writing-r-functions-yourself" id="toc-a-brief-digression-writing-r-functions-yourself" class="nav-link" data-scroll-target="#a-brief-digression-writing-r-functions-yourself"><span class="toc-section-number">4.2.2</span>  A brief digression: Writing R functions yourself</a></li>
  <li><a href="#going-back-to-simulating-die-rolls" id="toc-going-back-to-simulating-die-rolls" class="nav-link" data-scroll-target="#going-back-to-simulating-die-rolls"><span class="toc-section-number">4.2.3</span>  Going back to simulating die rolls</a></li>
  <li><a href="#the-law-of-averages" id="toc-the-law-of-averages" class="nav-link" data-scroll-target="#the-law-of-averages"><span class="toc-section-number">4.2.4</span>  The law of averages</a></li>
  </ul></li>
  <li><a href="#when-all-data-are-available" id="toc-when-all-data-are-available" class="nav-link" data-scroll-target="#when-all-data-are-available"><span class="toc-section-number">4.3</span>  When all data are available</a></li>
  <li><a href="#the-normal-approximation-for-data" id="toc-the-normal-approximation-for-data" class="nav-link" data-scroll-target="#the-normal-approximation-for-data"><span class="toc-section-number">4.4</span>  The normal approximation for data</a>
  <ul class="collapse">
  <li><a href="#the-normal-curve" id="toc-the-normal-curve" class="nav-link" data-scroll-target="#the-normal-curve"><span class="toc-section-number">4.4.1</span>  The normal curve</a></li>
  <li><a href="#units-and-standard-units" id="toc-units-and-standard-units" class="nav-link" data-scroll-target="#units-and-standard-units"><span class="toc-section-number">4.4.2</span>  Units and standard units</a></li>
  <li><a href="#exercises-now-you-try" id="toc-exercises-now-you-try" class="nav-link" data-scroll-target="#exercises-now-you-try"><span class="toc-section-number">4.4.3</span>  Exercises: Now you try</a></li>
  </ul></li>
  <li><a href="#finding-areas-under-the-normal-curve-with-r" id="toc-finding-areas-under-the-normal-curve-with-r" class="nav-link" data-scroll-target="#finding-areas-under-the-normal-curve-with-r"><span class="toc-section-number">4.5</span>  Finding areas under the normal curve with R</a>
  <ul class="collapse">
  <li><a href="#exercises-now-you-try-1" id="toc-exercises-now-you-try-1" class="nav-link" data-scroll-target="#exercises-now-you-try-1"><span class="toc-section-number">4.5.1</span>  Exercises: Now you try</a></li>
  </ul></li>
  <li><a href="#the-normal-approximation-for-data-1" id="toc-the-normal-approximation-for-data-1" class="nav-link" data-scroll-target="#the-normal-approximation-for-data-1"><span class="toc-section-number">4.6</span>  The normal approximation for data</a></li>
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles"><span class="toc-section-number">4.7</span>  Percentiles</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="page-columns page-full"><p>In the last exercise of section 3 we analyzed data from the Demographic and Health Survey.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> We looked at data monitoring of the nutritional state of children by using anthropometric data.¶</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;To learn more about this survey, please visit the DHS website at https://dhsprogram.com/</p></li></div></div>
<p>The data allow for producing tables like - for example - the following from the DHS model data set showing the share of children that are stunted and wasted by region.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data  <span class="ot">&lt;-</span> children_nutrition_data</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>stunting_by_region <span class="ot">&lt;-</span> <span class="fu">by</span>(data, data<span class="sc">$</span>region, with, <span class="fu">weighted.mean</span>(nt_ch_stunt, wt)) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>wasting_by_region <span class="ot">&lt;-</span>  <span class="fu">by</span>(data, data<span class="sc">$</span>region, with, <span class="fu">weighted.mean</span>(nt_ch_wast, wt)) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>() <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Region =</span> <span class="fu">c</span>(<span class="st">"Region 1"</span>, <span class="st">"Region 2"</span>, <span class="st">"Region 3"</span>, <span class="st">"Region 4"</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Stunted =</span> stunting_by_region, <span class="at">Wasted =</span> wasting_by_region)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab, <span class="at">caption =</span> <span class="st">"Percentage of stunted and wasted children by Region"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Percentage of stunted and wasted children by Region</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">Stunted</th>
<th style="text-align: right;">Wasted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Region 1</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Region 2</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Region 3</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Region 4</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.08</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These percentages are calculated from measurements of 2494 observations. Now even a small region in a thinly populated area will have more children than that. For instance the tiny European state of Liechtenstein, a small 62 square miles sliver of land between Austria and Switzerland has currently about 38.000 inhabitants. To a rough approximation even there the number of children under 59 month - the group for which the anthropometric measurments of the DHS were taken - is about this size or larger.</p>
<p>The data of the demographic and health survey are collected by selecting some households in a country and asking questions to their members or by taking measurements from them. This process of asking and measuring not the whole population but a subset of it is called a <strong>survey</strong>.</p>
<p>Surveys are huge and expensive projects which require complex logistics to work properly. The researchers in such a project are not interested in what particular respondents say or what are their particular anthropometric data are. In fact the individual respondents are anonymous in the collected data set. The questions are asked to find overall patterns in - for example - the nutritional status of children and infants in a country or in an administrative region.</p>
<p>But how can we say something about such a pattern in a country or a region by just asking a group of people or by taking some measurements from them? How can we be confident about the results beyond just claiming that we can generalize from the data of people we asked to the population pattern we are ultimately interested in? How can we ask or measure people in a way that the analysis of data from this subset allows to learn something about these measures in the entire population?</p>
<p>In this section we discuss how such a seemingly magical generalization can work at all and what needs to be considered before making such sweeping generalizations with some level of confidence. We will not learn here exactly how survey, like the DHS are done but use the survey example to introduce you to some general ideas ans principles of going from statements about a subgroup in a population, a <strong>sample</strong>, to the population as a whole.</p>
<p>The process of going from responses or measurements in a survey to patterns in a country or region proceeds in four stages as explained in <span class="citation" data-cites="Spi2019">Spiegelhalter (<a href="references.html#ref-Spi2019" role="doc-biblioref">2019</a>)</span>. We follow here his four stages taking the he DHS as an example.</p>
<p>Stage 1:</p>
<p>In the first stage of the data collection process DHS selects a group of households from the larger population about which we want to learn something. In technical terms the selected group is called a <strong>sample</strong> and the larger population about we ultimately hope to learn something is called the <strong>target population</strong>. The sample and all the successful and failed measurements in the sample will give us the <strong>raw data</strong>. From this we can get information about …</p>
<p>Stage 2:</p>
<p>The <strong>true</strong> numbers of height and weight in our sample, which contains information about …</p>
<p>Stage 3:</p>
<p>The height and weight in the <strong>study population</strong>, the people that could have potentially been included in the survey, which contains information about …</p>
<p>Stage 4:</p>
<p>The height and weight of children in our <strong>target population</strong>.</p>
<p>It is important to understand that at all these stages errors can occur.</p>
<p>For example on the way from the raw data to our sample - the step from stage 1 to stage 2 - we have to make assumptions on how accurately the field workers have taken their height and weight measurements. Or if we ask questions, we need to make assumptions on how accurately people respond.</p>
<p>When we go from the sample to the study population - from stage 2 to stage 3 - we need to be confident that the people asked or measured are a <strong>random sample</strong> from those who could be asked in principle. We have not yet introduced probability and what we mean exactly with a random sample. But at this stage it is sufficient to rely on our intuitive understanding of what random means and why it is important. Assume the sample had not been selected at random. Say the DHS survey team would drive through a region and stop here and there to interview households. This method risks that some households are much more likely to be in the sample than others - for example the ones who are easy to reach on the road. Then in going from 2 to 3 we will make mistakes because we will measure using a sample that is not comparable to the study population. Even worse we can not even quantify the error we are making.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/random_sample.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Random Sample</figcaption><p></p>
</figure>
</div>
<p>Now if a survey is done properly and professionally, as we can be confident with the DHS, we can usually assume that a proper random sample has been chosen. But even then we need to assume that the people who agree to take part in the survey, those in our sample that cooperate with the survey team, i.e.&nbsp;answer questions, agree to have anthropometrric measurements taken of their children, are representative. Otherwise comparisons with the larger group about which we ultimately want to say something, will be problematic. Assuring that the people in the sample who cooperate are representative is more difficult to assure. There are methods and procedures to address this difficulty systematically. For the moment it is important for you to recognize this as a potential source of error.</p>
<p>When we assume that the people who could potentially have been asked to participate in the survey represent the population of a country or a region, then the last step - going from stage 3 to stage 4 - is more straightforward. If the sample has been chosen with sufficient care this will be possible. It is, however, not easy in practice.</p>
<p>Considering all these potential sources of error you might become skeptical whether it is possible to say something reliable from limited data about the population at all. The good news is that statistics as a science and the methods you are going to learn during this course can smooth and control the process of going through these four steps where you indeed can say something very reliable and you can even precisely quantify the uncertainty that remains in what you are saying.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Assume a farmer wants to know the average yield of some crop - say maize - in a particular region. He cannot measure the yield on each and every field. So he takes a sample. Taking the notions we have explained in the previous discussion, in this example describe in words what precisly is the sample, what is the target population, what is the study population?</p></li>
<li><p>Suppose you are a an official statistician in the ministry of education in your country and the minister wants to learn about the avergage performance of students on a standardized test in your countries. Again, assume it is not possible to test all students but only a sample. Taking the notions we have explained in the previous discussion, in this example describe in words what precisly is the sample, what is the target population, what is the study population?</p></li>
<li><p>Finally, assume you are the head of a firm and you would like to know the average level of customer satisfaction among your customers. You cannot ask all your customers but only a sample. Explain the meaning of the notions in this context, what is the sample, what is the study population and what is the target population?</p></li>
</ol>
</div>
</div>
<section id="learning-from-data-and-the-process-of-inductive-inference." class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="learning-from-data-and-the-process-of-inductive-inference."><span class="header-section-number">4.1</span> Learning from data and the process of inductive inference.</h2>
<p>In the preceding chapters we have looked at examples where we had given data. Analysis of this data was sufficient if we just appropriately summarized them or displayed the data in an insightful way.</p>
<p>Sometimes this is really all there is to do. For instance when we studied the time trend in infant mortality we just looked at the time series of mortality data and a plot showed us the complete answer. The data we previously plotted for Ghana and Kenya - for example - show a steady decrease since 1965 starting from a share of roughly 12 % down below 2 % in 2020. These are data from public registers and not samples. The data are based on a complete set of observations in a country.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>pl_dat <span class="ot">&lt;-</span> <span class="fu">with</span>(infant_mortality_data, infant_mortality_data[Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ghana"</span>,<span class="st">"Kenya"</span>) <span class="sc">&amp;</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                                                            Year <span class="sc">&gt;=</span> <span class="dv">1965</span>, ])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pl_dat, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Mortality, <span class="at">color =</span> Country)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>     <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>     <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>But sometimes we want to say more about the data. We would like - for instance - to make predictions on how, for example, the trend in this share is going to look like in the future where we do not yet have data.</p>
<p>Or maybe we would like to say something more basic. For example why did the share show a long term downward trend in those countries.</p>
<p>Such generalisations, where we try to learn something about the world outside of our observations, based on these observations are called in statistics <strong>inductive inference</strong>. Inductive inference is a challenging idea and it had been the topic of many philosophical and methodological controversies among scholars in the past.</p>
<p><strong>Deductive reasoning</strong> derives particular conclusions from general premises using the rules of logic. In this way if the assumptions hold and the reasoning is done correctly, i.e.&nbsp;the rules of logic are properly applied the conclusions is certain and irrefutable. A toy example of deductive reasoning would for instance be:</p>
<ul>
<li>Major Premise: All plants perform photosynthesis.</li>
<li>Minor Premise: A cactus is a plant.</li>
<li>Conclusion: A cactus performs photosynthesis.</li>
</ul>
<p>Modern mathematical reasoning is all built on deduction, allowing to come up with actual proofs of certain statements given a set of axioms or assumptions. A proof is possible because deduction is logically certain.</p>
<p><strong>Inductive reasoning</strong> works differently. It starts from particular instances and tries to work out generalizations from there. It goes from data to hypothesis. A simple toy example for inductive reasoning would be:</p>
<ul>
<li>Data: I see fireflies in my garden every summer.</li>
<li>Hypothesis: This summer I will probably see fireflies in my garden.</li>
</ul>
<p>Induction does not allow to proof a hypothesis because it is generally uncertain.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>Think of another example for</p>
<ol type="1">
<li><p>deductive reasoning</p></li>
<li><p>inductive reasoning.</p></li>
</ol>
</div>
</div>
<p>Let us go back to the entire process of going from the raw data to the statements about the entire country or region in the DHS survey.</p>
<p>When we go from the sample to the true data about the units in the sample, the step from stage 1 to stage 2, we have to think careful about issues or problems of measurement. We want to know whether our data are reliable. They should have a low variability from occasion to occasion and should measure the same thing when we repeat a measurement. They should also measure what we intend or want to measure. This is called validity. We do not want our data to have a systematic bias.</p>
<p>Here is the idea of a random in a stylized picture. The big circle is the frame for the population from which you take a sample. The unit of obervation in the DHS and in this example is a household. The read households are picked at random from the population and put into the sample.</p>
<p>When we take again the DHS as an example, where people are asked many questions and quite a few measurements are taken on individuals, questions should be such that people give the same or a similar answer each time they are asked this question. To some extend this can be tested but these tests are not perfect. We also need to assume that people answer honestly to questions. With measurements things are similar. We want that we get the same or a very similar result if we repeat a measurement and we need to assume that the survey field workers who take the measurements do their job diligently.</p>
<p>If questions would be biased towards a particular answer a survey would also not be valid. This needs special care in developing questions. In chapter 2 we have learned about framing effects. Framing effects are often used in marketing. For example in meat packaging it is well known that how you report certain facts about the packaged meat influences sales. If the same piece of meat is one time packaged with the text “75 % lean meat” and the other time with the text “25 % fat”, which is logically the same information, several studies showed that on average the first package is preferred. This and other details have to be considered when elicting information from the sample.</p>
<p>Now going from the second stage - from the sample - to the third stage - the study population requires particular care. We have to be confident that the sample observed accurately reflects characteristics of the larger group we are ultimately interested in and from which the sample has been taken. Technically this is also often called <strong>internal validity</strong>.</p>
<p>Here we come to a crucial idea how bias can be avoided, the idea of <strong>random sampling</strong>. Let us explain exactly what a random sample is. Using R will support us in developing this understanding. As an example data set of our population we use as an illustration in the following discussion, let us take the dataset on the height and weight of adult humans, we used in chapter 3.</p>
</section>
<section id="why-does-random-sampling-help-avoiding-bias" class="level2 page-columns page-full" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="why-does-random-sampling-help-avoiding-bias"><span class="header-section-number">4.2</span> Why does random sampling help avoiding bias?</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> socr_height_weight</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Height <span class="ot">&lt;-</span> dat<span class="sc">$</span>Height<span class="sc">*</span><span class="fl">2.54</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Weight <span class="ot">&lt;-</span> dat<span class="sc">$</span>Weight<span class="sc">*</span><span class="fl">0.4535924</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="page-columns page-full"><p>Remember that this was a data set with 25.000 observations and three variables, an index for each individual a number of height in cm and weight in kg.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Let’s look at the first 10 rows in this dataset.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Note that the original data set <code>socr_height_weight</code> measures height in inches and weight in lbs. To get cm from inches, we have to multiply by 2.54 and to get kg from lbs we have to multiply the numbers by 0.4535924. In the data we use here we use units of cm and kg</p></li></div></div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>show <span class="ot">&lt;-</span> <span class="fu">head</span>(dat, <span class="at">n=</span> <span class="dv">10</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(show) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(show, <span class="at">n=</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Index</th>
<th style="text-align: right;">Height</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">167.0896</td>
<td style="text-align: right;">51.25254</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">181.6486</td>
<td style="text-align: right;">61.90960</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">176.2728</td>
<td style="text-align: right;">69.41184</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">173.2702</td>
<td style="text-align: right;">64.56226</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">172.1810</td>
<td style="text-align: right;">65.45207</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">174.4925</td>
<td style="text-align: right;">55.92903</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">177.2972</td>
<td style="text-align: right;">64.18092</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">177.8374</td>
<td style="text-align: right;">61.89826</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">172.4727</td>
<td style="text-align: right;">50.97122</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">169.6272</td>
<td style="text-align: right;">54.73372</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each row of this table represents an individual. Each individual here is an adult person age 18 or more for which a measure of height and weight has been taken. So if we sample from the rows of this table, we get values for the index, the height and the weight of individuals.</p>
<p>We could now take samples of rows from the table by selecting every 50th row. Here is a way of how we could implement this in R. If you go back to our last section and remember what we have learned about subsetting, you might get an idea how to approach such a problem.</p>
<p>Let us first create a sequence of numbers starting from 1 and going until the last row in steps of length 5. This can be done without problems because 25000 rows are divisible by 50 and this procedure will select exactly 500 rows. Here is the R code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="fu">nrow</span>(dat), <span class="at">by =</span> <span class="dv">5</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sample_1 <span class="ot">&lt;-</span> dat[idx, ]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(sample_1) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(sample_1, <span class="at">n =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Index</th>
<th style="text-align: right;">Height</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">167.0896</td>
<td style="text-align: right;">51.25254</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">174.4925</td>
<td style="text-align: right;">55.92903</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">168.8787</td>
<td style="text-align: right;">57.81108</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">180.5727</td>
<td style="text-align: right;">63.50180</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">172.2978</td>
<td style="text-align: right;">64.08385</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let me explain. <code>seq()</code> is an R function which creates a regular sequence of numbers. The arguments specify where the sequence begins and where it ends as well as the step length it takes. We write this sequence into a variable <code>idx</code>. Since we do not want row names we delete these. Then we apply the subsetting rules we have learned in the last section to select all rows with index <code>idx</code> with all its variables.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can try this code yourself and apply it to another situation where you would for example select every 100th obervation in the dataframe.</p>
</div>
</div>
<p>While this is a sample from our population, this is not a random sample because there is no chance involved in selecting the rows. Random sampling is a sampling method that uses a random mechanism. This means that the probability of each unit in the population to become part of the sample is known.</p>
<section id="a-virtual-game-of-chance-rolling-a-die" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="a-virtual-game-of-chance-rolling-a-die"><span class="header-section-number">4.2.1</span> A virtual game of chance: Rolling a die</h3>
<p>We have not yet discussed the concept of probability. We will learn about probability later in the course. But we have all am intuitive notion of probability from simple games of chance, such as from rolling a die. If we throw a die the probability of each of the points shown on the die’s faces - 1, 2, 3, 4, 5 or 6 - is <span class="math inline">\(\frac{1}{6}\)</span>. This is the chance or probability we would attribute before throwing the die that it shows a particular number. When we can give a probability for each outcome of throwing a die, we have a probability distribution, which is in this particular example very simple, because the probability we have attributed to the different outcomes is always <span class="math inline">\(\frac{1}{6}\)</span>. The probability of each number showing up is the same, <span class="math inline">\(\frac{1}{6}\)</span>. We can show this in the form of a bar-plot, where each bar stands for an outcome and its height showing the probability of this outcome.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>die_out <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="dv">2</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="dv">3</span>,<span class="dv">10</span>),<span class="fu">rep</span>(<span class="dv">4</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="dv">5</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="dv">6</span>,<span class="dv">10</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create a histogram with 6 columns</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(die_out, </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>,  </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Face"</span>, </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent per unit"</span>, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probability Distribution Fair Die"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F)         </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.08</span>, <span class="fl">0.16</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"8 %"</span>, <span class="st">"16 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In contrast to this theoretical probability distribution an empirical distribution is the distribution of observed data. We encountered many such distributions in the previous sections and and we have learned how to summarize them graphically by histograms.</p>
<p>The computer allows us to create empirical distributions of results from throwing a virtual die. It is a simulation of a real situation where you would actually roll a six sided die physically.</p>
<p>This is an example which allows us to introduce some new functions and concepts in R, which we will need in the rest of the course.</p>
<p>First we create a virtual die by defining an appropriate R object. This die should represent a physical die, which you know from games of chance.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/die_picture.jpg" style="width:50.0%;height:50.0%" class="figure-img"></p>
<p></p><figcaption class="figure-caption">A die</figcaption><p></p>
</figure>
</div>
<p>The essential feature of the die is that it has six faces each showing different points starting from 1 to 6. In R we implement this by creating a vector of integers 1 to 6, like this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we have created the vector of integers 1,2,3,4,5,6 and saved these numbers in an object calles <code>die</code>.</p>
<p>Now R has a built in function, called <code>sample()</code> which can pick values at random from an object. We can tell R by using this function for instance that it should randomly pick a number from the six possible numbers of <code>die</code>.</p>
<p>This is how it works:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x=</span>die, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>The R-function <code>sample()</code> takes an object as argument. The second argument, called <code>size</code>, specifies the number of random picks or draws from the object. If we give the value 1 to <code>size</code> it is as if we threw the die once. We have now implemented in the computer an equivalent to physically throwing a die.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the stylized picture of a random sample, we had 24 households in the population from which we randomly picked a sample of 8. Use the sample function to pick randomly 8 numbers out of the numbers 1 to 24.</p>
</div>
</div>
<p>One feature that makes R so very powerful is that you can not only use built in functions, like <code>mean</code>, <code>hist</code> <code>sample</code> etc. but you can also write your own functions. We could for instance write a function which rolls a die if we call it.</p>
</section>
<section id="a-brief-digression-writing-r-functions-yourself" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="a-brief-digression-writing-r-functions-yourself"><span class="header-section-number">4.2.2</span> A brief digression: Writing R functions yourself</h3>
<p>Each function in R has the same elements: A <strong>name</strong>, a <strong>function body</strong> of code and a set of <strong>arguments</strong>. To write your own function, you have to write up all of these parts and save them in an R object.</p>
<p>The syntax is given like this:</p>
<p><code>my_function &lt;- function() {}</code></p>
<p>The name here is <code>my_function</code>, next comes the expression <code>function()</code> which needs to be assigned. The names of the function arguments have to be written between the parentheses. Then we have to write the actual code within the braces <code>{}</code>.</p>
<p>To do this for the die, lets write a function named <code>roll_die</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>roll_die <span class="ot">&lt;-</span> <span class="cf">function</span>(){die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">sample</span>(die, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we have written the function and saved it as an R-object we can call it like this. Let’s call it three times for example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Note that in our function <code>roll_die()</code> has no arguments, just the function body. This is perfectly legitimate in R. It is important that when we call the function we have to call it with the parenthesis like <code>roll_die()</code>. If we only call the name <code>roll_die</code>, R will display the code in the function body.</p>
<p>Congratulations ! You have written your first R function for conducting a simple random experiment. Let me remind you once again: Think of the parentheses as a trigger that tells R to run the function. If you omit the trigger R just prints the body of the function. When you run a function, all the code in the function body is executed and R returns the result of the last line of code. If the last line of code does not return a value neither will R.</p>
<p>Let me finally say a few things about <strong>arguments</strong> in a function.</p>
<p>Imagine we remove the first line of code in our function body and changed the name die in the sample function to “ball”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we call the function now, we will get an error. The function call <code>roll_die2()</code> will result in the error message <code>Error in sample(ball, size = 1) : object 'ball' not found</code> (try it!)</p>
<p>We could supply ball when we call <code>roll_die2</code> if we make ball an argument of the function. Lets do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(ball){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the function will work as long as we supply <code>ball</code> when we call the function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die2</span>(<span class="at">ball =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>Note that we still get an error, if we forget to supply ball argument. This could be avoided if we give the function a default argument</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">ball=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now if we type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>everything works, just as intended.</p>
</section>
<section id="going-back-to-simulating-die-rolls" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="going-back-to-simulating-die-rolls"><span class="header-section-number">4.2.3</span> Going back to simulating die rolls</h3>
<p>Now we are interested in an <strong>empirical distribution</strong> of points if we roll the die many times. A built in R function that would help us to do this. This function is called <code>replicate()</code>. It needs two arguments, how many times it should do something and of course what it should do precisely.</p>
<p>So if we roll our virtual die 10 times, we would tell R to do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>r10 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10</span>, <span class="fu">roll_die</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which gives us the sequence of results from these 10 rolls. Now let’s plot the empirical distribution.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(r10, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>,  </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Face"</span>, </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent per unit"</span>, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probability Distribution Fair Die"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F)         </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.08</span>, <span class="fl">0.16</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"8 %"</span>, <span class="st">"16 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This does look quite different from the theoretical distribution, where each bar had the same length.</p>
<p>When we increase the sample size the empirical distribution starts to look more similar to the theoretical distribution. Lets roll our die 100 times</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>r100 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">roll_die</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(r100, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>,  </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Face"</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent per unit"</span>, </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probability Distribution Fair Die"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F)         </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.08</span>, <span class="fl">0.16</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"8 %"</span>, <span class="st">"16 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looks better. What about 1000 rolls?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>r1000 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">roll_die</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(r1000, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>,  </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Face"</span>, </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent per unit"</span>, </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probability Distribution Fair Die"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F)         </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.08</span>, <span class="fl">0.16</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"8 %"</span>, <span class="st">"16 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we increase the number of rolls in the simulation, the area of each bar gets closer to 16.67% (<span class="math inline">\(\frac{1}{6}\)</span>), which is the area of each bar in the probability histogram.</p>
<p>Let’s do a last example with 100.000 rolls to show this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>r100000 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100000</span>, <span class="fu">roll_die</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(r100000, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>,  </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Face"</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent per unit"</span>, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probability Distribution Fair Die"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F)         </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.08</span>, <span class="fl">0.16</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"8 %"</span>, <span class="st">"16 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we are almost there.</p>
</section>
<section id="the-law-of-averages" class="level3 page-columns page-full" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="the-law-of-averages"><span class="header-section-number">4.2.4</span> The law of averages</h3>
<div class="page-columns page-full"><p>What we have just observed is a demonstration of a famous result of probability theory. We are going to learn about probabilities later in the course. This result, sometimes referred to as the law of averages.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;Technically the result is called the weak law of large numbers and was discovered by the Mathematician Jacob Bernoulli in 1713</p></li></div></div>
<p>The law says that if a chance experiment - such as throwing a fair die - is repeated independently and under identical conditions (this means that every repetition is performed in the same way regardless of the other repetitions.), then as we repeat the experiment long enough, the relative frequency of each event<br>
- in our case an event would be that for example the outcome of the die throw is 1 - gets closer to the theoretical probability of the event.</p>
<p>In the example of the die, we just studied by using the simulation capacities of R, we saw that the proportion that the die will land on a face showing 6 will happen in about 1/6 of all rolls.</p>
<p>This law also holds when a random sample is drawn from units of a large population. Let us use the table of heights in cm and weights in kg of 25.000 adults we studied in the last unit. Here we show the fist 10 rows.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> socr_height_weight</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># transfrom to metric units from inches to cm and from lbs to kg</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Height <span class="ot">&lt;-</span> data<span class="sc">$</span>Height<span class="sc">*</span><span class="fl">2.54</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Weight <span class="ot">&lt;-</span> data<span class="sc">$</span>Weight<span class="sc">*</span><span class="fl">0.4535924</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Index   Height   Weight
2      1 167.0896 51.25254
3      2 181.6486 61.90960
4      3 176.2728 69.41184
5      4 173.2702 64.56226
6      5 172.1810 65.45207
7      6 174.4925 55.92903
8      7 177.2972 64.18092
9      8 177.8374 61.89826
10     9 172.4727 50.97122
11    10 169.6272 54.73372</code></pre>
</div>
</div>
<p>Let us remind ourselves, how the histogram of the height-data looked like.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(data<span class="sc">$</span>Height, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">plot =</span> F)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>h<span class="sc">$</span>counts <span class="ot">&lt;-</span> h<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h<span class="sc">$</span>counts)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">xlab =</span> <span class="st">"Height"</span>, <span class="at">ylab =</span> <span class="st">"Percent"</span>, <span class="at">main =</span> <span class="st">"Height distribution of adults"</span>, <span class="at">axes =</span> F)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">170</span>, <span class="dv">180</span>, <span class="dv">190</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"160 cm"</span>, <span class="st">"170 cm"</span>, <span class="st">"180 cm"</span>, <span class="st">"190 cm"</span>))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"2 %"</span>, <span class="st">"4 %"</span>, <span class="st">"6 %"</span>, <span class="st">"8 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let us now think about the 25.000 adults in our data as a population. We draw a random sample from it. When we draw from the population we draw with replacement. This means when a particular individual is selected at one draw, it could in principle be selected also at the next one.</p>
<p>Let us write an R function for this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>emp_distr_height <span class="ot">&lt;-</span> <span class="cf">function</span>(n){</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  data[<span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data), <span class="at">size =</span> n, <span class="at">replace =</span> T), ]</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This function draws <code>n</code> random row from our dataframe. Note that <code>n</code> is an argument for the function. The random draws are a dataframe with N row indices, say 10, and then this gives the row index to the dataframe according to the subsetting rules we have learned in the previous section <code>data[rowindex, ]</code>. Since there is no index in the second slot the entire rows will be selected.</p>
<p>Now in analogy to the dice example we can see, that when we increase the number of draws into our sample we come closer to the distribution of the population. By this mechanism a random sample generates a subpopulation with similar distributional properties when the sample is large enough. How much is large enough? For this we need probability theory which we will encounter later in the course.</p>
<p>As with the die, let us start with 10 draws:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>hs10 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(hs10<span class="sc">$</span>Height, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">plot =</span> F)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>h<span class="sc">$</span>counts <span class="ot">&lt;-</span> h<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h<span class="sc">$</span>counts)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">xlab =</span> <span class="st">"Height"</span>, <span class="at">ylab =</span> <span class="st">"Percent"</span>, <span class="at">main =</span> <span class="st">"Height distribution of adults"</span>, <span class="at">axes =</span> F)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">170</span>, <span class="dv">180</span>, <span class="dv">190</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"160 cm"</span>, <span class="st">"170 cm"</span>, <span class="st">"180 cm"</span>, <span class="st">"190 cm"</span>))</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"2 %"</span>, <span class="st">"4 %"</span>, <span class="st">"6 %"</span>, <span class="st">"8 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This does not look very similar to the population distribution.</p>
<p>What about a sample with size 100?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hs100 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(hs100<span class="sc">$</span>Height, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">plot =</span> F)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>h<span class="sc">$</span>counts <span class="ot">&lt;-</span> h<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h<span class="sc">$</span>counts)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">xlab =</span> <span class="st">"Height"</span>, <span class="at">ylab =</span> <span class="st">"Percent"</span>, <span class="at">main =</span> <span class="st">"Height distribution of adults"</span>, <span class="at">axes =</span> F)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">170</span>, <span class="dv">180</span>, <span class="dv">190</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"160 cm"</span>, <span class="st">"170 cm"</span>, <span class="st">"180 cm"</span>, <span class="st">"190 cm"</span>))</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"2 %"</span>, <span class="st">"4 %"</span>, <span class="st">"6 %"</span>, <span class="st">"8 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now lets increase to 2500, 10 % of the population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>hs2500 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">2500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(hs2500<span class="sc">$</span>Height, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">plot =</span> F)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>h<span class="sc">$</span>counts <span class="ot">&lt;-</span> h<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h<span class="sc">$</span>counts)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">xlab =</span> <span class="st">"Height"</span>, <span class="at">ylab =</span> <span class="st">"Percent"</span>, <span class="at">main =</span> <span class="st">"Height distribution of adults"</span>, <span class="at">axes =</span> F)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">170</span>, <span class="dv">180</span>, <span class="dv">190</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"160 cm"</span>, <span class="st">"170 cm"</span>, <span class="st">"180 cm"</span>, <span class="st">"190 cm"</span>))</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"2 %"</span>, <span class="st">"4 %"</span>, <span class="st">"6 %"</span>, <span class="st">"8 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This looks already pretty close. You should by now see what random sampling does for the process of inductive inference. For a large enough random sample, the empirical distribution of the sample resembles the histogram of the population with high probability. Thus if you report summaries of the sample, like its mean and its standard deviation, you will be close to the true values in the population. You will not be exactly there. But since the random mechanism is based on a probability model, where the chance of each unit ending up in the sample is known, we can quantify the uncertainty and the error we make.</p>
<p>How probability arguments work more precisely, we will learn later in the course. For now this brief discussion should have convinced you of the importance of random sampling for making inferences from sample to population and given you an intuition how this works. As a side effect of this discussion you have also learned how to write R functions.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the <code>emp_distr_height()</code>function we have just written to draw a random sample of n=5000. Compute the mean and the standard deviation of the sample distribution. Compute - or look up in chapter 3 - the mean and the standard deviation of the population data and compare.</p>
</div>
</div>
<p>Now that we have discussed random sampling, why it is important and how it works, let us finally discuss the last step in the inductive inference chain, going from the study population to the target population. Even if we have a perfect random sample, it might be the case that we were not able to ask the people who we were ultimately interested in. When we can make conclusions on the target population from the study population, we say that we have not only internal but also <strong>external validity</strong>.</p>
<p><span class="citation" data-cites="Spi2019">Spiegelhalter (<a href="references.html#ref-Spi2019" role="doc-biblioref">2019</a>)</span>, whom we have already cited before gives an example where this problem is particularly extreme. Often scientist who are ultimately interested in humans could onl study animals, as it is often the case in pharmaceutical research.</p>
<p>A bit less extreme but related is a second example <span class="citation" data-cites="Spi2019">Spiegelhalter (<a href="references.html#ref-Spi2019" role="doc-biblioref">2019</a>)</span> gives is the case of drugs tested say only on adults but it is then used also by children. These are problems which cannot entiely be solved by statistical methods but need caution and particular care and caution.</p>
</section>
</section>
<section id="when-all-data-are-available" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="when-all-data-are-available"><span class="header-section-number">4.3</span> When all data are available</h2>
<p>While surveys are a very important instrument to learn from data about the reality we live in, not all data that are available to us today are surveys. Mainly by the internet and technological development, the omnipresence of sensors and digital devices, we have today many data that are not random samples or which are not based on any sampling at all.</p>
<p>Many data, especially from online commerce are available to platform firms and online shops, for example. The new field of data science git a big push from the attempt to get hold of data created through interactions on the internet and to gain information from these data.</p>
<p>The public sector also collects and stores lots of administrative data in a systematic manner. These are for example data needed to run a social security or pension system, police records, health records, demographic data, land registers and business registers, also data on crime, voters and education. These data are used for policy making, research and statistical analysis. In this case you have all the data.</p>
<p>Having all the data means that the stage of the induction process where we go from a sample to a study population collapses because the sample and the study population are the same.</p>
<p>Still problems can occur. <span class="citation" data-cites="Spi2019">Spiegelhalter (<a href="references.html#ref-Spi2019" role="doc-biblioref">2019</a>)</span> mentions the problem that the police systematically misses cases which the police does not record as a crime or which have not been reported by a victim. These problems make the step of drawing conclusions from the study population to the target population difficult. It is not only police records on crimes. You have analogous problems in all other register data as well. Take population register, as one example. Often certain groups such as homeless people or undocumented immigrants who may be hesitant to register or provide personal information are under-counted. Or you can have inaccuracies in property ownership data in land registers due to incomplete or outdated records, fraudulent transactions, or illegal land occupations. Or in health registers you could have missing or incomplete data on certain health conditions, especially those that are stigmatized or poorly understood, or patients who do not seek medical attention due to lack of access or fear of discrimination.</p>
<p>Of course if we have all the data it is a straightforward process to produce statistics that describe what we have measured. But for broader conclusions we need to be very careful and we need to think about systematic biases and how we can potentially control for them. This always needs our special attention because systematic bias can jeopardize or even invalidate the reliability of our claims.</p>
</section>
<section id="the-normal-approximation-for-data" class="level2 page-columns page-full" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="the-normal-approximation-for-data"><span class="header-section-number">4.4</span> The normal approximation for data</h2>
<p>We will now discuss an old and powerful concept that helps us in our ultimate aim to describe the target distribution. This is called the normal distribution or often also called the “bell curve”, because of its characteristic shape. We already encountered this distribution in the last exercise of chapter 3, when we worked with the DHS data.</p>
<section id="the-normal-curve" class="level3 page-columns page-full" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="the-normal-curve"><span class="header-section-number">4.4.1</span> The normal curve</h3>
<div class="page-columns page-full"><p>The normal curve was discovered first around 1720 by Abraham de Moivre<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> In 1809, the German mathematician Car Friedrich Gauss<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, made significant contributions to the concept of the normal curve, which is until today often also referred as a Gaussian curve. He used the curve to model errors in astronomical observations. Around 1870 the Belgian mathematician Adolphe Quetelet<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> had the idea of using the curve as an ideal histogram to which historams of empirical distributions could be compared.</p><div class="no-row-height column-margin column-container"><li id="fn4"><p><sup>4</sup>&nbsp;Abraham de Moivre (1667-1754) was a French mathematician known for his contributions to the development of probability theory and the normal distribution as well as for his work on complex numbers. He is perhaps best known for his discovery of the formula that bears his name, which relates complex numbers to trigonometric functions. De Moivre was also a prominent member of the scientific community in 18th-century Europe and corresponded with many of the leading mathematicians and scientists of his time. <img src="pictures/Abraham_de_moivre.jpg" class="img-fluid" alt="Abraham de Moivre"></p></li><li id="fn5"><p><sup>5</sup>&nbsp;Carl Friedrich Gauss (1777-1855) was a German mathematician and physicist who made significant contributions to a wide range of fields, including algebra, number theory, astronomy, and physics. Gauss is considered one of the greatest mathematicians of all time and is known for his contributions to the development of calculus, the discovery of the normal distribution, and his work on the theory of functions. Gauss also made important contributions to the field of astronomy, including the discovery of the asteroid Ceres and the development of a method for calculating the orbits of celestial bodies. <img src="pictures/Carl_Friedrich_Gauss_1840_by_Jensen.jpg" class="img-fluid" alt="Carl Friedrich Gauss"></p></li><li id="fn6"><p><sup>6</sup>&nbsp;Adolphe Quetelet (1796-1874) was a Belgian mathematician, astronomer, and statistician who is known for his work in developing the concept of the “average man” and the use of statistical methods in the social sciences. He is also credited with the development of the body mass index (BMI), which is still widely used today as a measure of obesity. Quetelet was a prominent figure in the scientific community of his time and was a founding member of the International Statistical Institute. <img src="pictures/Adolphe_Quételet_by_Joseph-Arnold_Demannez.jpg" class="img-fluid" alt="Adolphe Quetelet"></p></li></div></div>
<p>The normal curve has a slightly intimidating equation, which looks as follows <span class="math display">\[\begin{equation}
y = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{1}{2}\left( \frac{x - \mu}{\sigma}\right)^2}
\end{equation}\]</span></p>
<div class="page-columns page-full"><p>But don’t be afraid. You do not have to be able to manipulate this equation. This is something that R. We will learn how to do this.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn7"><p><sup>7</sup>&nbsp;The mathematical formula for the normal curve is very interesting, since it contains the most famous numbers in mathematics. We have already encountered <span class="math inline">\(\sqrt{2}\)</span>, the diagonal of the unit square, which is the first so called irrational number detected by the Pythagoreans in antiquity. For them it was quite a shock to discover that there are numbers which can not be represented as a fraction of whole numbers. There is the famous number <span class="math inline">\(\pi\)</span> also known since antiquity. This number represents the ratio of the circumference of any circle to its diameter and is also an irrational number. Finally there is the number <span class="math inline">\(e\)</span> or sometimes also known as Euler’s number. It is the limit of the sequence <span class="math inline">\((1+\frac{1}{n})^n\)</span> and plays a fundamental role all over mathematics.</p></li></div></div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Standard units"</span>, <span class="at">ylab =</span> <span class="st">"Percent per standard unit"</span>, <span class="at">main =</span> <span class="st">"The Normal Curve"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are several features of this graph that are important to note:</p>
<ol type="1">
<li>The graph is symmetric about 0. The part of the curve to the right is a mirror image of the part of the curve to the left.</li>
<li>The total area under the curve equals 1 or 100 %.</li>
<li>The curve is always above the horizontal axis. It appears to get equal to zero between 3 and 4 but this is only because the distance from the horizontal axis becomes too tiny to visualize. Only about 0.00006 of the area under the curve is outside of this interval.</li>
</ol>
<p>It will be important and helpful to find areas under the normal curve between specified values. For instance:</p>
<ol type="1">
<li>the area under the normal curve between +1 and - 1 standard deviations from the mean is about 68 %.</li>
<li>the area under the normal curve between -2 and +2 standard deviations is about 95 %.</li>
<li>the area under the normal curve between -3 and +3 standard deviations is about 99.7%</li>
</ol>
<p>Does this look familiar? If you followed the course until now, you will remember that these are the numbers we encountered with the data on human height. This is because for these data the empirical distribution is such that the respective histogram is very closely approximated by a normal curve.</p>
</section>
<section id="units-and-standard-units" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="units-and-standard-units"><span class="header-section-number">4.4.2</span> Units and standard units</h3>
<p>Often it is convenient to express the units for the normal curve not in the direct unit in which observations are measures - as for example cm for human height - but in units of standard deviations from the mean.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Conversion to standard units
</div>
</div>
<div class="callout-body-container callout-body">
<p>A value is converted to standard units by checking how many standard deviations it is above or below the average. Values above the average are given a plus sign, values below the average are given a minus sign.</p>
</div>
</div>
<p>Take an example from our human height data and draw 4 random values from these data, using the <code>emp_distr_height()</code> function we wrote earlier in this chapter say</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>example <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">4</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>example<span class="sc">$</span>Height</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 170.6928 172.0204 179.4628 168.0772</code></pre>
</div>
</div>
<p>Let us convert these values to standard units. Let us compute again the mean and the standard deviation of the height data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Height)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>std <span class="ot">&lt;-</span> <span class="fu">sd</span>(data<span class="sc">$</span>Height)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 172.7025</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>std</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.830264</code></pre>
</div>
</div>
<p>170.6928 is -0.4161 from the average. In standard units therefore 170.6928 is -0.4161.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>Convert the other values to standard units. Find the height which is 2.4 in standard units.</p>
</div>
</div>
<p>Standard units are used in the DHS data on nutrition of children and adults which we worked with in the last exercise of chapter 3. Standard units are also often referred to as the <strong>z-score</strong>. Let us go back to these data and look at them more closely again.</p>
<p>Let us go back to the histogram of human height we already discussed in the chapter 3.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(data<span class="sc">$</span>Height, <span class="at">plot =</span> F, <span class="at">breaks =</span> <span class="dv">30</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a> hist_breaks <span class="ot">&lt;-</span> h<span class="sc">$</span>breaks</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a> color_list <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">'#C6E2FF'</span>, <span class="fu">length</span>(hist_breaks))</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a> color_list[hist_breaks <span class="sc">&lt;=</span> m <span class="sc">+</span> std] <span class="ot">&lt;-</span> <span class="st">'#6C7B8B'</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a> color_list[hist_breaks <span class="sc">&lt;=</span> m <span class="sc">-</span> std] <span class="ot">&lt;-</span> <span class="st">'#C6E2FF'</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>) <span class="sc">+</span> <span class="fl">0.3</span>)  </span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">col =</span> color_list, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">xlab =</span> <span class="st">" "</span>, <span class="at">ylab =</span> <span class="st">"Percent per cm "</span>, <span class="at">main =</span> <span class="st">"Height distribution of adults"</span>, <span class="at">axes =</span> F)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">new =</span> <span class="cn">TRUE</span>) </span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="do">## Define x and y coordinates for normal curve</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a> x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(data<span class="sc">$</span>Height), <span class="fu">max</span>(data<span class="sc">$</span>Height), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a> y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, m, std)</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add normal curve to histogram plot</span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a> <span class="fu">lines</span>(x, y, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,  <span class="at">xlab =</span> <span class="st">" "</span>, <span class="at">ylab =</span> <span class="st">" "</span>)</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a> <span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">4</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.02</span>,<span class="fl">0.04</span>,<span class="fl">0.06</span>,<span class="fl">0.08</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0%"</span>, <span class="st">"9.7 %"</span>, <span class="st">"19.3 %"</span>, <span class="st">"29.0 %"</span>, <span class="st">"38.6 %"</span>), <span class="at">ylab =</span> <span class="st">"Percent per standard unit"</span>)</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="fl">153.38</span>, <span class="fl">158.21</span>, <span class="fl">163.04</span>, <span class="fl">167.87</span>, <span class="fl">172.70</span>, <span class="fl">177.53</span>, <span class="fl">182.36</span>, <span class="fl">187.19</span>, <span class="fl">192.02</span>), </span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"153.38 cm"</span>, <span class="st">"158.21 cm"</span>, <span class="st">"163.04 cm"</span>, <span class="st">"167.87 cm"</span>, <span class="st">"172.70 cm"</span>, <span class="st">"177.53 cm"</span>, <span class="st">"182.36 cm"</span>, <span class="st">"187.19 cm"</span>, <span class="st">"192.02 cm"</span>))</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="fl">153.38</span>, <span class="fl">158.21</span>, <span class="fl">163.04</span>, <span class="fl">167.87</span>, <span class="fl">172.70</span>, <span class="fl">177.53</span>, <span class="fl">182.36</span>, <span class="fl">187.19</span>, <span class="fl">192.02</span>), </span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"-4"</span>, <span class="st">"-3"</span>, <span class="st">"-2"</span>, <span class="st">"-1"</span>, <span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>), <span class="at">line =</span> <span class="fl">2.5</span>)</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.02</span>,<span class="fl">0.04</span>,<span class="fl">0.06</span>,<span class="fl">0.08</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>, <span class="st">"2 %"</span>, <span class="st">"4 %"</span>, <span class="st">"6 %"</span>, <span class="st">"8 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are two x-axis in this figure. On the upper x-axis you see the height in cm. On the lower x-axis you see the height in standard units. Standard unit 1 is at 172.70 + 4.83 or at 177.53 and standard unit -1 is at 172.70 - 4.83 or 167.87.</p>
<p>There are two vertical axis in this figure, one on the left and one on the right. The histogram is drawn relative to the left y-axis, which is in percent per cm. The normal curve is drawn relative to the right one. To see how the scale on the right y-axis matches up, take the top value on each of the two axes: 38.6 % per standard unit matches 8% per cm because there are 4.8 cm to the standard unit. Spreading 38.6 % over one standard deviation is the same as spreading 38.6 % over 4.8cm and that comes to 8% per cm.</p>
<p>We explained before that the area under the normal curve between - 1 and 1 standard deviation from the mean is 68 %. In histogram the area between these values is colored in gray. The historgam follows the normal curve very closely. Sometimes it is a bit above, sometimes a bit below the curve but these deviations balance out. Indeed, if you go back to the previous chapter you see that in the empirical distribution we have indeed 68% of observations exactly between these bounds. So the shaded area in the histogram is to a very good approximation equal to the area under the normal curve and this is where the 68 % come from.</p>
</section>
<section id="exercises-now-you-try" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="exercises-now-you-try"><span class="header-section-number">4.4.3</span> Exercises: Now you try</h3>
<ol type="1">
<li>On a cetrain exam, the average of the scores was 50 and the standard deviation was 10.
<ol type="a">
<li>Convert each of the following scores to standard units: 60, 45, 75.</li>
<li>Find the scores which in standard units are: 0, 1.5, -2.8</li>
</ol></li>
<li>Convert each entry on the following list to standard units (using the average and standard deviation of the list): 13, 9, 11, 7, 10. Find the average and the standard devition of the converted list.</li>
</ol>
</section>
</section>
<section id="finding-areas-under-the-normal-curve-with-r" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="finding-areas-under-the-normal-curve-with-r"><span class="header-section-number">4.5</span> Finding areas under the normal curve with R</h2>
<p>Before the computer became a widely available tool, statisticians used standard tables for finding areas under the curve. Today this is done with a computer. R has built in standard function you can use for this purpose. In this section I show you how.</p>
<p>Example 1:</p>
<p>Say we want to find the area under the normal curve between 0 an 1. Now one way to find this area is to use you knowledge that 68 % of the area under the nomal curve are between - 1 and 1. By the symmetry of the normal curve thus the area between 0 and 1 must be half of this area or 34 %.</p>
<p>When you use R to do this calculation the built in function is called <code>pnorm()</code>. This function gives you the area under the normal curve smaller or equal to a given value <span class="math inline">\(x\)</span>. The default value for the mean <span class="math inline">\(\mu\)</span> and the standard deviation <span class="math inline">\(\sigma\)</span> is <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma = 1\)</span>.</p>
<p>So what we would do is to compute:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">1</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3413447</code></pre>
</div>
</div>
<p>which gives 0.34 or 34 %.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/normal_curve_34.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example 1: Area under the normal curve between 0 and 1</figcaption><p></p>
</figure>
</div>
<p>Example 2:</p>
<p>Find the area between -2 and 1 under the normal curve with <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma = 1\)</span>.</p>
<p>This problem can be broken down by first computing the area under the normal curve for all values lower than 1 and then the area under the curve for all values lower than - 2 and subtract the latter from the former. In R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">1</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8185946</code></pre>
</div>
</div>
<p>or 82 %.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/normal_curve_84.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example 1: Area under the normal curve between -2 and 1</figcaption><p></p>
</figure>
</div>
<p>Example 3:</p>
<p>Find the area to the right of 1 under the normal curve. This can be done by finding the area under the normal curve left from 1 first. Since the total area is 1, it must be the case that 1 minus the value of the area left from 1 is the same as the area right of 1.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1586553</code></pre>
</div>
</div>
<p>or 16 %.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/normal_curve_16.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example 1: Area under the normal curve right of 1</figcaption><p></p>
</figure>
</div>
<section id="exercises-now-you-try-1" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="exercises-now-you-try-1"><span class="header-section-number">4.5.1</span> Exercises: Now you try</h3>
<ol type="1">
<li>Find the area under the normal curve:</li>
</ol>
<ol type="a">
<li>to the right of 1.25</li>
<li>to the left of 0.80</li>
<li>between -0.3 and 0.9</li>
<li>to the left of -0.4</li>
<li>between 0.4 and 1.3</li>
<li>outside -1.5 to 1.5</li>
</ol>
<ol start="2" type="1">
<li>Fill in the blanks:</li>
</ol>
<ol type="a">
<li>The area between +/- under the normal curve equals 68%</li>
<li>The area between +/- under the normal curve equals 75 %.</li>
</ol>
</section>
</section>
<section id="the-normal-approximation-for-data-1" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-normal-approximation-for-data-1"><span class="header-section-number">4.6</span> The normal approximation for data</h2>
<p>In certain cases the normal curve may be used to approximate data. We go back to our example with the data on the height of adult humans.</p>
<p>Say we have the information that the height of adult humans were on average 172.7 cm with a standard deviation of 4.83 cm. Assuming the distribution of the data can be approximated by a normal curve. What is the estimated percentage of humans with a height between 168 and 178 cm?</p>
<p>We can proceed in two steps. First we convert to standard units:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> (<span class="dv">168</span> <span class="sc">-</span> <span class="fl">172.7</span>)<span class="sc">/</span><span class="fl">4.83</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> (<span class="dv">178</span> <span class="sc">-</span> <span class="fl">172.7</span>)<span class="sc">/</span><span class="fl">4.83</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.9730849</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>u</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.097308</code></pre>
</div>
</div>
<p>Then use the <code>pnorm()</code> function to estimate the area:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(u) <span class="sc">-</span> <span class="fu">pnorm</span>(l)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6984912</code></pre>
</div>
</div>
<p>which is about 70 %.</p>
<p>Let us check this approximation with the real data. We use logical subsetting to count the share of height values between <span class="math inline">\(l\)</span> and <span class="math inline">\(u\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> (data<span class="sc">$</span>Height <span class="sc">&gt;=</span> <span class="dv">168</span> <span class="sc">&amp;</span> data<span class="sc">$</span>Height <span class="sc">&lt;=</span> <span class="dv">178</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(idx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.69868</code></pre>
</div>
</div>
<p>You see that in this case the approximation works really well. So using the normal approximation we can get a fairly precise generalization from study population to the target population, even though the target population is larger than our study population. What we have done is that we have replaced the histogram of the empirical data by a normal curve before computing areas.</p>
<p>Not all histograms follow a normal curve. But it is a remarkable fact, which we will explore in more detail later in the course, that many histograms do. In this case the mean and the standard deviation are good summary statistics.</p>
</section>
<section id="percentiles" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="percentiles"><span class="header-section-number">4.7</span> Percentiles</h2>
<p>While the mean and the standard deviation are good statistics to summarize data which follow a normal distribution, they are not so suited to summarize other distributions.</p>
<p>Let us go back to one of these distributions we have encountered before: Primary energy consumption per capita in the world in the year 2019.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">with</span>(energy_consumption_per_capita, energy_consumption_per_capita[Year <span class="sc">==</span> <span class="dv">2019</span>, ])</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>hist_info <span class="ot">&lt;-</span> <span class="fu">hist</span>(dat<span class="sc">$</span>Cons, <span class="at">plot =</span> <span class="cn">FALSE</span>)         <span class="co"># Store output of hist function</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>hist_info<span class="sc">$</span>counts <span class="ot">&lt;-</span> hist_info<span class="sc">$</span>counts <span class="sc">/</span>    <span class="co"># Compute relative frequency values</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(hist_info<span class="sc">$</span>counts) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hist_info, <span class="at">freq =</span> <span class="cn">TRUE</span>, <span class="at">xlab =</span> <span class="st">"Primary energy consumption in kilowatt-hours per person per year."</span>, <span class="at">ylab =</span> <span class="st">"Percent"</span>, <span class="at">main =</span> <span class="st">"Primary energy Consuption per Capita 2019"</span>)              <span class="co"># Plot histogram with percentages</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="from_limited_data_to_populations_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The average primary energy consumption was 26883.02 kwh per person per year and a standard deviation of 33562.48 kwh per person per year.</p>
<p>If we would just blindly apply a normal approximation using these statistics we would conclude that 21.15 % of countries in the world had a negative primary energy consumption. This does not make sense.</p>
<p>The reason for this nonsensical result is that the distribution depicted by the histogram does not follow a normal distribution. To summarize such distributions, statisticians often use so called <strong>percentiles</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">quantile</span>(dat<span class="sc">$</span>Cons, <span class="fu">c</span>(<span class="fl">0.01</span>,<span class="fl">0.10</span>,<span class="fl">0.25</span>,<span class="fl">0.50</span>,<span class="fl">0.75</span>,<span class="fl">0.90</span>,<span class="fl">0.99</span>)),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1%       10%       25%       50%       75%       90%       99% 
   249.66   1147.96   3992.01  16516.14  33573.17  64784.08 165031.69 </code></pre>
</div>
</div>
<p>Let us first explain what you see in the code snippet. R has a built in functions to compute percentiles. This function is called <code>quantile()</code>and takes the data as the first argumente and then a vector of percentiles in decimal form. For example <code>quantile(dat$Cons, 0.01)</code> would compute the 1 % percentile.</p>
<p>What does this mean? The first percentile in our primary energy consumption distribution is 249.66. This means that in about 1 % of the countries of the world the primiary energy consumption per person per year is 250 kwh or less. 99 % of the countries had a primary energy consumption above that level. The 50 % percentile (0.5) is just the median. The interquartile range is the difference between the 75 % percentile (0.75) and the 25 % percentile (0.25). This is sometimes used as a measure of spread for distributions with long tails, such as in this example.</p>
<p>Sometimes data are distributed like a normal curve and sometimes they are not. We will later discuss a theoretical argument which helps to explain when precisely historgrams should be approximated well by a normal curve.</p>
<!-- ## How does the DHS sample its data -->
<!-- DHS is a nationally representative, population based cross sectional household survey. The survey is representative at the -->
<!-- national level, for urban and rural areas and for the first administrative subunit. -->
<!-- population based: data are collected through interviews of a representative sample of  -->
<!-- households. Interviewers visit selcetd households, collecting data from the household. -->
<!-- cross-sectional: A snapshot of an area at a particular point in time. -->
<!-- first government level below the national unit, such as region, state or zone -->
<!-- target population: women and men of reproductive age (15-49) of all backgrounds -->
<!-- 4 stages in the DHS survey process: -->
<!-- Stage 1 survey design and questionnaire six months -->
<!-- Stage 2 training interviewers and collecting data 6 month -->
<!-- Stage 3 data editing, tabulation and report writing 1 year -->
<!-- Stage 4 Dissemination and analysis 6-7 months -->
<!-- ## Contents -->
<!-- Inductive inference requires working from data to study sample and study population to target population. -->
<!-- At each stage bias can crop up. -->
<!-- The best way to proceed from sample to study population is if you have drawn a random sample. -->
<!-- Introduce the idea that a population can be thought of as a group of individuals but also as a probability distribution for a random observation drawn from that population -->
<!-- Populations can be summarized using parameters that mirror the summary statistics of sample data. -->
<!-- It often occurs that data do not arise as a sample from a literal population. We can always imagine data as drawn from a metaphorical population of events that could have occurred but didn’t. -->
<!-- ## Outcome -->
<!-- Make the concept of a random sample and a probability distribution tangible by using the computer. -->


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Spi2019" class="csl-entry" role="doc-biblioentry">
Spiegelhalter, David. 2019. <em>The Art of Statistcis: Learning from Data</em>. Pelican Books.
</div>
</div>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./summarizing_and_communicating_lots_of_data.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and communicating lots of data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./what_causes_what.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">What causes what?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>