<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics - 8&nbsp; How sure can we be about what is going on: Estimates and intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./probability.html" rel="next">
<link href="./modelling_relationships_using_regression_part_2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./how_sure_can_we_be.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on: Estimates and intervals</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><strong>Introduction</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical_data_and_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Data and Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summarizing_and_communicating_lots_of_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and communicating lots of data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from_limited_data_to_populations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_causes_what.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">What causes what?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling relationships: Points, Lines and Scatterplots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_sure_can_we_be.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on: Estimates and intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variabilility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_and_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answering_questions_and_claiming_discoveries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Answering questions and claiming discoveries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#quantifying-uncertainty-by-bootstraping-the-basic-idea." id="toc-quantifying-uncertainty-by-bootstraping-the-basic-idea." class="nav-link active" data-scroll-target="#quantifying-uncertainty-by-bootstraping-the-basic-idea."><span class="header-section-number">8.1</span> Quantifying uncertainty by bootstraping: The basic idea.</a></li>
  <li><a href="#doing-bootstraps-using-r" id="toc-doing-bootstraps-using-r" class="nav-link" data-scroll-target="#doing-bootstraps-using-r"><span class="header-section-number">8.2</span> Doing bootstraps using R</a>
  <ul class="collapse">
  <li><a href="#the-r-list-class" id="toc-the-r-list-class" class="nav-link" data-scroll-target="#the-r-list-class"><span class="header-section-number">8.2.1</span> The R list class</a></li>
  <li><a href="#iteration" id="toc-iteration" class="nav-link" data-scroll-target="#iteration"><span class="header-section-number">8.2.2</span> Iteration</a></li>
  </ul></li>
  <li><a href="#standard-error-of-a-proportion" id="toc-standard-error-of-a-proportion" class="nav-link" data-scroll-target="#standard-error-of-a-proportion"><span class="header-section-number">8.3</span> Standard error of a proportion</a></li>
  <li><a href="#regression-and-the-pearson-height-data" id="toc-regression-and-the-pearson-height-data" class="nav-link" data-scroll-target="#regression-and-the-pearson-height-data"><span class="header-section-number">8.4</span> Regression and the Pearson height data</a></li>
  <li><a href="#uncertainty-quantification-beyond-the-bootstrap" id="toc-uncertainty-quantification-beyond-the-bootstrap" class="nav-link" data-scroll-target="#uncertainty-quantification-beyond-the-bootstrap"><span class="header-section-number">8.5</span> Uncertainty quantification beyond the bootstrap</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">8.6</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">8.6.1</span> Exercises:</a></li>
  <li><a href="#exercises-r" id="toc-exercises-r" class="nav-link" data-scroll-target="#exercises-r"><span class="header-section-number">8.6.2</span> Exercises R</a></li>
  </ul></li>
  <li><a href="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" id="toc-project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="nav-link" data-scroll-target="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">8.7</span> Project People count: The present and future of humanity in pictures and numbers</a>
  <ul class="collapse">
  <li><a href="#how-precise-are-our-estimates-of-the-mean-age" id="toc-how-precise-are-our-estimates-of-the-mean-age" class="nav-link" data-scroll-target="#how-precise-are-our-estimates-of-the-mean-age"><span class="header-section-number">8.7.1</span> How precise are our estimates of the mean age ?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on: Estimates and intervals</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In statistics we often make estimates based on samples of data from a population as we discussed in unit 3 or we make predictions of future values of a variable using models as discussed in unit 4. But how precise are these estimates? Do they vary a lot or only a little? Estimates are not worth very much, if we are not able to quantify such uncertainty. In this unit we will learn a first technique based on computation to do so, the bootstrap.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Overview
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this unit you will learn how to quantify <strong>uncertainty intervals</strong> for your statistical estimates as well as for your predictions by using computational methods. Being able to do this is a very important part of communicating statistics.</p>
<p><strong>Bootstrapping</strong> is the technique we will learn in this unit. Bootstrapping a sample consists of creating new datasets of the same size by resampling the original data with replacement.</p>
<p>The distribution of some inportant <strong>sample statistics</strong> such as the mean or the median of a datset when computed using bootstrapping resamples are approximated by a normal curve for larger datasets, regardless of the shape of the original distribution.</p>
<p>Uncertainty intervals based on bootstrapping depend on modern computing power. They do not require assumptions about the mathematical description of the population distribution and do not require complex probability theory beyond the intuitive idea of <strong>random sampling with replacement</strong>.</p>
<p>Since the computational method of the bootstrap depends on repeated computations on random draws from a sample, you need to understand how to implement and use <strong>iteration</strong> as a computational technique. In this unit you will learn to work with <strong>for-loops</strong> in R and make use of them to quantify uncertainty. Since the objects of a resample can be complex you learn also about a new datastructure of R the R <strong>list-class</strong> which is very flexible in storing data or all types and shapes.</p>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Keywords
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Population</strong>: A population in statistics represents every possible individual element we would like to measure.</p>
<p><strong>Sample</strong>; A sample is a part or subset of the population.</p>
<p>Predictions with statistical models or estimates of statistics from samples have a <strong>margin of error</strong>, which we need to be able to quantify to assess the quality of a prediction or an estimate.</p>
<p><strong>Bootstrapping</strong> is a computational technique of creating from a given dataset new datasets of the same size by resampling at random the original data with replacement making the assumption that the sample is approximately distributed similarly as the population.</p>
<p><strong>Central Limit Theorem</strong>: When a statistics, such as for example the mean, is repeatedly computed from random resamples these computed values tend to be distributed symmetrically and approximated by a normal curve for large sample sizes. This holds irrespective of the shape of the initial distribution of the data.</p>
<p><strong>Lists</strong>: Lists are an important class of objects in R. They are able to contain elements of different types like − numbers, strings, vectors and another list inside it. List is created using the <code>list()</code> function.</p>
<p><strong>for-loops</strong>: For loops in R implement iterations of computations. They are an indispensable tool to iterate repeated computations. A for look consists of three key elements. The preallocated output, the specification of a sequence and the body of the for loop.</p>
</div>
</div>
<p>How many people will there be on the planet in 2100? Nobody knows, but we can make use of our experience from the past and our knowledge of demographic mechanisms to build models, which support us in making systematic predictions. You did work out such a prediction model in your last project work of “people-count” using a regression model.</p>
<p>In 2020 the World Health Organisation WHO published one of it’s global population forecast. The WHO needs high quality predictions of population numbers to plan their programs. They also use a prediction model but it is more sophisticated than the linear model we used in the last unit. The WHO model takes many factors into account. Here is a picture that illustrates their prediction:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>whopredplot <span class="ot">&lt;-</span> worldpop_pred <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">'WORLD'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> population<span class="sc">*</span><span class="fl">1e-06</span>)) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> population_lower95<span class="sc">*</span><span class="fl">1e-06</span>,<span class="at">ymax =</span> population_upper95<span class="sc">*</span><span class="fl">1e-06</span>),<span class="at">alpha =</span> .<span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"WHO predicted world population with 95% prediction interval"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"World population (Billions)"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>whopredplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="how_sure_can_we_be_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What you see in the picture are dots indicating the WHO prediction about how many people will be there on the planet in future years, starting from 2020, the year this prediction was produced. The points are shown for five year intervals on the horizontal axis and give the population count estimate on the vertical axis. So for instance for 2040 the prediction is a number slightly more than 9 billion. The precise number is 9.198847 billion.</p>
<p>But there is also a gray area surrounding the points. This area represents a <strong>margin of error</strong> that belongs to this prediction. There is an upper bound and a lower bound to this margin. The upper margin of error is 9.396987 billion and the lower margin of error is 8.996324. So there could be about 200 million people more or about 400 million people less. These are huge margins. This is a margin of error comprising almost 2-times the size of the population (roughly 333 Million as of 2022) of the United States of America. If you go further out into the future, say to the year 2080, this margin of error increases. Worse than that: While for 2080 the point estimate would still predict some sort of stabilization, the upper margin would indicate an increase, while the lower margin would indicate a decrease in the world population. So within the margin of error the predictions would even be qualitatively different.</p>
<p>Knowing the margin of error is important in order to get a more precise idea about the quality of the prediction. Anyone can make an estimate. But the real challenge is to make an realistic assessment of the possible error. This is a crucial element of statistics as a science and in this unit we are going to learn the basic skills needed for making such assessments now.</p>
<p>The importance of having a reasonable idea about the margin of error doe not only refer to predictions but to any other statistical estimate depending on limited information.</p>
<p>The data on population counts collected by the WHO will be mostly be based on surveys. Let us assume the surveys are all well designed and accurately executed. Assume that the people and institutions who have conducted the surveys have been very careful to avoid biases. Then the summary statistics calculated from the sample, such as the mean or median age of the people counted or any other statistics calculated from the sample, should be close to the value of the statistics in the study population.</p>
<p>In a well designed study we expect the sample statistics, like the mean the median the standard deviation and the interquartile range to be close to the mean, median, standard deviation and interquartile range of the study population.</p>
<p>In the communication of data often only the summary statistics is reported and sometimes this may be enough. But knowing the uncertainty attached to the estimate will be important. It can even qualitatively change the information, as in our example, where the WHO forecast for the global population in 2080 could mean an increase as well as a decrease of the numbers. Knowing the exact differences between the sample and the population, or knowing the uncertainty in a prediction may be necessary for proper statistical inference.</p>
<p>Let us return to a dataset we have studied before, when we discussed how we get from information about a sample to information on the study population. Let us take our data <code>socr_height_weight</code> about height and weight of 25000 18 year old people we had discussed in unit 3. We retrieve the data from the <code>JWL</code> package and change the units of height from inches to cm and of weight from pounds to kg. Then we store the data in an R object which we call <code>dat</code> for simplicity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> socr_height_weight</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Height <span class="ot">&lt;-</span> data<span class="sc">$</span>Height<span class="sc">*</span><span class="fl">2.54</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Weight <span class="ot">&lt;-</span> data<span class="sc">$</span>Weight<span class="sc">*</span><span class="fl">0.4535924</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To illustrate how the accuracy of statistics depends on sample size, let us take the data on human height and assume the 25000 data we have are the population and use our function <code>emp_distr_height()</code> to draw random samples from this population. In unit three we had drawn samples of 10, 100 and 2500.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>emp_distr_height <span class="ot">&lt;-</span> <span class="cf">function</span>(n){</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  data[<span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data), <span class="at">size =</span> n, <span class="at">replace =</span> T), ]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The distributions of these various samples are shown in the following figure.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>h10 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">10</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(h10<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of human height N = 10"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>h100 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">100</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(h100<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of human height N = 100"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>h2500 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">2500</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(h2500<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of human height N = 2500"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of human height Population"</span>,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="how_sure_can_we_be_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As the sample size gets smaller the sample gets more and more “bumpy” because the histogram becomes sensitive to individual data points. Only as the sample gets larger we come closer to the actual population distribution. This is also intuitively clear. If somebody would tell you he had measured 10 adults from Kenya and concludes that their average height is some number, this is less credible than in a case where the statement was based on a much larger number of observations.</p>
<p>Let’s go back to our problem at hand. What can we say about the mean height in our ficticious population based on our different samples?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">2500</span>, <span class="dv">25000</span>), </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Mean_Height =</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">round</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">c</span>(<span class="fu">mean</span>(h10<span class="sc">$</span>Height), </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">mean</span>(h100<span class="sc">$</span>Height), </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">mean</span>(h2500<span class="sc">$</span>Height), </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">mean</span>(data<span class="sc">$</span>Height)), <span class="dv">2</span> ))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(samp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Size</th>
<th style="text-align: right;">Mean_Height</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">171.94</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">172.55</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2500</td>
<td style="text-align: right;">172.69</td>
</tr>
<tr class="even">
<td style="text-align: right;">25000</td>
<td style="text-align: right;">172.70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>You can see from the table that with substantive larger sample sizes our estimation of the mean becomes more and more precise.</p>
<section id="quantifying-uncertainty-by-bootstraping-the-basic-idea." class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="quantifying-uncertainty-by-bootstraping-the-basic-idea."><span class="header-section-number">8.1</span> Quantifying uncertainty by bootstraping: The basic idea.</h2>
<p>In order to quantify the accuracy of our statistics we now have to work out a thought experiment. If we assume that we repeatedly drew samples of 25000 individuals of 18 years an each time measured their mean height, by how much would the statistics - the mean height - vary?</p>
<p>If we knew how this statistics would vary, then we could say something about the accuracy of the statistics. But the precise variablity of the estimates depends on knowledge of the population. But this knowledge is exactly the knowledge we do not have.</p>
<p>There are in principle two ways out of this circular reasoning. We could bring in probability and mathematics to make assumptions about the population distribution and work out the variability we would expect under these assumptions and thus how far away our statistics in our sample is from the value we would theoretically expect. This is an approach you learn in every statistics course and we will learn it too later in this course.</p>
<p>Here we take a second approach based on computation. We start from the plausible assumption that the population and the sample should roughly look the same. Since we can not draw repeated samples from the unknown population , we instead draw repeated samples from our sample.</p>
<p>Let us illustrate this idea with our height data. Let us take the sample of 100 and draw take three bootstrap resamples from this sample.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(h100<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Original sample N = 100"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> h100</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">100</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(b1<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap 1: N = 100"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">100</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(b2<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap 2: N = 100"</span>,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>b3 <span class="ot">&lt;-</span> <span class="fu">emp_distr_height</span>(<span class="dv">100</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(b3<span class="sc">$</span>Height, <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap 3: N = 100"</span>,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Height in cm"</span>,</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="how_sure_can_we_be_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>At the top left corner of this figure you see our original sample of 100 height data from our original population of 25.000, which has a mean of 172, 2100 data points in sequence, each time replacing the point we have taken, and get the second distribution in the top right corner in this way. This distribution has a mean of 173.13. The distribution can only contain data points taking on the same values as in the original sample, but it will contain different number of each value. Therefore the shape of the distribution will vary slightly and give a slightly different mean. In our case these means are 171.68, 173.13, 171.95.</p>
<p>Thus the resampling procedure gives us an idea how our statistics varies through this procedure of resampling with replacement. Why do we need replacement? We want to make sure that at every resample, every data point has the same chance of ending up in the resample. This would not be the case if we drew observations away once the have ended up in one sample. This is known as <strong>bootstraping</strong> the data. There is something “magic” about this approach, reflected in the name: As if pulling oneself up by one’s own bootstraps, here we learn about the variability of an estimate without making assumptions about the shape of the population distribution. We think of the sample as beeing a representation of the underlying population. If we draw random resamples we always need to draw from the same sample of the population so that every individual in the sample has the same chance of ending up in the resample.</p>
<p>Repeating the resampling many times, say 1000 times, we get 1000 possible estimates of the mean. Let us do this repeated resampling for the examples of sample sizes of 10, 100, 2500 and in the end 25000, the size of our fictitious population.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap: sample with replacement</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45356</span>) <span class="co"># So you can reproduce my results</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> socr_height_weight</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Height <span class="ot">&lt;-</span> data<span class="sc">$</span>Height<span class="sc">*</span><span class="fl">2.54</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Weight <span class="ot">&lt;-</span> data<span class="sc">$</span>Weight<span class="sc">*</span><span class="fl">0.4535924</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="co"># Number of bootstrap resamples to take</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">100</span>,<span class="dv">2500</span>, <span class="dv">25000</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="fu">length</span>(n))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="fu">seq_along</span>(n)){</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>bootstrapmeans <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="at">length =</span> B)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Draw a bootstrap sample</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  bootstrapsample <span class="ot">&lt;-</span> <span class="fu">sample</span>(data<span class="sc">$</span>Height,n[j],<span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute the bootstrap estimate</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  bootstrapmeans[b] <span class="ot">&lt;-</span> <span class="fu">mean</span>(bootstrapsample)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>out[[j]] <span class="ot">&lt;-</span> bootstrapmeans</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(out[[<span class="dv">1</span>]], <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">168</span>,<span class="dv">178</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">400</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"1000 resamples from N = 10"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Mean height in cm"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(out[[<span class="dv">2</span>]], <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">168</span>,<span class="dv">178</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">400</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"1000 resamples from  N = 100"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Mean height in cm"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(out[[<span class="dv">3</span>]], <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">168</span>,<span class="dv">178</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">400</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"1000 resamples from N = 2500"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Mean height in cm"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(out[[<span class="dv">4</span>]], <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">168</span>,<span class="dv">178</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">400</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"1000 resamples from N = 25000"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Mean height in cm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="how_sure_can_we_be_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that the distribution of the estimates of the mean based on the resampled data is symmetric around the mean. The deeper mathematical reason for this fact is the so called <strong>Central Limit Theorem</strong>, which says that the distribution of sample means tends towards a normal distribution with increasing sample size almost regardless of the shape of the original distribution of the data. We will discuss this result in further detail later in the course.</p>
<p>The bootstrap distributions allow us to quantify the uncertainty connected to the estimate of the mean based on the sampled data. For example, we can find the range of means that contain 95 % of all the means of the bootstrap resample and call this the 95 % uncertainty interval for the original estimates, or the margins of error.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mean_height <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">mean</span>(out[[<span class="dv">1</span>]]), <span class="fu">mean</span>(out[[<span class="dv">2</span>]]), <span class="fu">mean</span>(out[[<span class="dv">3</span>]]), <span class="fu">mean</span>(out[[<span class="dv">4</span>]])),<span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lower_margin <span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">c</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">1</span>]], <span class="at">probs=</span>.<span class="dv">025</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">2</span>]], <span class="at">probs=</span>.<span class="dv">025</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">3</span>]], <span class="at">probs=</span>.<span class="dv">025</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">4</span>]], <span class="at">probs=</span>.<span class="dv">025</span>)),<span class="dv">2</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>upper_margin <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">c</span>(</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">1</span>]], <span class="at">probs=</span>.<span class="dv">975</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">2</span>]], <span class="at">probs=</span>.<span class="dv">975</span>),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">3</span>]], <span class="at">probs=</span>.<span class="dv">975</span>),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(out[[<span class="dv">4</span>]], <span class="at">probs=</span>.<span class="dv">975</span>)), <span class="dv">2</span> </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mean_height, lower_margin, upper_margin)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">mean_height</th>
<th style="text-align: right;">lower_margin</th>
<th style="text-align: right;">upper_margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">172.65</td>
<td style="text-align: right;">169.55</td>
<td style="text-align: right;">175.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">172.71</td>
<td style="text-align: right;">171.79</td>
<td style="text-align: right;">173.58</td>
</tr>
<tr class="odd">
<td style="text-align: right;">172.70</td>
<td style="text-align: right;">172.52</td>
<td style="text-align: right;">172.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">172.70</td>
<td style="text-align: right;">172.64</td>
<td style="text-align: right;">172.76</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Also observe that the bootstrap distributions get narrower as the sample size increases. This means that uncertainty shrinks and the estimate becomes more precise.</p>
<p>One of the appeals of the bootstrap approach to quantify uncertainty is that we were able to do this without any mathematics but the idea of drawing observations at random. All we need is an estimate and a sampling distribution. Thus the quantification of uncertainty is almost entirely based on computation.</p>
<p>We did, so far, not show you the details of how the computations are done. We will introduce these concepts now. They will enlarge the frontier of your R knowledge by the concept of R’s list class as well as the concept of computational iteration.</p>
</section>
<section id="doing-bootstraps-using-r" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="doing-bootstraps-using-r"><span class="header-section-number">8.2</span> Doing bootstraps using R</h2>
<p>It is now time to learn some more R, in order to do the computations needed for a bootstrap. One convenient data structure in this context is R’s list class. The other very useful concept, which you will very often need in computation and coding is the concept of iteration. Let us begin with the R-list class.</p>
<section id="the-r-list-class" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="the-r-list-class"><span class="header-section-number">8.2.1</span> The R list class</h3>
<p>Let us for a moment go back to the children nutrition data from the DHS survey we discussed in unit 2 and load this dataset again and store them in a variable with a simpler name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dhs_data <span class="ot">&lt;-</span> children_nutrition_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In unit 2 we discussed one approach how we could compute the number of cases of stunting across the four regions in the dataset. In the exercises we discussed how to do the same computation more efficiently using the <code>tapply()</code> function.</p>
<p>Let us introduce here a related function, called <code>split()</code>. There are usually several ways in R how we can filter data. In unit 2 we used the <code>which()</code> function to compute indices for the appropriate rows we wanted to select from our dataframe. Another way could be, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> dhs_data[dhs_data<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"region 1"</span>, <span class="fu">c</span>(<span class="st">"wt"</span>, <span class="st">"nt_ch_stunt"</span>)]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(r1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          wt nt_ch_stunt
323 0.262466        TRUE
425 0.262466       FALSE
495 0.262466       FALSE
498 0.262466       FALSE
826 1.846709       FALSE
827 1.846709       FALSE</code></pre>
</div>
</div>
<p>We can do this region by region and compute the shares also for regions 2, 3 and 4.</p>
<p>Here is a faster and cleaner way to achieve the same thing using <code>split()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>regions <span class="ot">&lt;-</span> <span class="fu">split</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  dhs_data[ ,<span class="fu">c</span>(<span class="st">"wt"</span>, <span class="st">"nt_ch_stunt"</span>, <span class="st">"region"</span>)], dhs_data<span class="sc">$</span>region</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(regions, head)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`region 1`
          wt nt_ch_stunt   region
323 0.262466        TRUE region 1
425 0.262466       FALSE region 1
495 0.262466       FALSE region 1
498 0.262466       FALSE region 1
826 1.846709       FALSE region 1
827 1.846709       FALSE region 1

$`region 2`
          wt nt_ch_stunt   region
16  1.049502       FALSE region 2
27  1.049502        TRUE region 2
36  1.049502        TRUE region 2
94  1.049502       FALSE region 2
106 1.049502       FALSE region 2
113 1.049502        TRUE region 2

$`region 3`
           wt nt_ch_stunt   region
1025 0.457125        TRUE region 3
1026 0.457125       FALSE region 3
1039 0.457125        TRUE region 3
1102 0.457125       FALSE region 3
1103 0.457125        TRUE region 3
1124 0.457125       FALSE region 3

$`region 4`
          wt nt_ch_stunt   region
149 0.925559       FALSE region 4
158 0.925559       FALSE region 4
159 0.925559       FALSE region 4
171 0.925559        TRUE region 4
172 0.925559       FALSE region 4
187 0.925559        TRUE region 4</code></pre>
</div>
</div>
<p>Let’s unpack this piece of code: You already know the syntax <code>dhs_data[ ,c("wt", "nt_ch_stunt", "region")]</code>. This says that R should choose from the dataframe <code>dhs_data</code> all rows and the columns with the names “wt”, “nt_ch_stunt” and “region”. We could also have selected the columns by indices.</p>
<p>Now this (reduced) dataframe is given as one argument to the function <code>split()</code>. The second argument is the column <code>dhs_data$region</code>. This tells the split function the criterion how to split up the dataframe in data chunks by region, i.e.&nbsp;region 1, 2 etc.</p>
<p>The new split data are in an object called <code>regions</code> and this object has a new class</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(regions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "list"</code></pre>
</div>
</div>
<p>This class is called in R a list. In this example the list <code>regions</code> contains four dataframes, which we can individually access using the $-sign. We use the <code>head()</code>function to avoid showing the entire dataframe. We applied the <code>heads()</code> function to all elements of the list by using the function <code>lapply()</code> short for list apply. This is a powerful functions allowing computations on elements of a list. Our list contains dataframes as elements. The syntax of <code>lapply()</code>takes as input some function - what do you want to do with the list elements? - and a list - the list containing the elements to which the function is applied. So in this case R applies the heads function to every entry in te list. So when we</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(regions<span class="sc">$</span><span class="st">"region 1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          wt nt_ch_stunt   region
323 0.262466        TRUE region 1
425 0.262466       FALSE region 1
495 0.262466       FALSE region 1
498 0.262466       FALSE region 1
826 1.846709       FALSE region 1
827 1.846709       FALSE region 1</code></pre>
</div>
</div>
<p>Or we could alternatively use indices. But now for the <code>list</code> class we will need double brackets, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(regions[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          wt nt_ch_stunt   region
323 0.262466        TRUE region 1
425 0.262466       FALSE region 1
495 0.262466       FALSE region 1
498 0.262466       FALSE region 1
826 1.846709       FALSE region 1
827 1.846709       FALSE region 1</code></pre>
</div>
</div>
<p>This retrieves the first dataframe from the list of dataframes.</p>
<p>Lists are particularly useful to store R objects of different types or classes. For example, one list entry can be a dataframe, another one can consist of characters, another of numbers and so on. The R -function <code>list()</code> creates a list the same way <code>c</code> creates a vector. Separate each element in the list with a comma: Here is a toy exmple:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">a =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>), <span class="at">b =</span> <span class="st">'sky'</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$a
[1] 2 5

$b
[1] "sky"</code></pre>
</div>
</div>
<p>As we see in the toy example, we can give names to list elements. When we use <code>split()</code> the names will be taken from the columns according to which the data are split. If we don’t like these default names we can override them by using the <code>names()</code>function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(regions) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"County A"</span>, <span class="st">"County B"</span>, <span class="st">"County C"</span>, <span class="st">"County D"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(regions, head)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`County A`
          wt nt_ch_stunt   region
323 0.262466        TRUE region 1
425 0.262466       FALSE region 1
495 0.262466       FALSE region 1
498 0.262466       FALSE region 1
826 1.846709       FALSE region 1
827 1.846709       FALSE region 1

$`County B`
          wt nt_ch_stunt   region
16  1.049502       FALSE region 2
27  1.049502        TRUE region 2
36  1.049502        TRUE region 2
94  1.049502       FALSE region 2
106 1.049502       FALSE region 2
113 1.049502        TRUE region 2

$`County C`
           wt nt_ch_stunt   region
1025 0.457125        TRUE region 3
1026 0.457125       FALSE region 3
1039 0.457125        TRUE region 3
1102 0.457125       FALSE region 3
1103 0.457125        TRUE region 3
1124 0.457125       FALSE region 3

$`County D`
          wt nt_ch_stunt   region
149 0.925559       FALSE region 4
158 0.925559       FALSE region 4
159 0.925559       FALSE region 4
171 0.925559        TRUE region 4
172 0.925559       FALSE region 4
187 0.925559        TRUE region 4</code></pre>
</div>
</div>
<p>What if we wanted the third row of the dataframe of region 1?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(regions[[<span class="dv">1</span>]][<span class="dv">3</span>, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          wt nt_ch_stunt   region
495 0.262466       FALSE region 1</code></pre>
</div>
</div>
<p>Some of you may have noticed that the $ signs are both used to refer to columns in a dataframe as well as to elements of a list. This is no coindcidence, because in R dataframes are lists. Each column is one element of the list.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dhs_data[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.049502 1.049502 1.049502 1.049502 1.049502 1.049502</code></pre>
</div>
</div>
</section>
<section id="iteration" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="iteration"><span class="header-section-number">8.2.2</span> Iteration</h3>
<p>In the project “people count” you are working on in this course, we are often looking at countries comparatively. We looked for instance at Kenya, the United States and Japan and sometimes also at another country of your choice.</p>
<p>In coding it is an important principle to reduce duplication of code as much as possible. This has three main benefits it focuses on the essential parts of a code, it is easier and shorter to make changes and it also helps reducing bugs in your code.</p>
<p>One tool to reduce duplication of code you have already encountered. Here, you learn a second tool: Iteration. When you have to do tasks 1000 and more times, like in resampling from the same distribution, such tools are even necessary. These are tasks simply impossible to do by hand or by copy and paste.</p>
<section id="for-loops" class="level4" data-number="8.2.2.1">
<h4 data-number="8.2.2.1" class="anchored" data-anchor-id="for-loops"><span class="header-section-number">8.2.2.1</span> For Loops</h4>
<p>Imagine we have a simple dataframe, where we have four columns, each containing 10 random numbers from a normal distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">b =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">c =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">d =</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, assume we want to compute the mean of every column. In this little toy example, you could do this by hand and by copy and paste, if you chose and solve the task as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.008060505</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1712027</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.8099074</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1977989</code></pre>
</div>
</div>
<p>A better way to solve such tasks is to use iteration and implement a <strong>for-loop</strong>. This looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">ncol</span>(df))  <span class="co"># 1. output</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(df)) {            <span class="co"># 2. sequence</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  output[[i]] <span class="ot">&lt;-</span> <span class="fu">mean</span>(df[[i]])        <span class="co"># 3. body</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>output</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.008060505  0.171202713 -0.809907400  0.197798895</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The three components of a for loop
</div>
</div>
<div class="callout-body-container callout-body">
<p>Every for-loop has three components:</p>
<ol type="1">
<li>The <strong>output</strong>: <code>output &lt;- vector("double", ncol(df))</code>. Before you start a loop you need to allocate space for the results computed during the loop. This is essential for efficiency. Always preallocate space for the output This can in general best be done using the <code>vector()</code> function of R. It has two arguments, the class of the vector, numeric, logical, character etc. and the length of the vector.</li>
<li>The <strong>sequence</strong>: <code>i in seq_along(df)</code>. This describes what you are looping over. Each iteration of the for loop will assign <code>i</code> to a different value from <code>seq_along(df)</code>.</li>
<li>The <strong>body</strong>: <code>output[[i]] &lt;- mean(df[[i]])</code>. This is the code that does the actual work in the for loop. It i run repeatedly with each <code>i</code>. When <code>i</code>is 1 the computation will be <code>output[[1]] &lt;- mean(df[[1]])</code>, when it is 2, we will have <code>output[[2]] &lt;- mean(df[[2]])</code> etc.</li>
</ol>
</div>
</div>
<p>Let us apply this technique to a problem you had worked on before in your project work “people count”. There you were asked to find a way to compute the mean age of a country for a situation where you do not have individual data but data grouped by age groups. The main idae there was to take the mid point of the age group as an approximation for the age and multiply with the population sized in the age group. Then sum over all age groups and divide by the total population size. Now if you do this for many countries this is a typical situation where you want both functions and iteration. Let us take this case as an example to show how interation works in R.</p>
<p>First we load the data using the <code>JWL</code> library and assign them to an object with a simpler name to make our life easier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> population_statistics_by_age_and_sex</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now assume we want to compute the mean age of Kenya, the US, Japan and Austria, which happens to be my country. Instead of computing this case by case by recycling an multiplying code, we do this using iteration.</p>
<p>Let’s first write a function, which computes the mean for our grouped data. The function should take the entire demographic dataframe as an input and the country and year we choose as an argument. It can then be applied to any country and any year by just specifying the correct argument and providing the dataframe once.</p>
<p>Let’s start with the function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="cf">function</span>(country, year, data){</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select the data for a given dataframe for a given country and a given year</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  pop_dat <span class="ot">&lt;-</span> data[data<span class="sc">$</span>Country <span class="sc">==</span> country <span class="sc">&amp;</span> data<span class="sc">$</span>Year <span class="sc">==</span> year, ]</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># compute the mean age per age group by assuming that the age in a group </span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#is approximated by</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the mid point. For example, if the age group is 0-4 we assume the mean </span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># age is 2, if it is </span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5 - 9 it is 7 etc. We do this by creating an appropriate sequence.</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  mid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">2</span>, <span class="at">to =</span> <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">5</span>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#compute the mid age. Note that we use the R recycling rules. Mid has only </span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#half the length of </span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># pop_dat$POP, because pop_dat$POP contains first all rows for females and </span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#then for males. Once</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># mid is exhausted at age group 95-99 for females it just begins from new for </span></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>  <span class="co">#men. By this we can</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make the total sum without explicitly defining objects for each sex separately.</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute the mean age rounded to two digits.</span></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="fu">sum</span>(pop_dat<span class="sc">$</span>POP<span class="sc">*</span>mid)<span class="sc">/</span><span class="fu">sum</span>(pop_dat<span class="sc">$</span>POP), <span class="dv">2</span>)</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we start with the iteration:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the list of countries we are interested in first:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>list_of_countries <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Kenya"</span>, <span class="st">"United States of America"</span>, <span class="st">"Japan"</span>, <span class="st">"Austria"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Preallocate space for four countries: The mean is usually some decimal </span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># number, so the output of our iteration will be of type double. we will compute </span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># one mean age per country, so the length of the output pre-allocation needs to </span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co"># match the length of our country list.</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">length</span>(list_of_countries))  <span class="co"># 1. output</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="fu">seq_along</span>(list_of_countries)){               <span class="co"># 2: sequence</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>   <span class="co"># 3. Body: Note the countries change over the iteration. Data and year stay </span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>   <span class="co">#          the same.</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  output[[i]] <span class="ot">&lt;-</span> <span class="fu">mean_age</span>(list_of_countries[i], <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">data =</span> dat) </span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now, let’s check:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>output</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.24 39.52 47.28 43.43</code></pre>
</div>
</div>
<p>Let me explain how this works. In the first step R reserves a vector for the entry of four doubles. Then the sequence is specified: It says that it starts at entry 1 in the <code>object list_of_numbers</code>. This is in our example <code>list_of_numers[1]</code>, which must be Kenya. Then it calls the function with this country specified as the country argument and the arguments for <code>year</code> and <code>data</code> set to our default values <code>2022</code> and <code>dat</code>. This output is written into the first entry of <code>output</code> and then the next iteration starts until the end of the country list, overwriting one component after the other with outputs from the computation.</p>
<p>There are lots of variations of iteration scenarios. We won’t go beyond this most basic case here</p>
</section>
</section>
</section>
<section id="standard-error-of-a-proportion" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="standard-error-of-a-proportion"><span class="header-section-number">8.3</span> Standard error of a proportion</h2>
<p>In unit 1 we computed proportions of stunted children in four of different regions and got these proportions as a mean to a series of <code>TRUE</code> or <code>FALSE</code> answers to an anthropometric measurements and a comparison with thresholds in a WHO incidence table. Let’s retrieve these data once more:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>dhs_data <span class="ot">&lt;-</span> children_nutrition_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s compute the proportions of stunted children per region using the <code>tapply</code>function and taking account that each observation is weighted by the <code>wt</code>, the weight, variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the weighted variable and attach to dataframe as an addiional column</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>dhs_data<span class="sc">$</span>weighted_nt_ch_stunt  <span class="ot">&lt;-</span> dhs_data<span class="sc">$</span>nt_ch_stunt<span class="sc">*</span>dhs_data<span class="sc">$</span>wt</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute total number of stunted children per region</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>stunted <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dhs_data<span class="sc">$</span>weighted_nt_ch_stunt, dhs_data<span class="sc">$</span>region, sum)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the total number of children per region</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dhs_data<span class="sc">$</span>wt, dhs_data<span class="sc">$</span>region, sum)</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the proportions rounded to two digits</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>prop <span class="ot">&lt;-</span> <span class="fu">round</span>(stunted<span class="sc">/</span>total,<span class="dv">2</span>)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>prop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>region 1 region 2 region 3 region 4 
    0.34     0.41     0.30     0.39 </code></pre>
</div>
</div>
<p>Now we want to use the bootstrap to get an idea of how precise the estimates of these proportions are. According to the basic idea of the bootstrap we repeatedly resample from the empirical distribution. The estimated standard error of this means is then the standard deviations of these means, which are in our case the proportions per region.</p>
<p>We write the bootstrap function first. Within the function we built in a for loop to do the repeated resampling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>bootstrap <span class="ot">&lt;-</span> <span class="cf">function</span>(B, data){</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  boot <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, B)                                  <span class="co"># output allocation</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (b <span class="cf">in</span> <span class="fu">seq_along</span>(<span class="dv">1</span><span class="sc">:</span>B)){                                          <span class="co"># sequence</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    aux <span class="ot">&lt;-</span> data[<span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data), <span class="at">size =</span> <span class="fu">nrow</span>(data), <span class="at">replace =</span> T), ]</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    aux<span class="sc">$</span>weighted_nt_ch_stunt  <span class="ot">&lt;-</span> aux<span class="sc">$</span>nt_ch_stunt<span class="sc">*</span>aux<span class="sc">$</span>wt</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    stunted <span class="ot">&lt;-</span> <span class="fu">tapply</span>(aux<span class="sc">$</span>weighted_nt_ch_stunt, aux<span class="sc">$</span>region, sum)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>    total <span class="ot">&lt;-</span> <span class="fu">tapply</span>(aux<span class="sc">$</span>wt, aux<span class="sc">$</span>region, sum)</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    boot[[b]] <span class="ot">&lt;-</span> (stunted<span class="sc">/</span>total)                                          <span class="co"># body</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a> res <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, boot)</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a> <span class="fu">as.data.frame</span>(res)</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before we look at the numerical results, let us unpack this code. Here we have put the iteration inside the function. The function arguments are the data and the number of bootstrap resamplings, which we call here <span class="math inline">\(B\)</span>.</p>
<p>The function does <span class="math inline">\(B\)</span> random samples from the data. We use a list as an output vector, because at every iteration we will get a named vector of results, with four means for every region.</p>
<p>Now we define the sequence. We do <span class="math inline">\(B\)</span> bootstrap samples in total. You see that the running index can have any legitimate symbol. Before we called it <span class="math inline">\(i\)</span> and here we call it <span class="math inline">\(b\)</span>.</p>
<p>Then we sample rows from our dataframe at random with replacement. This is exactly similar to our discussion in unit 3 where we took random samples from the dataframe of human heights. We save this in an r-object which we chose to call <code>aux</code>here (for auxiliary). Then we do the same computation of the mean we did before and store the result in list element <span class="math inline">\(b\)</span>.</p>
<p>In the end we have boot filled with <span class="math inline">\(B\)</span> vectors with components showing the means of region 1 to 4.</p>
<p>In the end we use an R-function to transform the list back into a dataframe. This function is called <code>do.call()</code> and works as follows: The first argument is a function. It specifies what <code>do.call()</code>does to every element in the list. The function we chose is called <code>rbind()</code> (for row bind) it binds together rows in a dataframe. The result is stored in an R object called res and res is then the output. With <code>as.data.frame()</code>we tell R to give this result the class of a dataframe. Thus our output is a dataframe with 1000 rows and 4 columns, each column specifiying a region.</p>
<p>Now we can pin down the bootstrapped mean and standard deviation. Let’s give it a try. We first take 1000 bootstrap resamples from our data and compute the weighted means or proportions for all four regions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>boot <span class="ot">&lt;-</span> <span class="fu">bootstrap</span>(<span class="dv">1000</span>, dhs_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we have a dataframe with 4 columns and we want to compute the mean and sd for every column. Here we can practice iteration once more:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>all_means <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="dv">4</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>all_sds <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="dv">4</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(boot)){</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  all_means[[i]] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(boot[,i]),<span class="dv">2</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  all_sds[[i]] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">sd</span>(boot[ ,i]),<span class="dv">2</span>)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Regions =</span> <span class="fu">c</span>(<span class="st">"Region 1"</span>, <span class="st">"Region 2"</span>, <span class="st">"Regions 3"</span>, <span class="st">"Regions 4"</span>), </span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Means =</span> all_means, <span class="at">SDs =</span> all_sds)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  out</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Regions</th>
<th style="text-align: right;">Means</th>
<th style="text-align: right;">SDs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Region 1</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Region 2</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regions 3</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Regions 4</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This should look very familiar to you by now. We allocate the space for the output for the means and the standard deviations. Then in the for-loop we compute the mean for every row and the standard deviation for every row. Finally we write everything into a dataframe. The final line uses the <code>kable()</code> function from the <code>knitr</code> package. This allows a particular layout for the dataframe. It gives you by the way an alternative way to call functions from a package without running the <code>library()</code> function first. When the package is installed functions from the package can be called by the syntax <code>package_name::function_name</code>.</p>
<p>Let’s look at the numbers first. We observe a few things. First, observe that the standard deviation is largest for region 3, where the mean can vary by four percentage points as compared to 2 percentage points in all the other regions. While the proportion seems highest in region 2, within the precision of the estimate it will be difficult to distinguish it from region 4.</p>
<p>Let us look at the histogram of the bootstrap-distribution of the means:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>hist_data1 <span class="ot">&lt;-</span> <span class="fu">hist</span>(boot[ ,<span class="dv">1</span>], <span class="at">main =</span> <span class="st">"Bootstrap 1"</span>, <span class="at">xlab =</span> <span class="st">"proportion of stunted children in region 1"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co">#define x and y values to use for normal curve</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(boot[ ,<span class="dv">1</span>]), <span class="fu">max</span>(boot[ ,<span class="dv">1</span>]), <span class="at">length =</span> <span class="fu">length</span>(boot[ ,<span class="dv">1</span>]))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x_values, <span class="at">mean =</span> <span class="fu">mean</span>(boot[ ,<span class="dv">1</span>]), <span class="at">sd =</span> <span class="fu">sd</span>(boot[ ,<span class="dv">1</span>])) </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> y_values <span class="sc">*</span> <span class="fu">diff</span>(hist_data1<span class="sc">$</span>mids[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">*</span> <span class="fu">length</span>(boot[ ,<span class="dv">1</span>]) </span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co">#overlay normal curve on histogram</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_values, y_values, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>hist_data2 <span class="ot">&lt;-</span> <span class="fu">hist</span>(boot[ ,<span class="dv">2</span>], <span class="at">main =</span> <span class="st">"Bootstrap 2"</span>, <span class="at">xlab =</span> <span class="st">"proportion of stunted children in region 2"</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="co">#define x and y values to use for normal curve</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(boot[ ,<span class="dv">2</span>]), <span class="fu">max</span>(boot[ ,<span class="dv">2</span>]), <span class="at">length =</span> <span class="fu">length</span>(boot[ ,<span class="dv">2</span>]))</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x_values, <span class="at">mean =</span> <span class="fu">mean</span>(boot[ ,<span class="dv">2</span>]), <span class="at">sd =</span> <span class="fu">sd</span>(boot[ ,<span class="dv">2</span>])) </span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> y_values <span class="sc">*</span> <span class="fu">diff</span>(hist_data2<span class="sc">$</span>mids[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">*</span> <span class="fu">length</span>(boot[ ,<span class="dv">2</span>]) </span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a><span class="co">#overlay normal curve on histogram</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_values, y_values, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>hist_data3 <span class="ot">&lt;-</span> <span class="fu">hist</span>(boot[ ,<span class="dv">3</span>], <span class="at">main =</span> <span class="st">"Bootstrap 3"</span>, <span class="at">xlab =</span> <span class="st">"proportion of stunted children in region 3"</span>)</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a><span class="co">#define x and y values to use for normal curve</span></span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(boot[ ,<span class="dv">3</span>]), <span class="fu">max</span>(boot[ ,<span class="dv">3</span>]), <span class="at">length =</span> <span class="fu">length</span>(boot[ ,<span class="dv">3</span>]))</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x_values, <span class="at">mean =</span> <span class="fu">mean</span>(boot[ ,<span class="dv">3</span>]), <span class="at">sd =</span> <span class="fu">sd</span>(boot[ ,<span class="dv">3</span>])) </span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> y_values <span class="sc">*</span> <span class="fu">diff</span>(hist_data3<span class="sc">$</span>mids[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">*</span> <span class="fu">length</span>(boot[ ,<span class="dv">3</span>]) </span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a><span class="co">#overlay normal curve on histogram</span></span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_values, y_values, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>hist_data4 <span class="ot">&lt;-</span> <span class="fu">hist</span>(boot[ ,<span class="dv">4</span>], <span class="at">main =</span> <span class="st">"Bootstrap 4"</span>, <span class="at">xlab =</span> <span class="st">"proportion of stunted children in region 4"</span>)</span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a><span class="co">#define x and y values to use for normal curve</span></span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(boot[ ,<span class="dv">4</span>]), <span class="fu">max</span>(boot[ ,<span class="dv">4</span>]), <span class="at">length =</span> <span class="fu">length</span>(boot[ ,<span class="dv">4</span>]))</span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x_values, <span class="at">mean =</span> <span class="fu">mean</span>(boot[ ,<span class="dv">4</span>]), <span class="at">sd =</span> <span class="fu">sd</span>(boot[ ,<span class="dv">4</span>])) </span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> y_values <span class="sc">*</span> <span class="fu">diff</span>(hist_data4<span class="sc">$</span>mids[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">*</span> <span class="fu">length</span>(boot[ ,<span class="dv">4</span>]) </span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a><span class="co">#overlay normal curve on histogram</span></span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_values, y_values, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="how_sure_can_we_be_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We have overlayed all four distributions with a normal curve. You see that the fit is pretty good. This is no accident, as we will learn the deeper reason for this in the coming units.</p>
</section>
<section id="regression-and-the-pearson-height-data" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="regression-and-the-pearson-height-data"><span class="header-section-number">8.4</span> Regression and the Pearson height data</h2>
<p>One of the appeals of the bootstrap is that it is very general. Any estimate can be bootstrapped. All we need is an estimate and a sampling distribution. The bootstrap can be performed algorithmically without the need of a formal probability model. We can apply this idea to any situation where we need to quantify uncertainty.</p>
<p>In unit 5 we fitted a regression line to the heights data of fathers and son collected by Pearson in 1903. Let us come back to this analysis now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> pearson</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Son <span class="sc">~</span> Father, <span class="at">data =</span> dat)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Son ~ Father, data = dat)

Coefficients:
(Intercept)       Father  
     33.893        0.514  </code></pre>
</div>
</div>
<p>Our estimated coefficient were <span class="math inline">\(33.89\)</span> for the intercept and <span class="math inline">\(0.514\)</span> for the slope. How confident can we be about the position of the regression line? We could answer this question by bootstrapping.</p>
<p>Let us take a bootstrap resample of the 1078 Father and Son pairs with replacement. From the data we fit a least squares line. Repeating this many times we can compute a 95% interval for the coefficient. Let’s use R to implement this idea.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="at">length =</span> B)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(<span class="dv">1</span><span class="sc">:</span>B)){</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  aux <span class="ot">&lt;-</span> dat[<span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(dat), <span class="at">size =</span> <span class="fu">nrow</span>(dat), <span class="at">replace =</span> T), ]</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Son <span class="sc">~</span> Father, <span class="at">data =</span> aux)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  output[[i]] <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, output)</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code should be no mystery for you by now. One point is worth mentioning though. When we call the <code>lm()</code> function to do a least suqare fit of the regression line, we store the output in an R object called mod. When R performs the computations implemented in <code>lm()</code> it does not only compute the coefficients of the regression line but a lot of more different things and stores them in a list. The value of the coefficients are stored in a list element with the name <code>coeffcients</code>. Thus we store the value of the coefficients by assigning <code>mod$coefficients</code> to the object where we store the results.</p>
<p>When we compute the mean and the standard deviation of the coefficient, we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(result<span class="sc">$</span>Father),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.51</code></pre>
</div>
</div>
<p>95 % of the values of the coefficient are between the 2.5 and the 97.5 percentile. This can be computed using the <code>quantile()</code> function:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">quantile</span>(result<span class="sc">$</span>Father, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>) ),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 97.5% 
 0.47  0.56 </code></pre>
</div>
</div>
<p>This gives you a sense of the range where the coefficient value of this can fall with high confidence.</p>
</section>
<section id="uncertainty-quantification-beyond-the-bootstrap" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="uncertainty-quantification-beyond-the-bootstrap"><span class="header-section-number">8.5</span> Uncertainty quantification beyond the bootstrap</h2>
<p>Bootstrapping provides an intuitive way of assessing uncertainty of estimates. The method is computer intensive and needs computing technology and capacity. Since these tools are becoming available more widely and at ever lower cost, this is an attractive approach when we need to judge the uncertainty we should attach to our estimates.</p>
<p>The bootstrap is a very powerful method but always keep the following things in mind:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Things to keep in mind about the bootstrap
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Try to start with a sufficiently large random sample. Note that the sample and hence the resample will only resemble the population distribution if the sample is large enough.</p></li>
<li><p>To approximate the distribution of a statistics, like a mean, a median etc. replicate the resampling procedure very often. To get a decent approximation a few thousand resamples will be good. As a rule of thumb you could use 5000 or 10000, dependning in the computational ressoruces available to you.</p></li>
<li><p>The bootstrap percentile method works well for estimating the population mean of median based on a large random sample. It is not expected to work very well when the minimum or maximum should be estimated or when we look for very low or very high percentiles or other parameters that are strongly influenced by extreme observations. It also does not work well when the distribution of the statistics is not symmetric or well approximated by a normal curve. It also does not work well when the sample is very small say lower than 10 or 15.</p></li>
</ol>
</div>
</div>
<p>Bootstrapping reaches its limit when very large quantities of data are involved. Here we have reached the limits of what we can learn about statistics without taking resort to the (mathematical) theory of probability.</p>
<p>In such cases, when we need to deal with very large quantities of data, bootstrapping is too clumsy. In these cases we need to resort to the elegant and effective mathematics of uncertainty which is based on the theory of probability, which we explore in the next unit. We will only introduce the basic ideas without using too much mathematics. These ideas will be necessary to understand how we can leverage probability theory to quantify uncertainty.</p>
</section>
<section id="exercises" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="exercises"><span class="header-section-number">8.6</span> Exercises</h2>
<section id="exercises-1" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">8.6.1</span> Exercises:</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1: Thirsty students
</div>
</div>
<div class="callout-body-container callout-body">
<p>Assume you are interested in the amount of water the student coming to the JWL study center consume in a day. In particular you want to learn about the proportion of students that drink more than 2 liters of water per day. You take a random sample of 100 students in the students directory of the study center and obtain from them the information about how much water they drink in a day at the study center. You store your results in a dataframe you call <code>water</code>. The dataframe has one column called <code>amount</code> which stores the number of liters each of the students drink.</p>
<ol type="1">
<li><p>Write one line of R-code to compute the proportion of students who drank more than 2 liters of water. Hint: You can write this line of code also when you are not at the computer. You can solve this exercise by thinking about what you would write, if you had an R console or a Jupyter book opened in front of you.</p></li>
<li><p>Write one line of R-code to compute a single bootstrap resample from the water dataframe.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2: Check your understanding of why the bootstrap works
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>When we conduct a bootstrap resample, what size resample should we draw from our sample? Why? Hint: There is no unique answer to the size question only rules of thumb. When you think about the why, go back to consult our discussion on why random sampling works in unit 2.</p></li>
<li><p>Why do we need to sample with replacement?</p></li>
<li><p>When we conduct a bootstrap resample, what is the underlying assumption/reasoning for resampling from our sample? Why does it work?</p></li>
</ol>
</div>
</div>
</section>
<section id="exercises-r" class="level3" data-number="8.6.2">
<h3 data-number="8.6.2" class="anchored" data-anchor-id="exercises-r"><span class="header-section-number">8.6.2</span> Exercises R</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1: A toy problem for practicing iteration
</div>
</div>
<div class="callout-body-container callout-body">
<p>Load the pearson height data from the <code>JWL</code>package and transform the data to standard units using a for loop. Hint: You will need a function and an interation over the columns of the dataframe.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2: Bootstrapped interquartile range of height data
</div>
</div>
<div class="callout-body-container callout-body">
<p>To practice the bootstrapping technique we learned in this unit, let us load the human height data <code>socr_height_weight</code> once again from the JWL package. Take a sample of 5000 of the height data and compute the interquartile range. Implement a bootstrap with 10000 resamples to quantify the uncertainty in the sample inter quartile range for the inter quartile range, i.e.&nbsp;the difference between the 25 and the 75 percentile of the height distribution. Compute the range in which 95 % of the inter-quartile-ranges lie. You can leave the data for this exercise in the original units of inches. Hint: For the interquartile range consult the passage on percentiles in unit 3. If you do 10000 bootstraps this might take a while in times of computation. As long as the <code>In [*]</code> cell has a star in the brackets and not a number, the computation is still going on. So you will need a bit of patience for computing this exercise.</p>
</div>
</div>
</section>
</section>
<section id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">8.7</span> Project People count: The present and future of humanity in pictures and numbers</h2>
<section id="how-precise-are-our-estimates-of-the-mean-age" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="how-precise-are-our-estimates-of-the-mean-age"><span class="header-section-number">8.7.1</span> How precise are our estimates of the mean age ?</h3>
<p>In our project in unit 2 we estimated the mean age of the population in Kenya, the United States and Japan as well as in your own country in the year 2022. In this project we will leverage our knowledge of the bootstrap to attach some uncertainty interval to our estimate. Let us use Kenya as an example in this part of the project for. You may also choose your own country if you are more interested in this particular case.</p>
<ol type="1">
<li><p>Filtering the data for Kenya (or any other country): This is a repetition of what we have done already previously. Take the data <code>population_statistics_by_age_and_sex</code> from the <code>JWL</code> package and store it in an R object. Check whether the data you get in this way is what you want.</p></li>
<li><p>Implement a bootstrap for the mean age in Kenya (or the country of your choice) using your previous results and the techniques you learned in this unit and report the bounds that contain 95 % of these estimates based on 5000 resamples from the appropriate distribution.</p></li>
<li><p>What kind of data would you need to get a more precise estimate? What do you think? Explain in a few sentences.</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./modelling_relationships_using_regression_part_2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./probability.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variabilility</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>