<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics - 7&nbsp; Modelling relationship: Prediction using regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./how_sure_can_we_be.html" rel="next">
<link href="./modelling_relationships_using_regression_part_1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./modelling_relationships_using_regression_part_2.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><strong>Introduction</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical_data_and_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Data and Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summarizing_and_communicating_lots_of_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and communicating lots of data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from_limited_data_to_populations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_causes_what.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">What causes what?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling relationships: Points, Lines and Scatterplots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_sure_can_we_be.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variablility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_and_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answering_questions_and_claiming_discoveries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Answering questions and claiming discoveries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#correlation" id="toc-correlation" class="nav-link active" data-scroll-target="#correlation"><span class="header-section-number">7.1</span> Correlation</a>
  <ul class="collapse">
  <li><a href="#the-correlation-coefficient" id="toc-the-correlation-coefficient" class="nav-link" data-scroll-target="#the-correlation-coefficient"><span class="header-section-number">7.1.1</span> The correlation coefficient</a></li>
  <li><a href="#computing-r" id="toc-computing-r" class="nav-link" data-scroll-target="#computing-r"><span class="header-section-number">7.1.2</span> Computing r</a></li>
  <li><a href="#properties-of-r" id="toc-properties-of-r" class="nav-link" data-scroll-target="#properties-of-r"><span class="header-section-number">7.1.3</span> Properties of r</a></li>
  <li><a href="#r-is-a-measure-of-clustering-along-a-line." id="toc-r-is-a-measure-of-clustering-along-a-line." class="nav-link" data-scroll-target="#r-is-a-measure-of-clustering-along-a-line."><span class="header-section-number">7.1.4</span> r is a measure of clustering along a line.</a></li>
  <li><a href="#association-is-not-causation" id="toc-association-is-not-causation" class="nav-link" data-scroll-target="#association-is-not-causation"><span class="header-section-number">7.1.5</span> Association is not causation</a></li>
  <li><a href="#ecological-correlations" id="toc-ecological-correlations" class="nav-link" data-scroll-target="#ecological-correlations"><span class="header-section-number">7.1.6</span> Ecological correlations</a></li>
  </ul></li>
  <li><a href="#the-regression-line" id="toc-the-regression-line" class="nav-link" data-scroll-target="#the-regression-line"><span class="header-section-number">7.2</span> The regression line</a>
  <ul class="collapse">
  <li><a href="#the-method-of-least-squares" id="toc-the-method-of-least-squares" class="nav-link" data-scroll-target="#the-method-of-least-squares"><span class="header-section-number">7.2.1</span> The method of least squares</a></li>
  <li><a href="#finding-the-regression-line-with-r" id="toc-finding-the-regression-line-with-r" class="nav-link" data-scroll-target="#finding-the-regression-line-with-r"><span class="header-section-number">7.2.2</span> Finding the regression line with R</a></li>
  <li><a href="#plotting-the-regression-line" id="toc-plotting-the-regression-line" class="nav-link" data-scroll-target="#plotting-the-regression-line"><span class="header-section-number">7.2.3</span> Plotting the regression line</a></li>
  <li><a href="#using-the-predict-function" id="toc-using-the-predict-function" class="nav-link" data-scroll-target="#using-the-predict-function"><span class="header-section-number">7.2.4</span> Using the <code>predict()</code> function</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.3</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">7.3.1</span> Exercises</a></li>
  <li><a href="#exercises-r" id="toc-exercises-r" class="nav-link" data-scroll-target="#exercises-r"><span class="header-section-number">7.3.2</span> Exercises R</a></li>
  </ul></li>
  <li><a href="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" id="toc-project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="nav-link" data-scroll-target="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">7.4</span> Project People count: The present and future of humanity in pictures and numbers</a>
  <ul class="collapse">
  <li><a href="#text" id="toc-text" class="nav-link" data-scroll-target="#text"><span class="header-section-number">7.4.1</span> Text</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>We are now ready to learn about the most important statistical tool to describe relationship between variables and to model this relationship. The model of the relationship is the basis for making predictions. After finishing this unit you will have mastered the second core skill taught in this course: Making predictions based on data on past observations.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Overview
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>In this chapter you will learn about the most widely used method for making predictions: <strong>Regression analysis</strong>.</li>
<li>Regression analysis allows us to make predictions based on a <strong>model</strong> of the data. In our course we discuss the most basic case where we model the relationship between two variables.</li>
<li>Our discussion begins with the concept of a <strong>correlation coefficient</strong>, a concept that describes how tightly a scatter plot is aligned along a straight line. This provides a measure of the strength of a <strong>linear association</strong> between two variables.</li>
<li>We explain in detail how a correlation coefficient is described and what it means, We also show how to compute correlations using R.</li>
<li>The correlation coefficient also helps us to identify the so called <strong>regression line</strong>. We explain how to do this using historic anthropometric data about the height of fathers and sons and follow in our explanation the reasoning that was behind the historic discovery of the regression line as a model of the linear relationship between two variables.</li>
<li>We discuss also the method of <strong>least squares</strong> to identify the regression line.</li>
<li>In the end we demonstrate how we can make use of R to compute regression lines and how to use it for making predictions.</li>
</ol>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Keywords
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Correlation</strong>: Correlation, expressed by the correlation coefficient measures how tightly a scatterplot is clustered around a straight line. The correlation coefficient is therefore called a measure of linear association. It is usually expressed shorthand as correlation and often abbreviated by the letter <span class="math inline">\(r\)</span>.</p>
<p><strong>Correlation Coefficient</strong>: The correlation coefficient <span class="math inline">\(r\)</span> is the average of the products of the two variables when both variables are measured in standard units or z-scores.</p>
<p><strong>Correlation is not Causation</strong>: Correlation establishes how tightly two variables are clustered around a straight line. While a causal story might be the reason for this pattern (x causing y) the pattern does not establish that x causes y in a statistical sense. Detecting a pattern is never sufficient to establish a causal relation between variables.</p>
<p><strong>Regression lines</strong>: The regression line for <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span> estimates the average value for <span class="math inline">\(y\)</span> corresponding to each value of <span class="math inline">\(x\)</span>.</p>
<p><strong>Slope and Intercept of the regression line</strong>: The <strong>slope of the regression line</strong> is: <span class="math inline">\(r \,\, \frac{\text{sd}\, y}{\text{sd}\, x}\)</span>. The <strong>intercept of the regression line</strong> is: <span class="math inline">\(\text{average of}\, y - \text{slope} \times \text{average of}\, x\)</span>.</p>
<p><strong>Least squares method</strong>: Among all lines, the line that minimizes the root mean square error in predicting <span class="math inline">\(y\)</span> from <span class="math inline">\(x\)</span> is the regression line. Moreover the regression line is the only line that minimizes the root mean square error.</p>
<p><strong><code>lm()</code> function</strong>: The <code>lm()</code> function is the R implementation of the least squares method.</p>
<p><strong><code>predict()</code></strong>: The <code>predict()</code> function allows us to make predictions from a statistical model derived by <code>lm()</code>.</p>
</div>
</div>
<p>We ended the last chapter with Pearson’s historical data on the heights of fathers and sons to introduce the concept of a scatter-plot.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> pearson</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.3</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Father's height (inches)"</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Son's height (inches)"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Pearson's height data from 1903"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We discussed how we could use the positive association in this scatter-plot to predict the height of a son from the height of the father. One intuition might be to use the straight dashed line that runs along the diagonal. If we would use this line - the diagonal - as a model for prediction, each adult son would be predicted to show the same height as his father. But we can do better than that and improve on this choice.</p>
<p>For any straight line we might choose, each data-point will give rise to a <strong>residual</strong> which is the size of the error were we to use the line as prediction.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.3</span>, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Father's height (inches)"</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Son's height (inches)"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Pearson's height data from 1903"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg =</span> <span class="fu">lm</span>(dat<span class="sc">$</span>Son <span class="sc">~</span> dat<span class="sc">$</span>Father), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">63.1</span>, <span class="fl">74.3</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">63.1</span>, <span class="fl">63.1</span>), <span class="fu">c</span>(<span class="fl">66.3264</span>, <span class="fl">74.3</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Suppose for instance that we took the father with a height of 63.1 inches and predicted the height of the son according to the model described by the red line, we would have predicted the son to have height 66.3 inches. In the data the son of the father with height 63.1 inches is in fact 74.3 inches. This is marked out as the red point in the plot. The length of the dashed line from the red point to the red line is the residual.</p>
<p>The idea of prediction using models of straight lines is to make these residuals small. We will learn a method how to do this. This approach to prediction is called regression and we will learn how it works in this chapter.</p>
<section id="correlation" class="level2 page-columns page-full" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="correlation"><span class="header-section-number">7.1</span> Correlation</h2>
<p>In the beginning of this lecture we studied the example of infant mortality. Let us first study a scatter plot which plots the number of children per woman against the infant mortality rate across countries in the world in the year 2000.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> infant_mortality_data</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dat_2000 <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">2000</span>, ]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat_2000<span class="sc">$</span>Children, dat_2000<span class="sc">$</span>Mortality,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">yaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Children per woman"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Infant mortality"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at=</span><span class="fu">pretty</span>(dat_2000<span class="sc">$</span>Mortality), <span class="at">lab=</span><span class="fu">paste0</span>(<span class="fu">pretty</span>(dat_2000<span class="sc">$</span>Mortality) <span class="sc">*</span> <span class="dv">100</span>, <span class="st">" %"</span>), <span class="at">las=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notice the positive association in the data. The scatter of points is sloping upwards, indicating that a higher number of children per woman tends to go along with a higher infant mortality rate.</p>
<div class="page-columns page-full"><p>Let’s look at another example, where we plot the average years of schooling for women on the x-axis and child mortality<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> on the y-axis. Here we see a negative correlation. Child mortality across countries in a given year, here the year 2020, tends to be negatively associated with the average years of schooling of women. In such cases we speak of a negative correlation.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Remember from the section on counts and categorical data that child mortality is the rate of children who die before their fifth birthday. Infant mortality in contrast is the rate of children dying before their first birthday.</p></li></div></div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> child_mortality_average_schooling_of_women</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>data_2020 <span class="ot">&lt;-</span> data[data<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">2020</span>, ]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_2020<span class="sc">$</span>YEW15, data_2020<span class="sc">$</span>MR,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Average years of schooling for women"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Child mortality"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <strong>correlation coefficient</strong> measures how tightly a scatterplot is clustered around a straight line. The correlation coefficient is therefore called a measure of linear association. It is usually expressed shorthand as <strong>correlation</strong> and often abbreviated by the letter <span class="math inline">\(r\)</span>.</p>
<p>Here are some mathematical properties of correlation which we will observe by simulation in a next step.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mathematical properties of correlation
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>The correlation coefficient <span class="math inline">\(r\)</span> is a number between -1 and +1.</li>
<li><span class="math inline">\(r\)</span> measures the extend to which the scatter plot clusters around a straight line.</li>
<li><span class="math inline">\(r=1\)</span> if the scatter plot is a straight line sloping upwards and <span class="math inline">\(r = -1\)</span> if the scatter plot is a straight line sloping downwards</li>
</ol>
</div>
</div>
<section id="the-correlation-coefficient" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="the-correlation-coefficient"><span class="header-section-number">7.1.1</span> The correlation coefficient</h3>
<p>R has a built in function for computing the correlation coefficient. This function is called <code>cor()</code> and takes the <span class="math inline">\(x\)</span> and the <span class="math inline">\(y\)</span> values of a scatter plot as arguments. So, for example, take the data on children per woman and infant mortality.</p>
<p>We read the data from the <code>JWL</code>package and store them in an object which we call <code>dat</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> infant_mortality_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check the variable names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Country"    "Code"       "Year"       "Mortality"  "Continent" 
[6] "Population" "Births"     "Deaths"     "Children"  </code></pre>
</div>
</div>
<p>We filter the data for the year 2000 and store these data in a new object called <code>dat_2000</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>dat_2000 <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">2000</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we compute the correlation between the average number of children per woman <code>Children</code> and the child mortality rate <code>Mortality</code>, where each data-point corresponds to a particular country around the world.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dat_2000<span class="sc">$</span>Children, dat_2000<span class="sc">$</span>Mortality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8711762</code></pre>
</div>
</div>
<p>indicating a strong positive correlation.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Write your own R-function to study properties of correlation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now let us use a function, which we call <code>r_scatter</code> to explore how the correlation coefficient shapes a scatter plot. This is an excellent opportunity to refresh our knowledge of how to write your own functions in R.</p>
<p>First, remember that each function is an R object and has a name. We already decided to call the function <code>r_scatter</code>. Then the syntax is to write <code>function()</code> and put the function arguments within the paranthesis.</p>
<p>Here we have two arguments, the correlation coefficient - let us call it according to the convention <code>r</code> - and the number of data points we want to consider. We call this number <code>n</code> and assign a default value to it, let’s say 1000.</p>
<p>Next we have to write the function body between <code>{}</code>. This is the part containing the actual instructions.</p>
<p>First we create two vectors of length <span class="math inline">\(n\)</span> of values <span class="math inline">\(x\)</span> and <span class="math inline">\(z\)</span> from a normal distribution with mean 0 and standard deviation 1. This is achieved by the r function <code>rnorm(n)</code>. Note that <code>n</code> is a function argument and since we have set a default value of <code>n</code>, unless specified otherwise R will set <code>n</code> to 1000.</p>
<p>Next we use a mathematical fact, which we do not explain here in detail. When <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> have the same standard deviation then the variable <span class="math inline">\(y\)</span> given by <span class="math display">\[\begin{equation}
y = r x + \sqrt{1 - r^2} z
\end{equation}\]</span> will have correlation coefficient <span class="math inline">\(r\)</span> with <span class="math inline">\(x\)</span>. Thus we can implement this formula in the function body, leaving <span class="math inline">\(r\)</span> unspecified. It is the function argument of <code>r_scatter</code> and will be specified by you when you call the function with a specific <span class="math inline">\(r\)</span>.</p>
<p>Then we do a scatterplot of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> which is the output of the function. The function will always render the last expression in <code>{}</code> as the output.</p>
<p>This is how the code looks like in its entirety:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>r_scatter <span class="ot">&lt;-</span> <span class="cf">function</span>(r, <span class="at">n =</span> <span class="dv">1000</span>){</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n) <span class="co"># create n observations from a standard normal distribution</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n) <span class="co"># create n observations from a standard normal distribution</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> r<span class="sc">*</span>x <span class="sc">+</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">-</span>r<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>z <span class="co"># implement the formula discussed in text.</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># do a scatter plot of x and y</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(x,y,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"y"</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(<span class="fu">c</span>(<span class="st">"Correlation coefficient is"</span>, r), <span class="at">collapse =</span> <span class="st">" "</span>),</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we call <code>r_scatter</code> a few times to see what the correlation coefficient does.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>( <span class="sc">-</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="sc">-</span> <span class="fl">0.98</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</section>
<section id="computing-r" class="level3 page-columns page-full" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="computing-r"><span class="header-section-number">7.1.2</span> Computing r</h3>
<p>How does <code>cor()</code> compute the correlation coefficient? We do not give a mathematical derivation here. One way to explain the computation is to say that</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formula for <span class="math inline">\(r\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(r\)</span> is the <strong>average of the products of the two variables</strong> when both variables are measured in <strong>standard units</strong> or z-scores.</p>
</div>
</div>
<p>Let’s do a simple example in R to explain the computation. Consider the follwoing toy data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">9</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">13</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(x,y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To convert into standard units we have to subtract the mean from each observation and divide by the standard deviation. You should be able to verify for yourself that the mean of <span class="math inline">\(x\)</span> is 4 and the standard deviation is 2 and for <span class="math inline">\(y\)</span> the corresponding values are 7 and 4.</p>
<p>Doing this operation on the values in our table will give us:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(x,y, <span class="at">x_su =</span> (x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">/</span>(<span class="fu">sd</span>(x)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>)), <span class="at">y_su =</span> (y<span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">/</span>(<span class="fu">sd</span>(y)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
<th style="text-align: right;">x_su</th>
<th style="text-align: right;">y_su</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-1.5</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">-1.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">1.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Finally we have to add the product of the standardized values <span class="math inline">\(x_{su}\)</span> and <span class="math inline">\(y_{su}\)</span> to get</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(x,y, <span class="at">x_su =</span> (x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">/</span>(<span class="fu">sd</span>(x)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>)), <span class="at">y_su =</span> (y<span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">/</span>(<span class="fu">sd</span>(y)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>)), <span class="at">xy_su =</span> (x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">/</span>(<span class="fu">sd</span>(x)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>))<span class="sc">*</span>(y<span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">/</span>(<span class="fu">sd</span>(y)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
<th style="text-align: right;">x_su</th>
<th style="text-align: right;">y_su</th>
<th style="text-align: right;">xy_su</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-1.5</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">-0.25</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">-1.5</td>
<td style="text-align: right;">-0.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">2.25</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Taking the average across these values gives <span class="math inline">\(r\)</span>. Thus we get <span class="math display">\[\begin{equation}
\frac{0.75-0.25+0.00-0.75+2.25}{5} = 0.40
\end{equation}\]</span></p>
<p>Now check this against <code>cor()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(x,y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4</code></pre>
</div>
</div>
<p>Let’s do a scatter plot of the data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="dv">2</span>, <span class="at">ny =</span> <span class="dv">2</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">new =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"y"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatter plot toy example"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="dv">4</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">4.1</span>, <span class="at">y =</span> <span class="fl">6.6</span>, </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"0"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">8.4</span>, </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"-0.25"</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">4.4</span>, </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"0.75"</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fl">1.6</span>, </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"-0.75"</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">7</span>, <span class="at">y =</span> <span class="fl">12.4</span>, </span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"2.25"</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">2.5</span>, <span class="at">y =</span> <span class="dv">10</span>, </span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="fu">paste</span>(<span class="fu">c</span>(<span class="st">"-"</span>, <span class="st">"-"</span>, <span class="st">"-"</span>, <span class="st">"-"</span>)), <span class="at">cex =</span> <span class="dv">4</span>)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="dv">10</span>, </span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"+"</span>, <span class="at">cex =</span> <span class="dv">4</span>)</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="dv">4</span>, </span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="fu">paste</span>(<span class="fu">c</span>(<span class="st">"-"</span>, <span class="st">"-"</span>, <span class="st">"-"</span>, <span class="st">"-"</span>)), <span class="at">cex =</span> <span class="dv">4</span>)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">4</span>, </span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">label =</span> <span class="st">"+"</span>, <span class="at">cex =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="page-columns page-full"><p>In this plot the <span class="math inline">\(x\)</span> axis and the <span class="math inline">\(y\)</span> axis show the values of the original table and in the plot we associate the values of the product of standardized units in the plot. The dashed lines are plotted through the points of averages, dividing the scatter plot into four quadrants. If a point is in the lower left quadrant both variables are below average and are negative in standard units. So their product is positive. In the upper right quadrant the product of two positives is positive. In the remaining two quadrants the product of a positive and a negative is negative.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The average of all these products is the correlation coefficient.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;For those of you who need a refresher about the algebra of multiplying positive and negative numbers, you might resort to the following intuition: <span class="math inline">\(3 \times 5 = 15\)</span>: Getting 5 Dollars 3 times gives you 15 Dollars. <span class="math inline">\(3 \times (-5) = -15\)</span>: Paying a 5 Dollar penalty 3 times gives you a 15 Dollar penalty. <span class="math inline">\((-3) \times 5 = -15\)</span>: Not getting 5 Dollars 3 times is not getting 15 Dollars. $(-3) (-5) = 15: Not paying a 5 Dollar penalty 3 times is getting 15 Dollars.</p></li></div></div>
<p>If <span class="math inline">\(r\)</span> is positive, then points in the two positive quadrants will predominate as for example here</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="at">r =</span> <span class="fl">0.93</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Vertical grid</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Horizontal grid  </span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If <span class="math inline">\(r\)</span> is negative points in the two negative quadrants will dominate as for example here.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r_scatter</span>(<span class="at">r =</span> <span class="sc">-</span><span class="fl">0.95</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Vertical grid</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Horizontal grid  </span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that the way correlation as a measure of linear association makes <span class="math inline">\(r\)</span> sensitive to outliers. Consider the following example from <span class="citation" data-cites="AdhDen">Adhikari, DeNero, and Wagner</span>. Let’s assume we have a scatter plot like this</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The correlation coefficient here is 1, since the points are all exactly on a line. Now assume we add a fifth point, like this - an outlier.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">0</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now the correlation <span class="math inline">\(r\)</span> is 0. So a perfect correlation is changed to no correlation by just adding one single outlying point.</p>
</section>
<section id="properties-of-r" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="properties-of-r"><span class="header-section-number">7.1.3</span> Properties of r</h3>
<p>From these observations we can observe three properties of <span class="math inline">\(r\)</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Three properties of r:
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(r\)</span> is a pure number. It has no units. This is because <span class="math inline">\(r\)</span> is computed from standard units.</li>
<li><span class="math inline">\(r\)</span> is unaffected by changing the units on either axis. This is again because <span class="math inline">\(r\)</span> is computed based on standard units.</li>
<li><span class="math inline">\(r\)</span> is unaffected when we switch the axes. Algebraically this must be the case because when we multiply <span class="math inline">\(x\)</span> by <span class="math inline">\(y\)</span> the value of the product is the same as when we multiply <span class="math inline">\(y\)</span> by <span class="math inline">\(x\)</span>. Geometrically switching axes reflects the scatterplot along the line <span class="math inline">\(x=y\)</span> but does not change the amount of clustering along the line.</li>
</ol>
</div>
</div>
</section>
<section id="r-is-a-measure-of-clustering-along-a-line." class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="r-is-a-measure-of-clustering-along-a-line."><span class="header-section-number">7.1.4</span> r is a measure of clustering along a line.</h3>
<p><span class="math inline">\(r\)</span> is a measure of clustering along a line. This is often referred to by calling <span class="math inline">\(r\)</span> a measure of linear association. Note that data are often associated in other ways not necessarily along a line. In such cases <span class="math inline">\(r\)</span> would show a weak association only.</p>
<p>As one real world examples let us take the relation between the share of extremely poor people across countries in the world in a given year versus GDP per capita in that same year. Here we take the year 2015. This is what we get.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remove World, which should not be there and Luxembourg which is an extreme outlier</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>data_2015 <span class="ot">&lt;-</span> poverty_vs_gdp[(poverty_vs_gdp<span class="sc">$</span>Year <span class="sc">==</span> <span class="dv">2015</span> <span class="sc">&amp;</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                            <span class="sc">!</span>(poverty_vs_gdp<span class="sc">$</span>Entity <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"World"</span>, <span class="st">"Luxembourg"</span>))), ]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_2015<span class="sc">$</span>GDPpc, data_2015<span class="sc">$</span>Share,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"GDP per capita"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Share in extreme poverty"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Share of population living in extreme poverty vs. GDP per</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="st">capita, 2015"</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="at">yaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20000</span>, <span class="dv">40000</span>, <span class="dv">60000</span>, <span class="dv">80000</span>),</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"20.000"</span>, <span class="st">"40.000"</span>, <span class="st">"60.000"</span>, <span class="st">"80.000"</span>), <span class="st">" "</span>, <span class="st">"$"</span>), <span class="at">cex.axis =</span> <span class="fl">0.9</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>),</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">as.character</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>)), <span class="st">" "</span>, <span class="st">"%"</span>), <span class="at">cex.axis =</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can see that the data show a strong association between GDP per capita and the share of extreme poverty, which is intuitive. Moreover this association is not along a straight line.</p>
<p>If we would compute the correlation coefficient in these data, we would get a value of -0.4532214, a weak negative association.</p>
<p>In the following picture we show the data with smooth curve that approximates the shape of the data in red. Had we fitted a straight line to these data, you can see from the picture that the fit is poor. Though there seems to be a relatively strong association between GDP per capita and the share of people living in extreme poverty, it is not a linear association, i.e.&nbsp;an association along a straight line. The correlation coefficient only captures the clustering of data points along a straight line.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> data_2015<span class="sc">$</span>GDPpc, <span class="at">y =</span> data_2015<span class="sc">$</span>Share)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>y,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"GDP per capita"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Share in extreme poverty"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Share of population living in extreme poverty vs. GDP per</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="st">capita, 2015"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="at">yaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20000</span>, <span class="dv">40000</span>, <span class="dv">60000</span>, <span class="dv">80000</span>),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"20.000"</span>, <span class="st">"40.000"</span>, <span class="st">"60.000"</span>, <span class="st">"80.000"</span>), <span class="st">" "</span>, <span class="st">"$"</span>), <span class="at">cex.axis =</span> <span class="fl">0.9</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>),</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">as.character</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>)), <span class="st">" "</span>, <span class="st">"%"</span>), <span class="at">cex.axis =</span> <span class="fl">0.9</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(stats<span class="sc">::</span><span class="fu">lowess</span>(df, <span class="at">f=</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">7</span>), <span class="at">lw =</span> <span class="dv">2</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="dv">4</span>, <span class="at">lw =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="association-is-not-causation" class="level3" data-number="7.1.5">
<h3 data-number="7.1.5" class="anchored" data-anchor-id="association-is-not-causation"><span class="header-section-number">7.1.5</span> Association is not causation</h3>
<p>In the discussion of correlations we need to come back to an issue we had discussed in a previous lecture. It is important to keep in mind that correlations measure linear association between two variables but association is not the same as causation.</p>
<p>Let me come back to an example we discussed earlier in section 3, where we looked at the correlation between average learning outcomes and total education expenditure by per capita documented in the study by <span class="citation" data-cites="Hedgesetal1994">Larry Hedges (<a href="references.html#ref-Hedgesetal1994" role="doc-biblioref">1994</a>)</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(expenditure_outcome_dat<span class="sc">$</span>Expenditure, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>     expenditure_outcome_dat<span class="sc">$</span>Outcome, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> (<span class="st">"Average learning outcomes by total education expenditure per capita"</span>), </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> (<span class="st">"Public and private per capita expenditure on education (PPP, constant 2011-intl $)"</span>), </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> (<span class="st">"Average harmonized learning outcome in 2005 - 2015"</span>), <span class="at">pch =</span> <span class="dv">16</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">seq</span>(<span class="dv">500</span>, <span class="dv">3500</span>, <span class="at">by =</span> <span class="dv">500</span>))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Outcome <span class="sc">~</span> Expenditure, <span class="at">data =</span> expenditure_outcome_dat)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="dv">4</span>, <span class="at">lw =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The correlation in these data is 0.5684246. But does this evidence does not support the conclusion that there is a causal relation between increased educational spending and student outcomes. Comparing outcomes of students across countries or students across schools with different levels of spending does not tell us whether the different spending levels are causal for the variation in outcomes we observe. There may be many other differences between countries and students that are shaping this relationship.</p>
</section>
<section id="ecological-correlations" class="level3" data-number="7.1.6">
<h3 data-number="7.1.6" class="anchored" data-anchor-id="ecological-correlations"><span class="header-section-number">7.1.6</span> Ecological correlations</h3>
<p>The previous example shows a case of correlations based on averages. We have seen by now various examples of such correlations. Correlations based on averages can be frequently found in social sciences such as sociology, political science or economics. However these correlations have to be assessed with care because they can overstate the strength of an association.</p>
<p>Let me illustrate this point by a hypothetical example. Many studies have looked at the association between individual education and individual income, claiming a positive association between the level of education and individual income. Suppose a survey had collected data on income and education for individuals in three countries, labelled by three colors: Country red, country orange and country blue. Each individual is marked by one color symbolizing it’s country of residence. Let’s do not worry about the exact units. Say education is measured by some form of time of education and income in some monetary unit.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>) <span class="co"># set the random number generator seed</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">24</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="dv">1153</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="dv">20000</span>, <span class="dv">8000</span>) <span class="co"># create the toy data of duration of edcuation and income</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Education =</span> x, <span class="at">Income =</span> y) <span class="co"># write into dataframe</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>State <span class="ot">&lt;-</span>  <span class="fu">with</span>(df, <span class="fu">ave</span>(<span class="fu">seq_along</span>(Income), Income, <span class="at">FUN =</span> <span class="cf">function</span>(x)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Red"</span>, <span class="st">"Blue"</span>, <span class="st">"Orange"</span>), <span class="at">size =</span> <span class="fu">length</span>(x), <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)))) <span class="sc">|&gt;</span>    <span class="fu">as.factor</span>() <span class="co"># asign colors as factors to the education and income combination</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  color_pallete_function <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"orange"</span>, <span class="st">"blue"</span>),</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">space =</span> <span class="st">"Lab"</span> <span class="co"># Option used when colors do not represent a quantitative scale</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># define a state by a color</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  num_colors <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(df<span class="sc">$</span>State)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  df_state_state <span class="ot">&lt;-</span> <span class="fu">color_pallete_function</span>(num_colors)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Do the exercise for state averages</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>  col1 <span class="ot">&lt;-</span> <span class="fu">tapply</span>(df<span class="sc">$</span>Education, df<span class="sc">$</span>State, mean)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>  col2 <span class="ot">&lt;-</span> <span class="fu">tapply</span>(df<span class="sc">$</span>Income, df<span class="sc">$</span>State, mean)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>df_avg <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Education =</span> col1, <span class="at">Income =</span> col2, <span class="at">State =</span> <span class="fu">as.factor</span>(<span class="fu">names</span>(col1)))</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>num_colors_avg <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(df_avg<span class="sc">$</span>State)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>df_state_state_avg <span class="ot">&lt;-</span> <span class="fu">color_pallete_function</span>(num_colors_avg)</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="co"># plot side by side</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a><span class="co"># plot for individual values</span></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> df<span class="sc">$</span>Education,</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> df<span class="sc">$</span>Income,</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Individual education"</span>,</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Individual income"</span>,</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">20</span>, <span class="co"># solid dots increase the readability of this data plot</span></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> df_state_state[df<span class="sc">$</span>State],</span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">yaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a><span class="co"># plot for aggregated values</span></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> df_avg<span class="sc">$</span>Education,</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> df_avg<span class="sc">$</span>Income,</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Country average education"</span>,</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Country average income"</span>,</span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">20</span>, <span class="co"># solid dots increase the readability of this data plot</span></span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> df_state_state_avg[df_avg<span class="sc">$</span>State],</span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">yaxt =</span> <span class="st">"n"</span></span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the averaged data the correlation increases from 0.848 to 0.996 or by about 17.5 %. So bear in mind that, while correlations based on averages are frequently encountered in the press, in reports and in the research literature, they tend to overstate the strength of an association.</p>
</section>
</section>
<section id="the-regression-line" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="the-regression-line"><span class="header-section-number">7.2</span> The regression line</h2>
<p>The correlation coefficient does not only measure the strength of linear association along a line, it also helps us identifying this line. In order to help you discover this, let us go back to the Pearson data on the height of fathers and sons, we used in the beginning of this chapter.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> pearson</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.3</span>, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Father's height (inches)"</span>, </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Son's height (inches)"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Pearson's height data from 1903"</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="fl">1.036765</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="dv">4</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">67.69</span> <span class="sc">+</span> <span class="fl">2.75</span> <span class="sc">-</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">67.69</span> <span class="sc">+</span> <span class="fl">2.75</span> <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">70.44</span>, <span class="fl">70.12</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">73.19</span>, <span class="fl">71.56</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">62.19</span>, <span class="fl">65.8</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Son <span class="sc">~</span> Father, <span class="at">data =</span> dat)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The summary statistics of the data are:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data_father_son <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Father =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Father), <span class="fu">sd</span>(dat<span class="sc">$</span>Father)),<span class="dv">2</span>), </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Son =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">mean</span>(dat<span class="sc">$</span>Son), <span class="fu">sd</span>(dat<span class="sc">$</span>Son)),<span class="dv">2</span>), <span class="at">row.names =</span> <span class="fu">c</span>(<span class="st">"Mean"</span>, <span class="st">"Standard Deviation"</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(data_father_son)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Father</th>
<th style="text-align: right;">Son</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">67.69</td>
<td style="text-align: right;">68.68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard Deviation</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">2.82</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The correlation coefficient is <span class="math inline">\(r\)</span> = 0.501.</p>
<p>The dashed blue line in the picture is the line starting at 0 and increasing with the slope given by the standard-deviation of the father’s height - 2.82 - divided by the standard deviation of the son’s height - 2.72. This is a slope of approximately 1. The vertical strip with the dashed black lines show the fathers who were one standard deviation above average - 70.44 to the nearest inch, i.e. plus minus 0.5 inches. You can see that most of the points in this vertical strip are below the dashed red line. This means that most of the son’s whose father’s were 1 standard deviation above average were less than a standard deviation above average. The average height of the sons is only a fraction of a standard deviation above the average height. This is where the correlation coefficient <span class="math inline">\(r\)</span> = 0.51 comes in. Associated with an increase of one standard deviation in height by the father is and increase of only 0.51 standard deviations in height of the son on average.</p>
<p>Take the father whose height is one standard deviation above average: 67.69 + 2.75 = 70.44 in. The average height of their sons will be above average by 0.51 standard deviations of their height, or <span class="math inline">\(0.51 \times 2.82\)</span>, which is <span class="math inline">\(1.44\)</span>. So the average height of a son is <span class="math inline">\(68.68 + 1.44\)</span> The point <span class="math inline">\((70.44, 70.12)\)</span> is marked by a red dot in the figure.</p>
<p>Now let’s look at the father’s who are two standard deviations above the average height: <span class="math inline">\(67.69 + 2 \times 2.75\)</span> which is <span class="math inline">\(73.19\)</span>. The average height of their sons should be above <span class="math inline">\(2 \times 0.51\)</span> of their height, or <span class="math inline">\(1.02\)</span> standard deviations of height. That is <span class="math inline">\(1.02 \times 2.82\)</span> or <span class="math inline">\(2.88\)</span>. That is their average height is around <span class="math inline">\(68.68 + 2.88\)</span> or <span class="math inline">\(71.56\)</span>. We mark the point <span class="math inline">\((73.19, 71.56)\)</span> also as a red dot in our picture.</p>
<p>What about those who are 2 standard deviations below the average? Their height is <span class="math inline">\(67.69 - 2 \times 2.75\)</span>, which is <span class="math inline">\(62.19\)</span>. The average height of the sons is then about <span class="math inline">\(68.68 - 2.88\)</span> or <span class="math inline">\(65.8\)</span>. We also mark the point <span class="math inline">\((62.19, 65.8)\)</span> by a red dot.</p>
<p>Now all points that combine the father’s height with the estimate of the average height of the son fall on the solid red line which connects the red dots. This line is called the <strong>regression line</strong>. The line goes through the points of averages. Fathers with average heights should have sons with average height.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Regression line
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>regression line</strong> for <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span> estimates the average value for <span class="math inline">\(y\)</span> corresponding to each value of <span class="math inline">\(x\)</span>.</p>
</div>
</div>
<p>The method with which we have estimated this line is called the <strong>regression method</strong>. It associated in our example with each increase in one standard deviation in height by the father an increase of <span class="math inline">\(0.51\)</span> standard deviations of the son. More generally:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Regression method
</div>
</div>
<div class="callout-body-container callout-body">
<p>Associated with each increase of one standard deviation in <span class="math inline">\(x\)</span> there is an increase of only <span class="math inline">\(r\)</span> standard deviations in <span class="math inline">\(y\)</span> on average.</p>
</div>
</div>
<p>From our picture and the discussion we can also learn how the regression line can be described mathematically:</p>
<p>When the variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are measured in standard units, the regression line for predicting <span class="math inline">\(y\)</span> based on <span class="math inline">\(x\)</span> has slope <span class="math inline">\(r\)</span> and passes through the origin. Thus the regression equation can be written as <span class="math display">\[\begin{equation*}
\text{estimate of} \, y = r x \, \text{when both variables are measured in standard units}
\end{equation*}\]</span></p>
<p>When we write this equation not in standard units but in the original units of the data, this equation becomes <span class="math display">\[\begin{equation*}
\frac{\text{estimate of} \, y - \text{average of } \,y}{\text{sd of} \,y} = r \,\, \frac{\text{given} \, x - \text{average} \, x}{\text{sd of} \, x}
\end{equation*}\]</span></p>
<p>This means, we have:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Slope and Intercept of the regression line
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>The <strong>slope of the regression line</strong> is: <span class="math inline">\(r \,\, \frac{\text{sd}\, y}{\text{sd}\, x}\)</span></li>
<li>The <strong>intercept of the regression line</strong> is: <span class="math inline">\(\text{average of}\, y - \text{slope} \times \text{average of}\, x\)</span></li>
</ol>
</div>
</div>
<section id="the-method-of-least-squares" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="the-method-of-least-squares"><span class="header-section-number">7.2.1</span> The method of least squares</h3>
<p>Finding a regression line is a standard problem often encountered in statistics either to make predictions, when you run controlled experiments or to describe the data you see for a given population.</p>
<p>In the previous section we have explained how a regression line for a scatter plot can be found. In our discussion we followed the path how the regression line was historically detected by the pioneers of statistics.</p>
<p>In current practice the regression line is usually determined in another way. When the points in a scatter plot seem to follow a straight line, we could ask the question which line fits the points best.</p>
<p>Let’s go back to the graph discussed in the very beginning:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(JWL)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> pearson</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.3</span>, </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Father's height (inches)"</span>, </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Son's height (inches)"</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Pearson's height data from 1903"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg =</span> <span class="fu">lm</span>(dat<span class="sc">$</span>Son <span class="sc">~</span> dat<span class="sc">$</span>Father), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">63.1</span>, <span class="fl">74.3</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">63.1</span>, <span class="fl">63.1</span>), <span class="fu">c</span>(<span class="fl">66.3264</span>, <span class="fl">74.3</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fl">71.1</span>, <span class="fl">66.3</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="fl">71.1</span>,<span class="fl">71.1</span>), <span class="fu">c</span>(<span class="fl">66.3</span>, <span class="fl">70.4384</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Any straight line drawn through this point cloud will be near to some points and farther from others. One such distance from the line to a particular point is marked in the graph by a red dot. When we move the red line around, we will get closer with the line to some points and farther from others.</p>
<p>This conflict can be resolved in two steps: First define an average distance of all the points to the line. Second, move the line around until this average distance is as small as possible.</p>
<p>When <span class="math inline">\(x\)</span> is used to predict <span class="math inline">\(y\)</span> the error at each point is the vertical distance of the point to the line, like in our graph. Now, some distances will be positive, some will be negative, so to minimize the average distance, you can not just add the distances because negative and positive values will cancel each other. Instead statisticians take the square of these distances, because the square will always be positive, no matter, whether the distance has a negative or positive value. This square of the distances is also known as the <strong>root mean square error</strong>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Regression line by least squares
</div>
</div>
<div class="callout-body-container callout-body">
<p>Among all lines, the line that minimizes the root mean square error in predicting <span class="math inline">\(y\)</span> from <span class="math inline">\(x\)</span> is the regression line. Moreover the regression line is the only line that minimizes the root mean square error.</p>
</div>
</div>
</section>
<section id="finding-the-regression-line-with-r" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="finding-the-regression-line-with-r"><span class="header-section-number">7.2.2</span> Finding the regression line with R</h3>
<section id="the-lm-function" class="level4" data-number="7.2.2.1">
<h4 data-number="7.2.2.1" class="anchored" data-anchor-id="the-lm-function"><span class="header-section-number">7.2.2.1</span> The <code>lm()</code> function</h4>
<p>Regression is such an important topic and basic tool in statistics, that every software package has built in functions, to help you compute the regression line. In R this function is called <code>lm()</code> for linear model. As usual with functions, <code>lm()</code> takes arguments.</p>
<p>The first argument is of a type we did not encounter before. It is called in R a formula and has the following syntax. Suppose we want to fit a linear model <span class="math display">\[\begin{equation}
y = k x + d
\end{equation}\]</span> to our height data. <span class="math inline">\(y\)</span> is the vector of the father’s heights and <span class="math inline">\(x\)</span> is the vector of the son’s heights. The intercept of this line with the <span class="math inline">\(y\)</span> axis is <span class="math inline">\(d\)</span>. To tell R that this is our formula we write <code>name of y ~ name of x</code>.</p>
<p>Let me explain. Here in our discussion we stored the data in a dataframe which we called <code>dat</code>. This dataframe has two variables, which we called <code>Father</code> and <code>Son</code>. Now the formula we need to give to <code>lm</code> needs to be called in this case <code>Son ~ Father</code>.</p>
<p>Where is the constant <span class="math inline">\(d\)</span> in this formula? <code>lm()</code> automatically assumes that there is an intercept term. This has not to be specified in particular when passing the formula to <code>lm()</code>. The second argument you need to give to <code>lm()</code> is the data. This is called in our case <code>dat</code>.</p>
<p>So now we have the syntax:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Son <span class="sc">~</span> Father, <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Son ~ Father, data = dat)

Coefficients:
(Intercept)       Father  
     33.893        0.514  </code></pre>
</div>
</div>
<p>The output shows the value of the intercept <span class="math inline">\(d = 33.893\)</span> and the slope <span class="math inline">\(k = 0.514\)</span>. Let’s briefly check how this fits together with your discussion of the regression line. The correlation, the standard deviation of the son’s height and the standard deviation of the father’s height determine the slope <span class="math inline">\(k\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat<span class="sc">$</span>Father, dat<span class="sc">$</span>Son)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>SDF <span class="ot">&lt;-</span> <span class="fu">sd</span>(dat<span class="sc">$</span>Father)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>SDS <span class="ot">&lt;-</span> <span class="fu">sd</span>(dat<span class="sc">$</span>Son)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>r<span class="sc">*</span>SDS<span class="sc">/</span>SDF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5140059</code></pre>
</div>
</div>
<p>which is indeed the slope of the regression line.</p>
<p>For the intercept we derived:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>Son) <span class="sc">-</span> r<span class="sc">*</span><span class="fu">mean</span>(dat<span class="sc">$</span>Father)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34.76212</code></pre>
</div>
</div>
<p>which is the (almost) the same as the value of the intercept computed by <code>lm()</code>.</p>
</section>
</section>
<section id="plotting-the-regression-line" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="plotting-the-regression-line"><span class="header-section-number">7.2.3</span> Plotting the regression line</h3>
<p>Assume we would like to plot the regression line together with a scatter-plot of the data. We would first store the output of <code>lm()</code> in an object, let us call this object <code>mod</code> for model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Son <span class="sc">~</span> Father, <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then plotting the scatter plot together with the regression line can be done as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Father, dat<span class="sc">$</span>Son, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.3</span>, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Father's height (inches)"</span>, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Son's height (inches)"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Pearson's height data from 1903"</span>) <span class="co"># Syntax for the scatter plot </span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="co"># syntax for the regression line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelling_relationships_using_regression_part_2_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We first draw the scatter plot using the R <code>plot()</code>function. The arguments <code>pch</code> and <code>cex</code> control the type and size of the dots and <code>xlab</code>, <code>ylab</code> and <code>main</code> control the lables of the x-axis, the y-axis and the main plot.</p>
<p>Then we give the output of <code>lm()</code> the function <code>abline()</code> and tell <code>abline()</code>that the color of the line should be red and the line width should be 2. That’s it.</p>
</section>
<section id="using-the-predict-function" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="using-the-predict-function"><span class="header-section-number">7.2.4</span> Using the <code>predict()</code> function</h3>
<p>Finally, let us briefly show you an R function which helps you to check the predictions made by the linear model of the regression line using the built in function <code>predict()</code>.</p>
<p>Note that our regression line was computed as <span class="math display">\[\begin{equation}
\text{Son's height} = 0.51 \times \text{Father's height} + 33.89
\end{equation}\]</span> Now assume you want to make predictions for the height of the son based on the height of the father using this linear model. In this case this is easy to compute by hand but for many values (and even for few) this step can be automated using the <code>predict()</code>function of R. <code>predict()</code>needs as arguments the output of <code>lm()</code> plus a dataframe of new data.</p>
<p>We have already stored the output of <code>lm()</code>in our object <code>mod</code>. Now define some new data and then give the model and the new data to the <code>predict()</code>function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Father =</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">70</span>, <span class="dv">80</span>))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod, newdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3 
64.73316 69.87321 75.01327 </code></pre>
</div>
</div>
<p>So what predict does for you in one step is to compute for example for the value 80</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.514</span> <span class="sc">*</span><span class="dv">80</span> <span class="sc">+</span> <span class="fl">33.893</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75.013</code></pre>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="exercises"><span class="header-section-number">7.3</span> Exercises</h2>
<section id="exercises-1" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">7.3.1</span> Exercises</h3>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1: Comparing correlations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Look at the following four data sets. Rank them from weakest to strongest correlations.</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="pictures/corr_plot_A.png" class="img-fluid" alt="A"> <img src="pictures/corr_plot_B.png" class="img-fluid" alt="B"> <img src="pictures/corr_plot_C.png" class="img-fluid" alt="C"> <img src="pictures/corr_plot_D.png" class="img-fluid" alt="D"></p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2: Interpreting correlation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Studies find a negative correlation between hours spent watching television and scores on reading tests. Does watching television make people less able to read? Discuss briefly.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exerxise 3: Correlation between height and weight
</div>
</div>
<div class="callout-body-container callout-body">
<p>The correlation between height and weight among men 18-74 in the US is about 0.40. Say whether each conclusion follows from the data, explain your answer:</p>
<ol type="1">
<li>Taller men tend to be heavier</li>
<li>The correlation between weight and height for men 18-74 is 0.4</li>
<li>Heavier men tend to be taller</li>
<li>If someone eats more and puts on 10 pounds, he is likely to get somewhat taller.</li>
</ol>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 4: Explain
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we calculate the correlation coefficient, why do we convert data to standard units?</p>
</div>
</div>
</section>
<section id="exercises-r" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="exercises-r"><span class="header-section-number">7.3.2</span> Exercises R</h3>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1: Write a conversion function from any data to standard units:
</div>
</div>
<div class="callout-body-container callout-body">
<p>Write a function called <code>convert_su</code> which takes in a dataframe of elements called data and returns a dataframe of the values represented in standard units. To do a specific computation with the function take the dataset <code>pearson</code> from the <code>JWL</code>package. These are the data we used in the lecture.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2: Write your own function to compute correlation.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Write a function called <code>calculate_correlation</code> which takes in a dataframe which is the output of <code>convert_su</code> and returns the correlation coefficient. Again test your function with the <code>pearson</code>dataset from the <code>JWL</code> package.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 3: Advertising channels and sales
</div>
</div>
<div class="callout-body-container callout-body">
<p>Load the <code>advertising</code> dataset from the <code>JWL</code> package. The data show 200 samples of advertising expenditures via different advertising channels, TC, radio and newspaper as well as revenues from sales.</p>
<ol type="1">
<li><p>Visualize the association between advertising expenditures and the value of sales for each advertising channel. Interpret the graphs in your own words.</p></li>
<li><p>Compute the correlation between advertising expenditures and sales for the different advertising channels.</p></li>
<li><p>Build a linear model between advertising expenditures via TV and sales and display a scatterplot of the data as well as the regression line. Use <code>lm()</code> to compute the intercept and the slope of the regression line.</p></li>
<li><p>Predict the sales from the model if we spend 0 on TV advertising? What are the predicted sales if we spend 300 on advertising?</p></li>
</ol>
</div>
</div>
</section>
</section>
<section id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">7.4</span> Project People count: The present and future of humanity in pictures and numbers</h2>
<section id="text" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="text"><span class="header-section-number">7.4.1</span> Text</h3>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-AdhDen" class="csl-entry" role="listitem">
Adhikari, Ani, John DeNero, and David Wagner. <span>“Computational and Inferential Thinking: The Foundations of Data Science.”</span> <a href="https://inferentialthinking.com/chapters/intro.html" class="uri">https://inferentialthinking.com/chapters/intro.html</a>.
</div>
<div id="ref-Hedgesetal1994" class="csl-entry" role="listitem">
Larry Hedges, Rob Greenwald, Richard Laine. 1994. <span>“Does Money Matter? A Meta-Analysis of Studies of the Effects of Differential School Inputs on Student Outcomes.”</span> <em>Educational Researcher</em> 3 (23): 5–14.
</div>
</div>
</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./modelling_relationships_using_regression_part_1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling relationships: Points, Lines and Scatterplots</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./how_sure_can_we_be.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>