<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics - 10&nbsp; Putting probability and statistics together</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./answering_questions_and_claiming_discoveries.html" rel="next">
<link href="./probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./probability_and_statistics.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><strong>Introduction</strong></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical_data_and_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Data and Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summarizing_and_communicating_lots_of_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing and communicating lots of data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./from_limited_data_to_populations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From limited data to populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_causes_what.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">What causes what?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling relationships: Points, Lines and Scatterplots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelling_relationships_using_regression_part_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelling relationship: Prediction using regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_sure_can_we_be.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">How sure can we be about what is going on: Estimates and intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variabilility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_and_statistics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answering_questions_and_claiming_discoveries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Answering questions and claiming discoveries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#boys-and-girls-using-probability-theory-to-find-a-sampling-distribution." id="toc-boys-and-girls-using-probability-theory-to-find-a-sampling-distribution." class="nav-link active" data-scroll-target="#boys-and-girls-using-probability-theory-to-find-a-sampling-distribution."><span class="header-section-number">10.1</span> Boys and Girls: Using probability theory to find a sampling distribution.</a>
  <ul class="collapse">
  <li><a href="#the-binomial-distribution" id="toc-the-binomial-distribution" class="nav-link" data-scroll-target="#the-binomial-distribution"><span class="header-section-number">10.1.1</span> The binomial distribution</a></li>
  <li><a href="#expected-value" id="toc-expected-value" class="nav-link" data-scroll-target="#expected-value"><span class="header-section-number">10.1.2</span> Expected value</a></li>
  <li><a href="#standard-error" id="toc-standard-error" class="nav-link" data-scroll-target="#standard-error"><span class="header-section-number">10.1.3</span> Standard error</a></li>
  <li><a href="#using-the-normal-curve-when-the-number-of-draws-is-large" id="toc-using-the-normal-curve-when-the-number-of-draws-is-large" class="nav-link" data-scroll-target="#using-the-normal-curve-when-the-number-of-draws-is-large"><span class="header-section-number">10.1.4</span> Using the normal curve when the number of draws is large</a></li>
  <li><a href="#the-central-limit-theorem-and-probability-histograms" id="toc-the-central-limit-theorem-and-probability-histograms" class="nav-link" data-scroll-target="#the-central-limit-theorem-and-probability-histograms"><span class="header-section-number">10.1.5</span> The central limit theorem and probability histograms</a></li>
  </ul></li>
  <li><a href="#working-out-the-accuracy-of-estimates" id="toc-working-out-the-accuracy-of-estimates" class="nav-link" data-scroll-target="#working-out-the-accuracy-of-estimates"><span class="header-section-number">10.2</span> Working out the accuracy of estimates</a>
  <ul class="collapse">
  <li><a href="#the-accuracy-of-percentages" id="toc-the-accuracy-of-percentages" class="nav-link" data-scroll-target="#the-accuracy-of-percentages"><span class="header-section-number">10.2.1</span> The accuracy of percentages</a></li>
  <li><a href="#confidendence-intervals" id="toc-confidendence-intervals" class="nav-link" data-scroll-target="#confidendence-intervals"><span class="header-section-number">10.2.2</span> Confidendence intervals</a></li>
  <li><a href="#the-accuracy-of-averages" id="toc-the-accuracy-of-averages" class="nav-link" data-scroll-target="#the-accuracy-of-averages"><span class="header-section-number">10.2.3</span> The accuracy of averages</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">10.3</span> Exercises:</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">10.3.1</span> Exercises</a></li>
  </ul></li>
  <li><a href="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" id="toc-project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="nav-link" data-scroll-target="#project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">10.4</span> Project People count: The present and future of humanity in pictures and numbers</a></li>
  <li><a href="#this-is-a-level-1-heading" id="toc-this-is-a-level-1-heading" class="nav-link" data-scroll-target="#this-is-a-level-1-heading"><span class="header-section-number">11</span> This is a level 1 heading</a>
  <ul class="collapse">
  <li><a href="#this-is-a-level-2-heading" id="toc-this-is-a-level-2-heading" class="nav-link" data-scroll-target="#this-is-a-level-2-heading"><span class="header-section-number">11.1</span> This is a level 2 heading</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Putting probability and statistics together</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the last unit on probability we analyzed randomizing devices such as dice and coins. We have assumed the in these cases that we can enlist all the possible outcomes that might potentially be observed and we can attach chances or probabilities to these outcomes. One example was 1/2 for a fair coin coming up Heads, or 1/6 for the die showing any of its faces after a throw, or 1/36 for two dice showing one of the possible combinations of points.</p>
<p>When we attach to each of these outcomes some quantity, for example 1 for Heads and 0 for Tails, probability theorists say that we have a <strong>random variable</strong> with a probability distribution. The randomizing device is such that it is ensured that the observation is generated at random from this distribution. This probability distribution can be described by parameters, such as the mean, for example in the case of the Poisson Distribution, or the mean and the standard deviation in the case of the normal distribution. We also learned how we can use R to draw data points from a probability distribution described by its parameters.</p>
<p>The usual situation, we face in statistics is that we have to deal with lots of data and we give an overall description of these data usually by a summary statistics like the mean, the median or other percentiles.</p>
<p>A fundamental step and a key idea in statistics, where probability and statistics come together, is the idea that we can view a particular statistics like the mean also as a random variable and its values as draws from its own probability distribution. Using this perspective allows statisticians to assess the uncertainty of estimates of population parameters using probability theory. This is a conceptually challenging and difficult idea, which we are going to develop in this unit.</p>
<p>We have encountered a method to achieve such a quantification of uncertainty when we discussed the bootstrap in unit 5. There we took repeated samples with replacement from the distribution of human height data and computed the mean height at each step. In this way we generated a distribution of the mean height that gave us some idea about the precision of this estimate.</p>
<p>In contrast to bootstrapping which is a computer intensive simulation technique, probability theory provides an alternative approach to give a mathematical answer to the same question: How confident can we be about the precision of our statistics? In this approach we can save on computing resources but we need - as in any mathematical theory - assumptions and we need to think about whether these assumptions are justified in each single situation where we apply the theory.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Overview
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this unit you will learn how we can use probability theory to <strong>quantify the uncertainty of a sampling statistics</strong> as a measure about the true underlying paremter of a population, such as the mean or a proportion. This is an important, though conceptually challenging idea.</p>
<p>The first step in this process is that we learn <strong>how a known population gives rise to different samples</strong>.</p>
<p>We discuss the notions of <strong>expected value</strong> and the <strong>standard error</strong> of a random variable and we analyze the expected value and the standard error of a sum and a proportion using <strong>box-models</strong> and the idea of drawing at random with replacement from a box.</p>
<p>We learn what chance error is and how the <strong>square root law</strong> can describe the chance error of sums and proportions for situations that can be described as random draws with replacement from a box.</p>
<p>A key step in this analysis is an insight known as the <strong>central limit theorem</strong> which says that when we draw at random with replacement from a box, the probability histogram for the sum will follow the normal curve, even is the contents of the box is not normally distributed, provided the number of draws is large enough.</p>
<p>This is a key step in bringing probability and statistics together for it helps us to work out the <strong>accuracy of estimates of the sum, the average and or proportions</strong> using the normal distribution.</p>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Keywords
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Random drawing with replacement from a box-model</strong> is our key model of a random variable, which arises if we attach to each outcome of a random process a quantity.</p>
<p><strong>Expected value of the sum of random draws of tickets from a box made with replacement</strong> is equal to <span class="math inline">\((\text{the number of draws}) \times (\text{average of the box})\)</span></p>
<p><strong>Square root law</strong>: When drawing at random with replacement form a box of numbered tickets, the standard error for the sum of the draws is <span class="math inline">\(\sqrt{\text{number of draws}} \times (\text{standard deviation of the box})\)</span></p>
<p><strong>Probability histogram</strong> represents probabilities, not data. A probability historgam represents chance by area.</p>
<p><strong>Central limit theorem</strong> When drawing at random with replacement from a box, the probability histogram for the sum will follow the normal curve, even is the contents of the box is not normally distributed, provided the number of draws is large enough.</p>
<p><strong>Confidence interval</strong>: A confidence interval is used when estimating an unknown parameter from sample data. The interval gives a range for the parameter, and a confidence level that the range covers the true value.</p>
</div>
</div>
<section id="boys-and-girls-using-probability-theory-to-find-a-sampling-distribution." class="level2 page-columns page-full" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="boys-and-girls-using-probability-theory-to-find-a-sampling-distribution."><span class="header-section-number">10.1</span> Boys and Girls: Using probability theory to find a sampling distribution.</h2>
<p>In unit 3 we talked about random samples, where we draw a sample from a population and want to learn from the sample statistics about the value of the statistics - say a proportion - in the underlying population. For this we need to know how a known population gives rise to different samples. Let us think about this problem in terms of concrete example.</p>
<p>In a random sample of 1000 newborn babies we find that there are 487 girls and 513 boys. What can we say about the proportion of baby boys and girls in the population of all newborns in a country?</p>
<p>Assume we draw random samples of different sizes from a population of newborns in a country containing exactly 48.7 % baby girls an 51.3 % baby boys. We would like to find the probability of observing possible proportions of baby girls and baby boys. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;The probabilities we use here are actually the natural probabilities that a baby is a girl or a boy. These probabilities have been historically very stable. The outcomes are also independent across births. The independence assumption is justified when we abstract for the moment from rare events such as twins and triplets. In this case things are a bit more complicated but let’s not worry about these special cases for now.</p></div></div><p>Now, of course, this is not the situation we encounter in practice. In practice we can only use the sample to learn about the unknown population. But we can only get to such a conclusion by first exploring how a known population gives rise to different samples. Let’s imagine an example to understand this distinction better.</p>
<p>We could think of the situation in terms of a box model. Think of the population of 10 newborns as being in a box where we know that 4 babies are girls and 6 are boys and we draw a sample of size 4 from this box at random.</p>
<p><img src="pictures/box_proportion.png" class="img-fluid" alt="Random draws from a box with known proportions"> This is the first situtuation. We have a population with known distribution and draw at random from this population. Using probability theory we can work out the probabilities of getting different proportions of baby girls and boys.</p>
<p>The situation we encounter in the practice of statistics is, however, rather the second situation. We have only a sample and want to learn about the population. Look at the following picture.</p>
<p><img src="pictures/box_proportion_dist_unkown.png" class="img-fluid" alt="Random draws from a box with unkwn proportions"> In order to understand the first situation we can help ourselves via the application of probability theory. This will be a necessary step to understand how probability and statistics hang together and by this insight understand the second situation.</p>
<p>Let us work out an answer to the first situation now. Suppose the sample has a size of only 1. Then the proportion of baby girls must be either 0 or 1 depending whether we have selected a girl or a boy. These events occur with probability 0.513 (boy) ans 0.487 (girl).</p>
<p>The resulting probability distribution is shown here:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">c</span>(<span class="fl">0.513</span>, <span class="fl">0.487</span>), <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"0 (boy)"</span>, <span class="st">"1 (girl)"</span>), </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Probability Distribution: Sample size 1"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Suppose our sample consists of two babies drawn at random from the population of newborns. Then the proportion of girls will be either 0 (both boys), 0.5 (one girl and one boy) or 1 (both girls).</p>
<p>Let’s work out the probabilities of these proportions: The probability of two boys must be <span class="math inline">\(0.513 \times 0.513 = 0.263\)</span>. (multiplication rule and independence) The probability of two girls must be <span class="math inline">\(0.487 \times 0.487 = 0.237\)</span> and so the probability of one of each must be <span class="math inline">\(1 - 0.263 - 0.237 = 0.5\)</span> (Complement rule). The resulting probability distribution is here.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">c</span>(<span class="fl">0.236</span>, <span class="fl">0.5</span>, <span class="fl">0.237</span>), <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"0 (both boys)"</span>, <span class="st">"0.5 (boy and girl)"</span>, <span class="st">"1 (both girls"</span>),</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Probability Distribution: Sample size 2"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of Girls"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We could now use probability theory to work out the probability distribution for even larger and larger samples. How would we do that?</p>
<p>Suppose we would like to find the probability that in a random sample of 5 newborns we have two boys and then three girls, like, for example, this: BBGGG. There are, of course, many other ways in which there can be two boys in a sample of five, for example GGGBB.</p>
<p>To solve the problem using probability theory we must first find all the possible ways two boys and three girls can occur, compute the chance of each and then use the addition rule to add up the chances. Let us skip the complicated task of finding all the possible ways and concentrate on the second task first.</p>
<p>The chance of a pattern BBGGG is: <span class="math inline">\(0.513 \times 0.513 \times 0.487 \times 0.487 \times 0.487 = (0.513)^2 \times
(0.487)^3\)</span>. This follows from the multiplication rule as well as from the assumption of independence. Similarly the chance of GGGBB would compute as: <span class="math inline">\(0.487 \times 0.487 \times 0.487 \times 0.513 \times 0.513 =
(0.487)^3 \times (0.513)^2\)</span>, so exactly the same chance.</p>
<p>Now, how many patterns are there? The number of patterns is given by the <strong>binomial coefficient</strong>: <span class="math display">\[\begin{equation*}
\frac{5 \times 4 \times 3 \times 2 \times 1}
{(2 \times 1) \times (3 \times 2 \times 1)} = 10
\end{equation*}\]</span> There are 10 different patterns of 2 boys and three girls, so the chance is: <span class="math inline">\(10 \times (0.513)^2 \times (0.487)^3\)</span>, or roughly 30 %.</p>
<p>Binomial coefficientas look messy and so mathematicians have invented a cleaner notation using an exclamation mark ! as a special symbol to indicate the result of multiplying together a number and all the numbers which come before it. For example <span class="math display">\[\begin{eqnarray*}
1! &amp;=&amp; 1\\
2! &amp;=&amp; 2 \times 1 = 2 \\
3! &amp;=&amp; 3 \times 2 \times 1 =  6 \\
4! &amp;=&amp; 4 \times 3 \times 2 \times 1  =  24
\end{eqnarray*}\]</span> The exclamation mark reads <strong>factorial</strong> and sure enough there is an R function for it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">factorial</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<section id="the-binomial-distribution" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="the-binomial-distribution"><span class="header-section-number">10.1.1</span> The binomial distribution</h3>
<p>All these arguments and reasoning can be packed into a formula giving the chance that an event will occur exactly <span class="math inline">\(k\)</span> times out of <span class="math inline">\(n\)</span>. This is</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Binomial Formula
</div>
</div>
<div class="callout-body-container callout-body">
<p>The chance that an event <span class="math inline">\(X\)</span> will occur exactly <span class="math inline">\(k\)</span> times out of <span class="math inline">\(n\)</span> is given by the <strong>binomial formula</strong> <span class="math display">\[\begin{equation}
P(X = k) = \frac{n!}{k!(n-k)!}p^k(1-p)^{n-k}
\end{equation}\]</span></p>
<p>In this formula, <span class="math inline">\(n\)</span> is the number of trials, <span class="math inline">\(k\)</span> is the number of times the event is to occur, an <span class="math inline">\(p\)</span> is the probability that the event will occur on any particular trial.</p>
<p>Mathematicians often use a particular notation for the binomial coefficient in this formula, so the formula looks like: <span class="math display">\[\begin{equation}
P(X = k) = \binom{n}{k}p^k(1-p)^{n-k}
\end{equation}\]</span> where <span class="math inline">\(\binom{n}{k}\)</span> denotes the binomial coefficient.</p>
<p>The assumptions are:</p>
<ul>
<li>The value of <span class="math inline">\(n\)</span> must be fixed in advance</li>
<li><span class="math inline">\(p\)</span> must be the same for each trial</li>
<li>The trials must be independent</li>
</ul>
</div>
</div>
<p>R has a built in function for the binomial formula and we can use it for probability computations where it is involved. This function is called <code>dbinom()</code> and is to be used like this:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Binomial Formula in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>The chance that an event will occur exactly <span class="math inline">\(k\)</span> times out of <span class="math inline">\(n\)</span> is given by the <strong>binomial formula</strong> implemented in R as</p>
<pre><code>dbinom(x,          # X-axis values (x = 0, 1, 2, ..., n)
       
       size,        # Number of trials (n &gt; = 0)
       
       prob,        # The probability of success on each trial
       
       log = FALSE) # If TRUE, probabilities are given as log</code></pre>
</div>
</div>
<p>Let us demonstrate its use this to work out the theoretical probabilities for the proportion of girls in a sample of 10 as in the example in our picture where we had a proportion of 0.5 for girls and 0.5 for boys in the sample. We show here the probabilties for all possible cases (0, 1, 2, 3, 4, 5, 6, 7, 8, 9 or 10 girls).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">dbinom</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="dv">10</span>, <span class="fl">0.487</span>), </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">names.arg =</span> <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">10</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Probability distribution: Sample size 10"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s check your understanding of the formula: Denote the event that a randomly chosen newborn will be a girl by <span class="math inline">\(X\)</span>. According to the binomial formula the probability that in a sample of 10 newborns we will have, say four girls, given the probability that a baby is a girl of <span class="math inline">\(0.487\)</span> is:</p>
<p><span class="math display">\[\begin{eqnarray*}
P(X = 2) &amp;=&amp; \binom{10}{4} \times 0.487^4 \times (1-0.487)^{(10-4)} \\
         &amp;=&amp; \frac{10!}{4!(10-4)!} \times 0.487^4 \times (1-0.487)^{(10-4)} \\
         &amp;=&amp; \frac{10 \times 9 \times 8 \times 7 \times 6 \times 5 \times 4\times 3\times 2\times 1}{( 4 \times 3\times 2 \times 1) ( 6 \times 5 \times 4 \times 3 \times 2 \times 1)} \times 0.487^4 \times (1-0.487)^{(5-2)} \\
         &amp;=&amp; 0.2152977
\end{eqnarray*}\]</span></p>
<p>This is what we get if we do the computation by hand and using pencil and paper. When we use R we should get the same result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">4</span>,<span class="dv">10</span>,<span class="fl">0.487</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2152977</code></pre>
</div>
</div>
<p>Now look at the barplot: If we have 4 girls out of 10 the proportion of girls in the sample would be <span class="math inline">\(4/10\)</span> or <span class="math inline">\(0.4\)</span>. The theoretical probability for this proportion would be about <span class="math inline">\(0.22\)</span>. This is exactly what you see in the barplot.</p>
<p>For the plot we have computed these probabilities and proportions for all constellations 0, 1, 2, 3, 4 up to 10 girls. We have created this sequence with the R <code>seq()</code> function. For the <code>names.arg</code> argument we have created the same sequence but divided every element of the sequence by 10 to express the number as a proportion and then transformed the numbers to a vector of type character by the <code>as.character()</code> function, since <code>names.arg</code> requires a vector of characters.</p>
<p>I think by now you understand how we apply the formula both in math and in R to figure out the probabilities. Here we do the same exercise for <span class="math inline">\(n= 100\)</span> and <span class="math inline">\(n=1000\)</span>. We do not show the code anymore her just the plots (try it!):</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">dbinom</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="dv">100</span>, <span class="fl">0.487</span>), <span class="at">names.arg =</span> <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">100</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Sample size 100"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">dbinom</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="dv">1000</span>, <span class="fl">0.487</span>), <span class="at">names.arg =</span> <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">1000</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Sample size 1000"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When we draw random samples, like in this example drawing babies from a population of newborns, then the chance process of random sampling delivers a number and then another and then another and so on, in the specific example, 1 for a girl and 0 for a boy.</p>
<p>Mathematicians call the value around which these number vary the <strong>expected value</strong>, and the average size of how much the numbers are off the the expected value the <strong>standard error</strong>. The formulas for the expected value and the standard error depend on the chance process which generates the numbers.</p>
<p>The figures above have two notable features.</p>
<ol type="1">
<li><p>The probability distribution for the proportion tends to become regular, symmetric and bell shaped, like a normal curve. This is something we already observed when we discussed the bootstrap.</p></li>
<li><p>The distribution gets tighter as the sample size increases.</p></li>
</ol>
<p>But before we discuss these ideas and their implications further, let us unpack the notions of expected value and standard error a bit more.</p>
</section>
<section id="expected-value" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="expected-value"><span class="header-section-number">10.1.2</span> Expected value</h3>
<p>The formula for the expected value depends on the chance process which generates the random numbers. Let us introduce the general formulas by another box model example.</p>
<p>Suppose we make hundred random draws with replacement from the box, containing the following tickets, symbolized by an R vector called <code>box</code> and the draws symbolized by an R vector called <code>draws</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>draws <span class="ot">&lt;-</span> <span class="fu">sample</span>(box, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>About how large should this sum be? The draws could turn out either 0, 2, 3, 4, or 6. Each outcome has a probability of 1/5, so they should come up around 1/5th of the draws. So in 100 draws we should see:</p>
<p><span class="math display">\[\begin{equation}
20 \times 0 + 20 \times 2 + 20 \times 3 + 20 \times 4 + 20 \times 6 = 300
\end{equation}\]</span></p>
<p>This is called the <strong>expected value</strong>.</p>
<p>The formula has two ingredients:</p>
<ol type="1">
<li>The number of draws</li>
<li>The average of the numbers of the tickets in the box.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Expected value for the sum of random draws from a box
</div>
</div>
<div class="callout-body-container callout-body">
<p>The expected value for the sum of draws made at random with replacement from a box equals</p>
<p><span class="math display">\[\begin{equation}
(\text{number of draws}) \times (\text{average of box})
\end{equation}\]</span></p>
</div>
</div>
<p>The logic here is that the average of the box amounts to <span class="math display">\[\begin{equation}
\frac{0+2+3+4+6}{5} = 15/5 = 3
\end{equation}\]</span> On average each draw adds around 3 to the sum. With 100 draws then the sum must be around <span class="math inline">\(100 \times 3 = 300\)</span>.</p>
<p>See what we have in our actual random draws:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(draws)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 328</code></pre>
</div>
</div>
<p>pretty close.</p>
</section>
<section id="standard-error" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="standard-error"><span class="header-section-number">10.1.3</span> Standard error</h3>
<p>We have seen before that the expected value of the sum of the tickets in the box is <span class="math inline">\(300\)</span>. The actual outcome of the random process was, however, 328, which is 28 off the expected value.</p>
<p>This is a chance error. The sum will be off the expected value by the size of a chance error, so that:</p>
<p><span class="math display">\[\begin{equation}
\text{sum} = \text{expected value} + \text{chance error}
\end{equation}\]</span></p>
<p>How big is this chance error likely to be?</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Likely size of chance error
</div>
</div>
<div class="callout-body-container callout-body">
<p>The sum is likely to be around its expected value but to be off by a chance error similar in size to the standard error.</p>
</div>
</div>
<p>There is also a formula to use when we compute the standard error for a sum of draws made at random from a box with replacement. This formula plays a key role in the statistical procedures we discuss in this and in the next unit.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Square root law
</div>
</div>
<div class="callout-body-container callout-body">
<p>When drawing at random with replacement form a box of numbered tickets, the standard error for the sum of the draws is <span class="math display">\[\begin{equation}
\sqrt{\text{number of draws}} \times (\text{standard deviation of box})
\end{equation}\]</span></p>
</div>
</div>
<p>This formula has two ingredients:</p>
<ol type="1">
<li>The square root of the number of draws.</li>
<li>The standard deviation of the list of numbers in the box.</li>
</ol>
<p>If there is a lot of spread in the box, the standard deviation is big and it is hard to predict how the draws will turn out. So the standard error must be big too.</p>
<p>The sum of two draws has more variability than one draw. The sum of 100 draws is still more variable. As the number of draws grows the sum gets harder to predict, the chance error gets bigger and so does the standard error. However the standard error goes up slowly with a factor equal to the square root of the number of draws. With 100 draws, therefore the sum is 10 times more variable than with a single draw.</p>
<p>Note that the standard deviation and the standard error are two different concepts:</p>
<p>The standard deviation is for the list of numbers in the box, in our example <span class="math inline">\(0,2,3,4, 6\)</span>. This is 2</p>
<p>The standard error refers to the outcome of the chance process, in our case drawing at random from the box of numbers. This is for our particular example 20</p>
<p>A statistics, like the mean or a proportion, when viewed as a random variable has a standard error. This is to distinguish from the standard deviation of the population distribution from which this statistics derives.</p>
<p>We began our discussion with 100 random draws with replacement from the box</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The expected value of the sum is 300. The sum will be around 300 but will be off by a chance error. The average in the box is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(box)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>and the standard deviation is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>( ((<span class="dv">0-3</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="dv">2-3</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span> (<span class="dv">3-3</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="dv">4-3</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="dv">6-3</span>)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>This measures the variability in our box. According to the square root law the sum of 100 draws is <span class="math inline">\(\sqrt{100} = 10\)</span> times more variable. The standard error (SE) of the sum is the <span class="math inline">\(10 \times 2\)</span> or <span class="math inline">\(20\)</span>. The likely chance error is about 20. The sum of draws should be around 200 give or take 20.</p>
<p>Let us use the compute again to show what this means empirically. When we asked the computer to draw 100 times with replacement from the box we got a list of successive draws, which we could visualize as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">split</span>(draws, <span class="fu">ceiling</span>(<span class="fu">seq_along</span>(draws)<span class="sc">/</span><span class="dv">5</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind, res))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Element 1"</span>, <span class="st">"Element 2"</span>, <span class="st">"Element 3"</span>, <span class="st">"Element 4"</span>, <span class="st">"Element 5"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(df) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(df[ , <span class="fu">c</span>(<span class="st">"Element 1"</span>, <span class="st">"Element 2"</span>, <span class="st">"Element 3"</span>, <span class="st">"Element 4"</span>, <span class="st">"Element 5"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Element 1</th>
<th style="text-align: right;">Element 2</th>
<th style="text-align: right;">Element 3</th>
<th style="text-align: right;">Element 4</th>
<th style="text-align: right;">Element 5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The sum of these draws is 328, this is 28 off the expected value.</p>
<p>Now if we do such an experiment 100 times, we get something like the following table. I don’t show the code but you can try to refresh your knowledge of writing a loop here.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>repetitions <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="dv">100</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)){</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  repetitions[[i]] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sample</span>(box, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># perpeare a table</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">split</span>(repetitions, <span class="fu">ceiling</span>(<span class="fu">seq_along</span>(repetitions)<span class="sc">/</span><span class="dv">20</span>))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>aux <span class="ot">&lt;-</span> <span class="fu">lapply</span>(out, unlist) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Round =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="at">Sum =</span> aux[,<span class="dv">1</span>], <span class="at">Round =</span> <span class="dv">21</span><span class="sc">:</span><span class="dv">40</span>, <span class="at">Sum =</span> aux[, <span class="dv">2</span>], <span class="at">Round =</span> <span class="dv">41</span><span class="sc">:</span><span class="dv">60</span>, <span class="at">Sum =</span> aux[, <span class="dv">3</span>], <span class="at">Round =</span> <span class="dv">61</span><span class="sc">:</span><span class="dv">80</span>, <span class="at">Sum =</span> aux[, <span class="dv">4</span>], <span class="at">Round =</span> <span class="dv">81</span><span class="sc">:</span><span class="dv">100</span>, <span class="at">Sum =</span> aux[,<span class="dv">5</span>])</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(df, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Round"</span>, <span class="st">"Sum"</span>, </span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Round"</span>, <span class="st">"Sum"</span>, </span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Round"</span>, <span class="st">"Sum"</span>, </span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Round"</span>, <span class="st">"Sum"</span>,</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Round"</span>, <span class="st">"Sum"</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Round</th>
<th style="text-align: right;">Sum</th>
<th style="text-align: right;">Round</th>
<th style="text-align: right;">Sum</th>
<th style="text-align: right;">Round</th>
<th style="text-align: right;">Sum</th>
<th style="text-align: right;">Round</th>
<th style="text-align: right;">Sum</th>
<th style="text-align: right;">Round</th>
<th style="text-align: right;">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">338</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">261</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">294</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">338</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">365</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">321</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">288</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">306</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">268</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">246</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">303</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">282</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">321</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">350</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">286</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">285</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">323</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">322</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">316</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">283</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">307</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">280</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">301</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">306</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">305</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">296</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">324</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">265</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">305</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">306</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">302</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">332</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">302</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">334</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">286</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">323</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">288</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">322</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">335</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">337</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">282</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">297</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">329</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">296</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">273</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">325</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">268</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">293</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The observed values in this table have a remarkably low spread around the expected value of 300. It is rare that they are more than 2 or three standard errors away from the expected value. In principle they could be as small as 0 and as large as 600 but most of them are between 2.5 standard errors, actually:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">unlist</span>(repetitions) <span class="sc">&lt;=</span> (<span class="dv">300</span> <span class="sc">+</span> <span class="dv">20</span><span class="sc">*</span><span class="fl">2.5</span>) <span class="sc">&amp;</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">unlist</span>(repetitions) <span class="sc">&gt;=</span> (<span class="dv">300</span> <span class="sc">-</span> <span class="dv">20</span><span class="sc">*</span><span class="fl">2.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>98 % are within these bounds.</p>
</section>
<section id="using-the-normal-curve-when-the-number-of-draws-is-large" class="level3 page-columns page-full" data-number="10.1.4">
<h3 data-number="10.1.4" class="anchored" data-anchor-id="using-the-normal-curve-when-the-number-of-draws-is-large"><span class="header-section-number">10.1.4</span> Using the normal curve when the number of draws is large</h3>
<p>When we make a large number of draws at random with replacement what is the chance that the values of the sum are within a given range ? Historically mathematicians detected the normal curve while working out problems of this kind. Let’s keep the logic of why the normal curve comes into play with a large number of draws aside for the moment and briefly discuss how it works.</p>
<p>Think about our box from before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we tell the computer to repeatedly sample from this box with replacement and take the sum, he prints or stores the result over and over again. What percentage of numbers should be between 270 and 330?</p>
<p>Note that each sum will be somewhere between 0 and <span class="math inline">\(100 \times 6\)</span> or 600. Let us assume we want to know the chance that the sum is somewhere between 270 and 330. Here is a picture. We convert first to standard units and then use the normal curve. <img src="pictures/range_of_sum_with_curve.png" class="img-fluid" alt="Probability of sum between 150 and 360 in a large sample"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.5</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8663856</code></pre>
</div>
</div>
<p>Let’s check with the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">unlist</span>(repetitions) <span class="sc">&lt;=</span> (<span class="dv">300</span> <span class="sc">+</span> <span class="dv">30</span>) <span class="sc">&amp;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">unlist</span>(repetitions) <span class="sc">&gt;=</span> (<span class="dv">300</span> <span class="sc">-</span> <span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is 0.85. A pretty good approximation.</p>
<p>Why do we need a conversion to standard units? Here we could also use the normal distribution with mean 300 and standard deviation 30 to derive the same result. To see this, consider:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">330</span>, <span class="at">mean =</span> <span class="dv">300</span>, <span class="at">sd =</span> <span class="dv">20</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">270</span>, <span class="at">mean =</span> <span class="dv">300</span>, <span class="at">sd =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8663856</code></pre>
</div>
</div>
<p>Same result. The probability does not depend on the units in which the variables are measured. There is an infinity of normal distributions for each different pair of means and standard deviations. For the computer this is no problem to handle, so in the computer age in some cases we do not need to convert to standard units.</p>
<p>However before the age of computers probabilities of the normal distribution were printed in tables, for the standard normal distributions and you had to use the table to compute probabilities for intervals of normally distributed random variables. Such a table looks like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/standard_normal_table.png" class="img-fluid figure-img"></p>
<figcaption>Probability table of the standard normal distribution</figcaption>
</figure>
</div>
<p>The value in the table correspond to the area under the normal curve above a certain value <span class="math inline">\(z\)</span>. So how do we read the table for our computation? The area above <span class="math inline">\(z = 1.5\)</span> is 0.0668 (table row 16). The area above 0 is by the symmetry of the normal curve 0.5. Hence the area between 0 and 1.5 must be 0.4332 and by symmetry again, the area above -1.5 and below 0 must then by twice this amount which gives 0.8664, which is the same answer than we got from the computer.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;There are other scenarios where standardization is useful even if we have access to a computer. One is when we compare variables with different normal distributions relative to each other. One example would be, when the grades of the astronomy course and the grades of the statistics course are normally distributed but with different means and standard deviations. Then to compare the scores you need to standardize. For instance, suppose a student is scoring 60 in Astronomy with the mean score of the class being 40, and scoring 65 at statistics with the mean score of the class being 80. Given the “raw” scores, one would say that the student performed better in statistics than in astronomy. However, taking into consideration the peers, it is clear that the student performed relatively better in astronomy than in statistics. Furthermore z-scores also allow to compare variables that would be impossible to compare otherwise because they have different units. Say you would like to know whether somebody is more extreme in terms of salary than in terms of running speed, then there would be no way to know this except when you standardize or use z-scores. This would then tell you how far this individual is above or below average in both aspects.</p></div></div><div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Where are the missing girls?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Finding standard errors can be computationally intensive, especially for large samples. If the random variable can have only two values, like in the example of boys and girls, there is a short cut.</p>
<p>Assume we interpret a random device which shows a number 1 as indicating a girl and 0 indicating a boy, with the probability of 1 given by 0.487. Then we can use a short cut.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>When a list has two different numbers the standard deviation equals: <span class="math display">\[\begin{equation}
\left(\text{bigger number} - \text{smaller number}) \right) \times \sqrt{\text{share of bigger number}
\times \text{share of smaller number}}
\end{equation}\]</span></p>
</div>
</div>
<p>Say, our box is like before with the baby girls and baby boys. Again, we might think of a box consisting of two values and the probability that a newborn baby will be a girl is 0.487. Then a list of 1000 babies will be a list of binomial random variables, which we can simulate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"girl"</span>, <span class="st">"boy"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> <span class="fu">sample</span>(box, <span class="dv">1000</span>, <span class="at">replace =</span> T, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.487</span>, <span class="fl">0.513</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we encode the event girl as 1 and the event boy as 0, then the standard deviation of the list must be according to our short cut formula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1-0</span>)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="fu">mean</span>(outcome <span class="sc">==</span> <span class="st">"girl"</span>)<span class="sc">*</span><span class="fu">mean</span>(outcome <span class="sc">==</span> <span class="st">"boy"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4993746</code></pre>
</div>
</div>
<p>With this insight we can treat the binomial case exactly like the box case. All we have to do is to mark the tickets in the box, in our case the girls and boys, write 1 on the tickets that you count and 0 on the others and then your expected value of a sum of n tosses will be:</p>
<p><span class="math display">\[\begin{eqnarray}
\text{expected value}&amp;=&amp; \text{number of draws} \times \text{share of} \, 1.\\
\text{standard error}&amp;=&amp; \sqrt{\text{number of draws}} \times \sqrt{\text{share of 1}\times \text{share of 0}}
\end{eqnarray}\]</span> This means that in our case of 100 draws the expected value of girls will be <span class="math inline">\(1000 \times 0.487 = 487\)</span> with a standard error of <span class="math inline">\(\sqrt{1000}\times \sqrt{0.487 \times 0.513} = 15.8\)</span> or about 16.</p>
<p>Look at the number from the simulation:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(outcome <span class="sc">==</span> <span class="st">"girl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.475</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">sqrt</span>( <span class="fu">mean</span>(outcome <span class="sc">==</span> <span class="st">"girl"</span>)<span class="sc">*</span>(<span class="fu">mean</span>(outcome <span class="sc">==</span> <span class="st">"boy"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.79161</code></pre>
</div>
</div>
<p>This is very good. Now for computing probabilities also here we can - for large enough samples - use the normal approximation. Say, we would like to know what is the probability that we would observe a share of girls between 0.4 and 0.5?</p>
<p>With the computer the exact computation is easy, because all the formulas we need are implemented. We just add up all the binomial probabilities from 0 to 500 and add up from 0 to 400 and take the difference:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">500</span>, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">prob =</span> <span class="fl">0.487</span>)) <span class="sc">-</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">400</span>, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">prob =</span> <span class="fl">0.487</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8034914</code></pre>
</div>
</div>
<p>Using the normal approximation with mean 487 and standard error 15.8, let us convert to z scores, to get <span class="math inline">\((400 - 487)/15.8 = -5.5\)</span> and <span class="math inline">\((500 - 487)/15.8 = 0.82\)</span> in standard units. Thus we get</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.82</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">5.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7938919</code></pre>
</div>
</div>
<p>which is a stunningly close approximation.</p>
<p>Such statistical regularities can sometimes bring insight into social processes. For example with the natural probabilities that a baby will be a girl with 0.487 and a boy with 0.513 the sex ratio at birth should be expected to be <span class="math inline">\(0.513/0.487 = 1.053\)</span>. India, in contrast hat a sex ratio at birth of 1.063.</p>
<p>The number of life births in 2022 in India was according to the demographic data of the US Census international database 23.377.786. With the natural probabilities we expect for such a population 11.384.982 baby girls in this cohort of 2022 babies with a standard error of <span class="math inline">\(\sqrt{23377786 \times 0.487 \times 0.513} = 2417\)</span>. Thus using the normal approximation the ratio would be with 95 % probability within the interval <span class="math inline">\([11.384.982 - 2 \times 2417 , 11.384.982 + 2 \times 2417]\)</span>, or within <span class="math inline">\([0.4868, 0.4872]\)</span>. With a ratio of boys to girls of 1.063 the share of girls would be 0.4847. This proportion is more than two standard deviations lower compared to what would be expected based on the natural probabilities of 0.487 and 0.513. There is a debate among demographers whether this discrepancy in girl births might be due to infanticide of selective abortion of female fetuses.</p>
</div>
</div>
</section>
<section id="the-central-limit-theorem-and-probability-histograms" class="level3 page-columns page-full" data-number="10.1.5">
<h3 data-number="10.1.5" class="anchored" data-anchor-id="the-central-limit-theorem-and-probability-histograms"><span class="header-section-number">10.1.5</span> The central limit theorem and probability histograms</h3>
<p>When we get numbers from a chance process, the expected value and the standard error give us an impression where the numbers will be. If we want to get the full picture, however, we get it from a <strong>probability histogram</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Probability histogram
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>A probability histogram represents probabilities, not data.</p></li>
<li><p>A probability histogram represents chance by area.</p></li>
</ul>
</div>
</div>
<p>Here is an example from gambling:</p>
<p>Craps is a casino game where you throw two dice and gamblers bet on the sum of numbers the two dice will show. We can find the chances of the combinations by probability theory (try it). But here we will simulate using concepts we already know and learend in this course. We write a function tossing two dice and sum up their outcomes and repeat this many times and plot the outome (try it)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>craps <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># construct a die</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># roll twice</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">sample</span>(die, <span class="dv">2</span>, <span class="at">replace =</span> T)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># sum the outcome of the rolls</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(out)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>crap_sim <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">craps</span>())</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co">#hist(crap_sim, breaks = seq(1.5, 12.5, by = 1), freq = F, plot = F)</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>h100 <span class="ot">&lt;-</span> <span class="fu">hist</span>(crap_sim, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="fl">12.5</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="at">plot =</span> F)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>h100<span class="sc">$</span>counts <span class="ot">&lt;-</span> h100<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h100<span class="sc">$</span>counts)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h100,</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of dots"</span>,</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent"</span>,</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"One Hundered Repetitions"</span>,</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F,</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">13</span>),</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.3</span>))</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">labels =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>)</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>,<span class="st">"10 %"</span>, <span class="st">"20 %"</span>, <span class="st">"30 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now increase the repetitions to 1000</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>crap_sim <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">craps</span>())</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#hist(crap_sim, breaks = seq(1.5, 12.5, by = 1), freq = F, plot = F)</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>h1000 <span class="ot">&lt;-</span> <span class="fu">hist</span>(crap_sim, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="fl">12.5</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="at">plot =</span> F)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>h1000<span class="sc">$</span>counts <span class="ot">&lt;-</span> h1000<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h1000<span class="sc">$</span>counts)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h1000,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of dots"</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"One Thousand Repetitions"</span>,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">13</span>),</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.3</span>))</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">labels =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>)</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>,<span class="st">"10 %"</span>, <span class="st">"20 %"</span>, <span class="st">"30 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And to 10000</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>crap_sim <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">craps</span>())</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#hist(crap_sim, breaks = seq(1.5, 12.5, by = 1), freq = F, plot = F)</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>h10000 <span class="ot">&lt;-</span> <span class="fu">hist</span>(crap_sim, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="fl">12.5</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="at">plot =</span> F)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>h10000<span class="sc">$</span>counts <span class="ot">&lt;-</span> h10000<span class="sc">$</span>counts<span class="sc">/</span><span class="fu">sum</span>(h10000<span class="sc">$</span>counts)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h10000,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of dots"</span>,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Percent"</span>,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Ten Thousand Repetitions"</span>,</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> F,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">13</span>),</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.3</span>))</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="co"># add labels below each column</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">labels =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 %"</span>,<span class="st">"10 %"</span>, <span class="st">"20 %"</span>, <span class="st">"30 %"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can see that the probability histograms observed from the random experiments of throwing the two dice 100, 1000 and 10000 times get closer and closer to the ideal probability histogram, where the relative frequency of events from the random experiment come arbitrarily close to the theoretical probabilities.</p>
<p>There are 6 events in 36 where the sum of the die could be 7 (try to convince yourself!). This is 16 2/3 %. The area of the rectangle over 7 in the probability histogram, therefore equals 16.3%. The total area of all the rectangles sum up to 100 %.</p>
<p>When we discussed the theoretical share of baby girls using the binomial distribution, we saw a remarkable fact:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">dbinom</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="dv">100</span>, <span class="fl">0.487</span>), <span class="at">names.arg =</span> <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">100</span>),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Sample size 100"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">dbinom</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="dv">1000</span>, <span class="fl">0.487</span>), <span class="at">names.arg =</span> <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">1000</span>),</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Sample size 1000"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Proportion of girls"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We saw in this example that the variability of the observed proportion gets smaller as the sample size increases. Here the same mechanisms are at work as in the example of craps.</p>
<p>These mechanisms have been first systematically described by is the classic Jacob Bernoulli in the 17th century and the result is termed the <strong>law of large numbers</strong> or the law of averages.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;Jacob Bernoulli, 6 January 1655 – 16 August 1705,was one of the many prominent mathematicians in the Swiss Bernoulli family. <img src="pictures/Jakob_Bernoulli.jpg" class="img-fluid" alt="Jacon Bernoulli"> He sided with Gottfried Wilhelm Leibniz during the Leibniz–Newton calculus controversy and was an early proponent of Leibnizian calculus, which he made numerous contributions to; along with his brother Johann, he was one of the founders of the calculus of variations. He also discovered the fundamental mathematical constant e. However, his most important contribution was in the field of probability, where he derived the first version of the law of large numbers in his work Ars Conjectandi.[3]</p></div></div><p>The manifestation of this law here is that when we increase the sample, the proportion of girls in the outcome of the random experiment comes closer and closer to the true proportion of 0.487.</p>
<p>In the previous section we discussed the normal approximation when the sample size is large enough. This is also the content of the famous <strong>central limit theorem</strong> detected in 1733 by Abraham de Moivre. This theorem says:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Central limit theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p>When drawing at random with replacement from a box, the probability histogram for the sum will follow the normal curve, even is the contents of the box is not normally distributed, provided the number of draws is large enough.</p>
</div>
</div>
<p>This is a remarkable fact. Whatever the the shape of the population distribution from which each of the original measurements were sampled, for large sample sizes their average can be considered as drawn from a normal curve. This will have a mean that is equal to the mean of the original distribution the standard deviation that has a simple relationship to the standard deviation of the original population It is known, as we discussed before, as the standard error.</p>
<p>Note that the central limit theorem applies to sums but not to other operations, like products. The central limit theorem is the basis for many statistical procedures we discuss in the rest of the units.</p>
<p>How many draws will be needed before we can be confident that we may apply the approximation? There is no general rule. It depends on what is in the box but for most boxes 100 draws will already get sufficienty close.</p>
<p>When a probability histogram follows a normal curve, it can be approximated by the expected value and the standard error.</p>
<p>According to the square root law the expected value and the standard error for a sum can be computed from:</p>
<ul>
<li>the number of draws</li>
<li>the average of the box</li>
<li>the standard error of the box</li>
</ul>
<p>These are the three quantities which determine the behavior of the sum. This is why the standard error of the box is such an important measure of its spread.</p>
<p>Now we see also why in the bootstrap examples we discussed in unit 5, the distribution of the statistics we got from repeated resamples looked more and more like a normal distribution. This is the consequence of the central limit theorem.</p>
<p>This applies also for proportions, because by appropriate labeling of the outcomes a count of proportions can be understood as the means of a binary variable with values 0 and 1.</p>
</section>
</section>
<section id="working-out-the-accuracy-of-estimates" class="level2 page-columns page-full" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="working-out-the-accuracy-of-estimates"><span class="header-section-number">10.2</span> Working out the accuracy of estimates</h2>
<p>While the central limit theorem is a remarkable and extraordinary law of nature, the question arises, how this law can help us work out the accuracy of estimates without using the heavy machinery of computer simulation.</p>
<p>We have gone a long way now to discuss how we come from a given probability distribution to the probability of outcomes. We now are ready to discuss the second question, which is the usual situation in statistical practice. We have a single sample and need to say saying something about an underlying population. This is the process of inductive inference, we discussed in unit 3.</p>
<section id="the-accuracy-of-percentages" class="level3 page-columns page-full" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="the-accuracy-of-percentages"><span class="header-section-number">10.2.1</span> The accuracy of percentages</h3>
<p>Let us now turn the situation around and do not reason from the box to the draws but take the other perspective and reason from the draws to the box. The technique belongs to the key ideas of statistics and we develop it here in a context of polling.</p>
<p>Suppose a vote between two political parties comes up and you want to find out an estimate of the percentage of votes for one of two parties, A and B. Say you were able to draw a random sample from the eligible voters in the district and all have responded truthfully<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Say you have taken a sample of 2500 voters, and in the there are 1328 voters in favor party A. The percentage is: <span class="math display">\[\begin{equation}
\frac{1328}{2500} \times 100 \% \approx 53 \%
\end{equation}\]</span> You have taken the data of the sample to make an estimate but how far wrong this estimate is likely to be? With a box model in mind, you might think of the following procedure. Each respondent with a stated preference for party A is represented as a ticket with a 1 written on it and the others with a ticket with a 0 written on it. The standard error of the box for the sum should be <span class="math display">\[\begin{equation}
\sqrt{\text{(share of}\, 1's) \times (\text{share of} 0's)}
\end{equation}\]</span> But now you are stuck, because you don’t know how the tickets in the box (in the population of voters in the district ) are marked.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;Of course this is not a realistic scenario in polling. You will have non-responses and people not telling the truth and in practice you have to find methods and ways to deal with all of these aspects. The key principles can, however, be explained also in this idealized and simplified case</p></div></div><p>Survey organisations lift themselves out of the dilemma, very much like we did in unit 5, when we learned about the bootstrap. They substitute the fractions observed in the sample for the unknown fractions in the box. For example, there were 1328/2500 or 0.53 in the sample in favor of party A and the rest of 0.47 was opposed. On this basis lets estimate the standard deviation of the box as <span class="math inline">\(\sqrt{0.53 \times 0.47}\)</span> which is about 0.5. With this assumption the standard error for the voters in the sample is <span class="math inline">\(\sqrt{2500} \times 0.5\)</span> which is 25, which is 1 % in terms of the sample size. The estimate is according to this calculation off by about 1 percentage point.</p>
</section>
<section id="confidendence-intervals" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="confidendence-intervals"><span class="header-section-number">10.2.2</span> Confidendence intervals</h3>
<p>In the previous example of polling, the voter share for party A was estimated 53 % with a standard error of 1 %. So the population percentage could by 52 %. The population percentage could also be 54 %. The population percentage could also be 49 % corresponding to a chance error of 4 %. This is already unlikely because 4 % represent 4 standard deviations. But theoretically the population percentage could even be smaller than that.</p>
<p>With chance error there is no sharp line between possible and impossible. Errors with 4 standard deviations do occur but very infrequently. What happens, if we set the cutoff at 2 standard deviations? Take the interval from s standard errors above and below the sample percentage:</p>
<p><img src="pictures/confidence_interval.png" class="img-fluid" alt="Confidence Interval"> This is called a <strong>confidence interval</strong> for the population percentage, with a confidence level of about 95 %. You can be 95 % confident that the population percentage will be inside the interval <span class="math inline">\([53 \%, 54 \%]\)</span>. You can have other confidence intervals. Anything except 100 % is possible.</p>
<p>What, if you want different confidence levels? Anything except 100 % is allowed by going the appropriate number of standard errors right and left from the expected value. For example:</p>
<ol type="1">
<li><p>The interval “sample percentage” plus/minus 1 stndard error is an 68 % confidence interval for the population percentage.</p></li>
<li><p>The interval “sample percentage” of plus/minus 2 standard errors is a 95 % confidence interval fro the population percentage.</p></li>
<li><p>The interval “sample percentage” of plus minus 3 standard errors is a 99.7 confidence interval for the population percentage.</p></li>
</ol>
<p>You can go on but even 10 standard deviations may not give you 100 % confidence, because for any interval you take, the normal curve always has some area (if very very small) outside of it.</p>
<p>How can we interpret a confidence interval? Often yo will hear people saying: “there is a 95 % chance that the population percentage is between 52 and 54 %. But this is misleading. The chance represents the number of times something will happen. No matter how many time you poll the voters, the share will not change.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Keep in mind
</div>
</div>
<div class="callout-body-container callout-body">
<p>The chances are in the sampling procedure, not in the parameter.</p>
</div>
</div>
<p>First of all, notice that the confidence interval depends on the sample. If the sample had come out differently, the confidence interval would be different. With some samples the confidence interval contains the population percentage and with others perhaps not. The confidence level of 95 % then means that for 95 % of all samples the confidence interval will contain the true population percentage, and for the other 5 % it will not.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting a confidence interval
</div>
</div>
<div class="callout-body-container callout-body">
<p>A confidence interval is used when estimating an unknown parameter from sample data. The interval gives a range for the parameter, and a confidence level that the range covers the true value.</p>
</div>
</div>
<p>Suppose that 100 survey teams took a random sample of 10.000 newborns in a large country to estimated the share of baby girls. Unknown to the survey teams this percentage is 48.7 %. Each team computes a confidence interval for the proportion of girls, using the formula:</p>
<p><span class="math display">\[\begin{equation}
\text{percentage of girls in the sample}\,\, \substack{+ \\ -} \,\, 2 \times \text{SE}
\end{equation}\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>conf_intervals <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)){</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">4</span>, <span class="dv">1</span>, <span class="fl">0.487</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)<span class="sc">*</span><span class="dv">10000</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">10000</span><span class="sc">*</span><span class="fu">mean</span>(x)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(x)))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  conf_intervals[[i]] <span class="ot">&lt;-</span> <span class="fu">c</span>((m <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>se), (m <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>se))<span class="sc">/</span><span class="dv">10000</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot setup</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">52</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">100</span>), <span class="at">xaxt =</span> <span class="st">"n"</span>, <span class="at">yaxt =</span> <span class="st">"n"</span>, <span class="at">ylab =</span> <span class="st">"Interval Index"</span>, <span class="at">xlab =</span> <span class="st">"Percentage"</span>, <span class="at">main =</span> <span class="st">"Confidence Intervals"</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">seq</span>(<span class="dv">45</span>, <span class="dv">52</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">seq</span>(<span class="dv">45</span>, <span class="dv">52</span>, <span class="dv">1</span>), <span class="st">"%"</span>))  <span class="co"># X-axis ticks as percentages</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the confidence intervals</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(conf_intervals)) {</span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  interval <span class="ot">&lt;-</span> conf_intervals[[i]]<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segments</span>(<span class="at">x0 =</span> interval[<span class="dv">1</span>], <span class="at">y0 =</span> i, <span class="at">x1 =</span> interval[<span class="dv">2</span>], <span class="at">y1 =</span> i, <span class="at">col =</span> <span class="st">"blue"</span>)  <span class="co"># Interval line</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected value line</span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">48.7</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Correcting the y-axis and plot limits</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">las =</span> <span class="dv">1</span>)  <span class="co"># Add y-axis numbers with horizontal labels</span></span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure plot box is shown</span></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The percentage of girls is different from sample to sample and so is the estimated standard error. As a result the intervals have different centers and lengths. Some cover the percentage of 48.7 others fail to do so. About 95 % of them cover the true proportion.</p>
<p>This is of course only a computer simulation. In practice an investigator would have only one sample and would not know the parameter. A sample percentage will be off the population percentage due to chance error. The standard error tells you the likely size of being off. Confidence intervals are a concept to make this idea more quantitative.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The formulas for simple random samples do not apply to other kinds of samples!</p>
</div>
</div>
<p>The logic of the procedure depends on the square root law. When the size of the sample is small relative to the size of the population, taking a simple random sample is about the same as drawing at random with replacement from a box. This is the basic situation to which the square root law applies. At random means, that every ticket in the box has the same probability of ending up in the sample. If the sample is not taken at random, the square root law will give you wrong answers.</p>
</section>
<section id="the-accuracy-of-averages" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="the-accuracy-of-averages"><span class="header-section-number">10.2.3</span> The accuracy of averages</h3>
<p>Let us next discuss how we can use probability theory in combination with statistics to quantify the accuracy of averages. Again our leading example will be a box, with tickets numbered from 1 to 7.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s ask the computer to take 25 draws at random from this box:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>numbers <span class="ot">&lt;-</span> <span class="fu">sample</span>(box, <span class="dv">25</span>, <span class="at">replace =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and display them here:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>group_factor <span class="ot">&lt;-</span> group_factor <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">each =</span> <span class="dv">5</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">split</span>(numbers, group_factor)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind,sp))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(df, <span class="at">col.names =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The sum of these numbers is 86, so their average is 3.44. If we ask the computer to do this experiment again we get a different average: 4.84. There is chance variability in the sum of draws and thus also in the average. We want to solve the problem of computing the expected value and the standard error of this statistics.</p>
<p>The average of the box is 4 and so the average of the draws will be around 4. The standard error for the average can be worked out from the standard error of the sum. The expected value of the sum is: <span class="math display">\[\begin{equation}
\text{number of draws}\,\, \times \,\, \text{avergage of box} = 25 \times 4 = 100
\end{equation}\]</span> The standard deviation of the box is 2 and so the standard error of the sum must be: <span class="math display">\[\begin{equation}
\sqrt{\text{number of draws}}\,\, \times \,\, \text{SD of box} = \sqrt{25} \times 2 = 10
\end{equation}\]</span> The sum will be around 100 give and take about 10. For the average, this means that we have for 25 draws: <span class="math display">\[\begin{equation}
\frac{100 + 10}{25} = \frac{100}{25} + \frac{10}{25} = 4 + 0.4
\end{equation}\]</span> and on the other hand: <span class="math display">\[\begin{equation}
\frac{100 - 10}{25} = \frac{100}{25} - \frac{10}{25} = 4 - 0.4
\end{equation}\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Accuracy of averages
</div>
</div>
<div class="callout-body-container callout-body">
<p>When drawing at random from a box:</p>
<ol type="1">
<li><p>The expected value for the average of draws: Average of the box</p></li>
<li><p>The standard error of draws: <span class="math inline">\(\frac{\text{Standard error for the sum}}{\text{number of draws}}\)</span></p></li>
</ol>
</div>
</div>
<p>Here we see a picture for the sum of draws.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the vector to draw from</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>vec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of random draws and simulations</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>n_draws <span class="ot">&lt;-</span> <span class="dv">25</span>  <span class="co"># Number of draws per simulation</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">10000</span>  <span class="co"># Number of simulations</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate and compute the sum of each set of random draws</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>sample_sums <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_sims, <span class="fu">sum</span>(<span class="fu">sample</span>(vec, n_draws, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic statistics for overlaying the normal curve</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>mean_sample_sums <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_sums)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>sd_sample_sums <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample_sums)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the histogram and convert counts to percentages</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sample_sums, <span class="at">breaks =</span> <span class="dv">100</span>, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Distribution of Sample Sums"</span>, </span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">140</span>), <span class="at">xlab =</span> <span class="st">"Sum"</span>, <span class="at">ylab =</span> <span class="st">"Percentage"</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">border =</span> <span class="st">"blue"</span>, <span class="at">yaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>yvals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fu">max</span>(<span class="fu">density</span>(sample_sums)<span class="sc">$</span>y), <span class="at">length.out =</span> <span class="dv">4</span>)</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at=</span>yvals, <span class="at">labels=</span><span class="fu">paste0</span>(<span class="fu">round</span>(yvals<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>))  <span class="co"># Adjust y-axis to show percentages</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Overlay a normal distribution curve</span></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean =</span> mean_sample_sums, <span class="at">sd =</span> sd_sample_sums), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now consider the same picture for the average:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the vector to draw from</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>vec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of random draws and simulations</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>n_draws <span class="ot">&lt;-</span> <span class="dv">100</span>  <span class="co"># Number of draws per simulation</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">10000</span>  <span class="co"># Number of simulations</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate and compute the mean of each set of random draws</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_sims, <span class="fu">mean</span>(<span class="fu">sample</span>(vec, n_draws, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic statistics for overlaying the normal curve</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>mean_sample_means <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_means)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>sd_sample_means <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample_means)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the histogram and convert counts to percentages</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sample_means, <span class="at">breaks =</span> <span class="dv">100</span>, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Distribution of Sample Means"</span>, </span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">2.8</span>, <span class="fl">5.2</span>), <span class="at">xlab =</span> <span class="st">"Mean"</span>, <span class="at">ylab =</span> <span class="st">"Percentage"</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">border =</span> <span class="st">"blue"</span>, <span class="at">yaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>yvals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fu">max</span>(<span class="fu">density</span>(sample_means)<span class="sc">$</span>y), <span class="at">length.out =</span> <span class="dv">3</span>)</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at=</span>yvals, <span class="at">labels=</span><span class="fu">paste0</span>(<span class="fu">round</span>(yvals, <span class="dv">2</span>), <span class="st">"%"</span>))  <span class="co"># Adjust y-axis to show percentages</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Overlay a normal distribution curve</span></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean =</span> mean_sample_means, <span class="at">sd =</span> sd_sample_means), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="probability_and_statistics_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram of the average is described by a normal curve because the histogram of sums is described by a normal curve. The division by the number of draws is just a change of scale and we saw that probabilities do not change when we change the scale or the units.</p>
<p>Now as with the percentages before, let us see what happens if we don’t know the numbers in the box. The situation is now that a random sample is taken from a box of unknown composition. The problem is to estimate the average in the box.</p>
<p>Suppose the ministry of labor wants to know the average income of the 5 million families living in the country. A survey organisation is hired to draw a random sample of 5000 families. Assume the total annual income of the families turns out to be 2.700.000 in some monetary unit. The average income of all 5000 families is then 54000. There is a chance error in this estimate.</p>
<p>To assess the uncertainty in this statistics we need a standard error and for that a box model. There should be one ticket in the box for each family in the country. The tickets show the family income. The data we have are like 5000 draws from this box. Since 5000 is such a small fraction of 5 million, there is practically no difference between drawing with and without replacement.</p>
<p>The standard error of the sum is <span class="math inline">\(\sqrt{5000} \times \text{SD of the box}\)</span>. But the survey team does not know the SD of the box. What they can do is to estimated the SD of the sample.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Estimating the SD of a box
</div>
</div>
<div class="callout-body-container callout-body">
<p>With a simple random sample, the SD of the sample can be used to estimate the SD of the box. The estimate is good when the sample is large.</p>
</div>
</div>
<p>There are 5000 families in the sample and the SD turns out to be 43.000. The SE of the sum is then estimated as <span class="math display">\[\begin{equation}
\sqrt{5000} \times 43.000 \approx 3.040.559
\end{equation}\]</span></p>
<p>To get the SE for the average we have to divide by the number of families in the sample which gives us 608.11. Thus two standard errors either way from the sample average is then <span class="math display">\[\begin{equation}
54.000 \,\, \substack{+ \\ -} \,\, 2 \times 608.11
\end{equation}\]</span></p>
<p>Two different numbers came up in this computation: The standard deviation of the sample was 43.000 and the standard error for the average was 608. Note that these two number say two different things:</p>
<ol type="1">
<li>The standard deviation says how far family incomes are from average for typical families.</li>
<li>The standard error says how far sample averages are from the population average for typical samples.</li>
</ol>
<p>The confidence interval is about the sampling procedure. In about 95 % of all samples - since we considered two SE for a large sample - the interval will contain the true average. The average in the box is not moving around.</p>
</section>
</section>
<section id="exercises" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="exercises"><span class="header-section-number">10.3</span> Exercises:</h2>
<p>In this set of exercises you will not need the computer. A major point in the unit was to show how combining probability and statistics can help us quantify the uncertainty of a proportion or a mean in a population without a computer intensive method such as bootstrapping. You can - of course - use R and your computer if you wish to do so but all of the exercises do in principle not require the use of it. You will need a computational device to take a square root here and there, though.</p>
<section id="exercises-1" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">10.3.1</span> Exercises</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1: Rolling a die
</div>
</div>
<div class="callout-body-container callout-body">
<p>A die will be rolled 10 times. The chance it never lands such that 6 is shown can be found by one of the follwoing computations. Which one and Why?</p>
<ol type="i">
<li><p><span class="math inline">\(\left(\frac{1}{6}\right)^{10}\)</span></p></li>
<li><p>1 - <span class="math inline">\(\left(\frac{1}{6} \right)^{10}\)</span></p></li>
<li><p><span class="math inline">\(\left(\frac{5}{6} \right)^{10}\)</span></p></li>
<li><p>1 - <span class="math inline">\(\left(\frac{5}{6} \right)^{10}\)</span></p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2: Family composition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Of families with 4 children, what proportion have more girls than boys, assuming that the chance for a girl is 0.487?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 3: Expected value and standard deviation of a box
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find the expected value and the standard error for the sum of 100 draws at random with replacement from the following boxes:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/box_exercise.png" class="img-fluid figure-img"></p>
<figcaption>boxes</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 4: Find the sequence
</div>
</div>
<div class="callout-body-container callout-body">
<p>The expected value for a sum is 50, with a SE of 5. the chance process generating the sum is repeated 10 times. Which is the sequence of observed values?</p>
<ol type="a">
<li><p>51, 57, 48, 52, 57, 61, 58, 41, 53, 48</p></li>
<li><p>51, 49, 50, 52, 48, 47, 53, 50, 49, 47</p></li>
<li><p>45, 50, 55, 45, 50, 55, 45, 50, 55, 45</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 5: Assessing the probability of the magnitude of a sum
</div>
</div>
<div class="callout-body-container callout-body">
<p>One 100 draws will be made from the box [[1], [3], [3], [9]] at random with replacement.</p>
<ol type="a">
<li><p>How large can the sum be and how small can it be?</p></li>
<li><p>How likely is it that the sum is in the range from 370 to 430.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 6: The probability of girls again
</div>
</div>
<div class="callout-body-container callout-body">
<p>According to the natural probabilities the chance that the sex of a baby is determined to be a girl or a boy is as if there were random draws from the box [[Girl],[Boy]] with probabilities 0.487 and 0.513. What is the chance that the next 2500 births (ignoring twins and other multiple births) will show more than 1275 girls? (Hint: Use the table for the standard normal distribution from unit 7).</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 7: Polling
</div>
</div>
<div class="callout-body-container callout-body">
<p>A simple random sample of 1600 persons is taken to estimate the percentage of voters of one of two parties, party A, among the 25000 eligible voters in a certain town. It turns out that 917 people in the sample are voters for party A.</p>
<ol type="a">
<li><p>Find the 95 % confidence interval for the percentage of voters for party A among the 25000 eligible voters.</p></li>
<li><p>Im the example is the value of 917 expected or observed? Explain.</p></li>
<li><p>Th SD of the box is exactly equal to <span class="math inline">\(\sqrt{0.573\times 0.427}\)</span> or estimated form the data? Explain.</p></li>
<li><p>The SE for the number of voter for party A in the sampple is exactly equal to 20, or estimated from the data as 20? Explain.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 8: A student survey
</div>
</div>
<div class="callout-body-container callout-body">
<p>A university has 30.000 registered students. As part of a survey, 900 of these students are chosen at random. The average age in the sampe turns out to be 22.3 years and the SD is 4.5 years.</p>
<ol type="a">
<li><p>The average age of all 30.000 students is estimated as?</p></li>
<li><p>This estimate is likely to be off by ?</p></li>
<li><p>Find a 95 %-confidence interval for the average age of all 30.000 registered students.</p></li>
</ol>
</div>
</div>
</section>
</section>
<section id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="project-people-count-the-present-and-future-of-humanity-in-pictures-and-numbers"><span class="header-section-number">10.4</span> Project People count: The present and future of humanity in pictures and numbers</h2>
<p>In this course you have worked on a project called “people count” using demographic data. The context of census data and demographic data was used to apply some of the concepts we learned in this course, such as visualizing data, subsetting and extracting particular datasets from a larger dataset by using R’s subsetting rules. Compute the mean and median age for grouped data, quantify the uncertainty attached to such estimates using a bootstrap algorithm and predicting population growth. Often we looked at three typical countries, Kenya, a so called bottom layered country, because of the shape of its population barplot with the typical shape you get for a very young population, the US as an example of a middle layered country and Japan as an example for an aging society.</p>
<p>This week I want to encourage you to think about an outline for producing a data-story about your country using the analysis done during the project so far as a guide. It should be a text built around data and charts that tells the story of your country using the population numbers we used in this course from the JWLpackage and which are called population_statistics_by_age_and_sex. You may, but you need not also use a general demorgaphic dataset, if you want, which is called general_demograpics and which can be studied using the R help function, for the description of the variables.</p>
<p>The data-story should be:</p>
<ul>
<li>About 4 pages long</li>
<li>Written as a Jupyter Notebook.</li>
<li>Using the analysis you did in the project in units 1 - 6.</li>
<li>Describe your country, either your country where you have been born or where you are currently living.</li>
<li>Contain, text, graphics and data and using the two demographic datasets we used in the course.</li>
<li>Be roughly built around the template:
<ul>
<li>my country short description in word</li>
<li>my country viewed from the perspective of census data, a short demographic description in numbers, pictures and text, giving a view into the past (10 years ago) and giving an outlook into the future, say in 10 years from now)</li>
<li>Some concluding passage. You have considerable freedom in the way you write this but make sure to built in the analysis you did throughout the assignment. This will be one important element for the grading of the project work. Use the project work time of this week to make a plan for this essay and to familiarize yourself a bit with working with text and code in one Notebook.</li>
</ul></li>
</ul>
<p>Here is a very brief intro to the most basic elements.</p>
<p>Jupyter Notebooks use Markdown for formatting text. You have to choose <code>Markdown</code> from the menue bar above, such that Jupyter knows that the cell you are currently working in with text is a markdown cell and not a code cell.</p>
<p>Markdown is a lightweight, easy to learn markup language for formatting plain text.</p>
<p>Remember that this exercise sheet was written in a Jupyter notebook, so all of the narrative text and images you have seen so far were achieved writing in Markdown and code. Let’s cover the basics with a quick example:</p>
</section>
<section id="this-is-a-level-1-heading" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> This is a level 1 heading</h1>
<section id="this-is-a-level-2-heading" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="this-is-a-level-2-heading"><span class="header-section-number">11.1</span> This is a level 2 heading</h2>
<p>This is some plain text that forms a paragraph. Add emphasis via <strong>bold</strong> and <strong>bold</strong>, or <em>italic</em> and <em>italic</em>.</p>
<p>Paragraphs must be separated by an empty line.</p>
<ul>
<li>Sometimes we want to include lists.</li>
<li>Which can be bulleted using asterisks.</li>
</ul>
<ol type="1">
<li>Lists can also be numbered.</li>
<li>If we want an ordered list.</li>
</ol>
<p><a href="https://www.example.com">It is possible to include hyperlinks</a></p>
<p>Inline code uses single backticks: foo(), and code blocks use triple backticks:</p>
<pre><code>bar()</code></pre>
<p>Or can be indented by 4 spaces:</p>
<pre><code>foo()</code></pre>
<p>And finally, adding images is easy: <img src="https://www.example.com/image.jpg" class="img-fluid" alt="Alt text"></p>
<p>To see the source text from which these lines were compiled, double click into the cell. It will then show you the source text. When you execute the cell it will show you the formatted markup text.</p>
<p>Sharing Your Notebooks When people talk about sharing their notebooks, there are generally two paradigms they may be considering.</p>
<p>Most often, individuals share the end-result of their work, much like this article itself, which means sharing non-interactive, pre-rendered versions of their notebooks. However, it is also possible to collaborate on notebooks with the aid of version control systems such as Git or online platforms like Google Colab.</p>
<p>Before You Share A shared notebook will appear exactly in the state it was in when you export or save it, including the output of any code cells. Therefore, to ensure that your notebook is share-ready, so to speak, there are a few steps you should take before sharing:</p>
<p>Click “Cell &gt; All Output &gt; Clear” Click “Kernel &gt; Restart &amp; Run All” Wait for your code cells to finish executing and check ran as expected</p>
<p>This will ensure your notebooks don’t contain intermediary output, h ave a stale state, and execute in order at the time of sharing.</p>
<p>Exporting Your Notebooks Jupyter has built-in support for exporting to HTML and PDF as well as several other formats, which you can find from the menu under “File &gt; Download As.”</p>
<p>You can of course always share .ipynb files more directly and this is also the format I prefer for submitting your data essay.</p>


</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./probability.html" class="pagination-link" aria-label="Probability: Quantifying uncertainty and variabilility">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability: Quantifying uncertainty and variabilility</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./answering_questions_and_claiming_discoveries.html" class="pagination-link" aria-label="Answering questions and claiming discoveries">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Answering questions and claiming discoveries</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>